### ISSUE TITLE
Iredadmin issues with forwardings

### ISSUE THREAD

**Issue by prasannadt** [iredmail/iRedMail#1]
Error: IntegrityError(1062, "Duplicate entry 'team@designtreeconsultants.com-accounts@designtreeconsultants.co' for key 'address'") 

Getting this error while adding more users to the forwardings.

**Comment by iredmail** [comment]
How did you add forwardings?

**Comment by prasannadt** [comment]
Thru the gui.

**Comment by prasannadt** [comment]
After updating to iRedAdmin-Pro 4.1.1 the forwardings are not visible in the gui.

**Comment by prasannadt** [comment]
I had a list of forwarding from one email id to another and after updating to 4.1.1 when i try to add more addresses it gives me that error and also on checking inside the db the forwardings are missing

**Comment by iredmail** [comment]
I just fixed this issue and released iRedAdmin-Pro-SQL-4.1.2, could you please upgrade and try again?

- Login to iRedAdmin-Pro as global admin
- Go to the "License" page, then click button to request download link

Upgrade tutorial: https://docs.iredmail.org/migrate.or.upgrade.iredadmin.html

**Comment by prasannadt** [comment]
Sure i will

**Comment by prasannadt** [comment]
Working now. Thank you so much.
