### ISSUE TITLE
Testing CentOS 8 install.

### ISSUE THREAD

**Issue by MS2504** [iredmail/iRedMail#10]
steps done:
Installed CentOS 8 from scrap, updated. 
downloaded iRedMail from GitHub as a .zip file, unzipped.
# bash  iRedMail.sh

this is the log of errors :

# bash iRedMail.sh
[ INFO ] Checking configuration file: /home/admin/iRedMail-master/config ... [FOUND]
< Question > Use it for mail server setting? [y|N]y
[ INFO ] Use config file: /home/admin/iRedMail-master/config for mail server setting.
[ INFO ] Import installation process status from file: /home/admin/iRedMail-master/runtime/install.status.
[ INFO ] Add yum repo for SOGo: /etc/yum.repos.d/sogo.repo.
[ INFO ] Installing package(s): rsyslog firewalld postfix postfix-pcre postfix-mysql mariadb mariadb-server perl-DBD-MySQL php-common php-fpm php-gd php-xml php-mysqlnd php-ldap php-pgsql php-mbstring php-pecl-apcu php-intl nginx dovecot dovecot-pigeonhole dovecot-mysql amavisd-new spamassassin altermime perl-LDAP perl-Mail-SPF lz4 clamav clamav-update clamav-server clamav-server-systemd mlmmj sogo sogo-activesync libwbxml sogo-ealarms-notify sogo-tool sope49-gdl1-mysql gcc libcurl-devel openssl-devel python2-devel python2-pip python2-sqlalchemy python2-setuptools python2-dns python2-PyMySQL python2-jinja2 python2-requests fail2ban curl libmnl libuuid lm_sensors nc zlib iproute python2-pyyaml unzip bzip2 acl patch tmpwatch crontabs dos2unix logwatch lz4
No repository match: ius
No repository match: rpmforge
No repository match: atrpms
No repository match: remi
Inverse SOGo Repository                         533  B/s | 358  B     00:00
Failed to download metadata for repo 'SOGo'
Error: Failed to download metadata for repo 'SOGo'
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/

Do I have to manually add some repo?

**Comment by iredmail** [comment]
Fixed moment ago: https://github.com/iredmail/iRedMail/commit/9c50832623e9c991a2438b293d00065be2adaaa7

SOGo team doesn't offer binary packages for CentOS 8 yet, so we have to disable sogo in iRedMail installer.
