### ISSUE TITLE
Hide non-valid emails from Top Recipient and Received Mails statistic

### ISSUE THREAD

**Issue by camaer** [iredmail/iRedMail#101]
- iRedMail version (check /etc/iredmail-release): 1.3.2 PGSQL edition
- Deployed with iRedMail Easy or the downloadable installer? Downloadable installer
- Linux/BSD distribution name and version: Ubuntu 20.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL 
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? Yes

We have an email account with "Accepting Mails sent to this account on mail server" disabled in iRedAdmin-Pro
![Screen Shot 2020-12-10 at 11 14 04 AM](https://user-images.githubusercontent.com/35572989/101800437-46806300-3adb-11eb-928c-16042d2afc3a.png)

The issue is that even if the account is disabled and email can't be sent to this address, it appears in the **Top Recipients**  statistics
![Screen Shot 2020-12-10 at 11 16 03 AM](https://user-images.githubusercontent.com/35572989/101800625-7af41f00-3adb-11eb-8f59-5751b011a4a5.png)

Same thing in the **Received Mails** section
![Screen Shot 2020-12-10 at 11 26 14 AM](https://user-images.githubusercontent.com/35572989/101800713-8fd0b280-3adb-11eb-9ca2-10e6adfc49a5.png)

My suggestion is that invalid emails should not appear in the **Top Recipients** or **Received Mails** section or maybe there is a reason for this ?

Thanks

**Comment by iredmail** [comment]
Could you show us content of few emails received by this `noreply@` user? The content of mail "Undelivered Mail Returned to Sender".

**Comment by camaer** [comment]
I'm not sure if I can in the webui of iRedAdmin-Pro since I can't find the option. The main messages we get are out of office notifications. The norepy address is use as some form of reminder but if the recipient(external to our organisation) has an out of office message it writes back an email to the noreply. Hope it makes sense

**Comment by iredmail** [comment]
Could you please login to webmail as this account, then check the mail content?

**Comment by iredmail** [comment]
Why not enable IMAP temporarily for checking?

**Comment by camaer** [comment]
> Why not enable IMAP temporarily for checking?

You're right. Enabling IMAP and logging in worked but the mailbox was empty. Not a single email in the Inbox nor Sent folder

**Comment by iredmail** [comment]
The log shown in account's `Received Mails` page, and `Top Recipients` are extracted from Amavisd SQL database, seems email entered mail queue and scanned by Amavisd, but eventually discarded by Dovecot. This is not expected.

Expected behaviour is Postfix rejects emails sent to this `noreply@` account.

Could you please show me output of commands below (replace `noreply@domain.com` by the real email address):

```
cd /etc/postfix/pgsql/
for i in $(ls *cf); do echo $i; postmap -q noreply@domain.com pgsql:./$i; done
```

**Comment by camaer** [comment]
Sure thing. Here's the output:
```
catchall_maps.cf
domain_alias_catchall_maps.cf
domain_alias_maps.cf
recipient_bcc_maps_domain.cf
recipient_bcc_maps_user.cf
relay_domains.cf
sender_bcc_maps_domain.cf
sender_bcc_maps_user.cf
sender_dependent_relayhost_maps.cf
sender_login_maps.cf
noreply@domain.com
transport_maps_domain.cf
transport_maps_maillist.cf
transport_maps_user.cf
virtual_alias_maps.cf
noreply@domain.com
virtual_mailbox_domains.cf
virtual_mailbox_maps.cf
```

Here's in the mail log:

```
Dec  6 09:04:23 prd-mail-1n1 amavis[4018379]: (4018379-03) Passed CLEAN {RelayedInbound}, [xx.xx.xx.xx]:14608 [xx.xx.xx.xx] ESMTP/ESMTP <> -> <noreply@domain.com>, (ESMTPS://[xx.xx.xx.xx]:14608), Queue-ID: 3A26313C047, Message-ID: <b5f0d38698274eaab29d2ea@prod.outlook.com>, mail_id: 1W4jYa5kjKEu, b: Vun1bOFOf, Hits: 0.441, size: 11351, queued_as: 37B1113C41C, Subject: "Automatic reply: Out of Office", From: <George@externaldomain.com>, helo=CAN01-TO1-obe.outbound.protection.outlook.com, Tests: [ANY_BOUNCE_MESSAGE=0.1,DCC_REPUT_00_12=-0.8,DKIM_SIGNED=0.1,DKIM_VALID=-0.1,FORGED_SPF_HELO=1.042,HTML_MESSAGE=0.001,OOOBOUNCE_MESSAGE=0.1,RCVD_IN_DNSWL_NONE=-0.0001,RCVD_IN_MSPIKE_H2=-0.001,SPF_HELO_PASS=-0.001], autolearn=no autolearn_force=no, autolearnscore=1.242, dkim_i=@onmicrosoft.com, dkim_sd=onmicrosoft-com:onmicrosoft.com, 3924 ms
Dec  6 09:04:23 prd-mail-1n1 postfix/amavis/smtp[4042547]: 3A26313C047: to=<noreply@domain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=4.8, delays=0.91/0/0.01/3.9, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 37B1113C41C)
Dec  6 09:04:23 prd-mail-1n1 postfix/qmgr[2925232]: 3A26313C047: removed
Dec  6 09:04:23 prd-mail-1n1 postfix/pipe[4042582]: 37B1113C41C: to=<noreply@domain.com>, relay=dovecot, delay=0.05, delays=0.01/0/0/0.03, dsn=5.1.1, status=bounced (user unknown)
Dec  6 09:04:23 prd-mail-1n1 postfix/qmgr[2925232]: 37B1113C41C: removed
```

**Comment by iredmail** [comment]
> virtual_alias_maps.cf
> noreply@domain.com

Could you please remove one SQL row with commands below first:

```
USE vmail;
DELETE FROM forwardings WHERE address='noreply@domain.com';
```

Then run commands again:

```
cd /etc/postfix/pgsql/
for i in $(ls *cf); do echo $i; postmap -q noreply@domain.com pgsql:./$i; done
```

Also send a testing email to `noreply@domain.com` again and show us the Postfix log lines.

**Comment by camaer** [comment]
Seems to be fixed ! Could it be that there was a forward previously set (even though there was no forward set in IredAdmin-Pro) and disabling the **Accepting mails sent to this account on mail server** does not remove any forward for the address ? Now at least the email sent to noreply@domain.com are no longer visible in the statistic in iRedAdmin-Pro. Thanks for the help !

```
vmail=# select * from forwardings where address='noreply@domain.com';
 id  |      address       |     forwarding     |   domain   | dest_domain | is_list | is_forwarding | is_alias | active | is_maillist
-----+--------------------+--------------------+------------+-------------+---------+---------------+----------+--------+-------------
 180 | noreply@domain.com | noreply@domain.com | domain.com | domain.com  |       0 |             1 |        0 |      1 |           0
(1 row)
```
```
root@prd-mail-1n1:/etc/postfix/pgsql# for i in $(ls *cf); do echo $i; postmap -q noreply@domain.com pgsql:./$i; done
catchall_maps.cf
domain_alias_catchall_maps.cf
domain_alias_maps.cf
recipient_bcc_maps_domain.cf
recipient_bcc_maps_user.cf
relay_domains.cf
sender_bcc_maps_domain.cf
sender_bcc_maps_user.cf
sender_dependent_relayhost_maps.cf
sender_login_maps.cf
noreply@domain.com
transport_maps_domain.cf
transport_maps_maillist.cf
transport_maps_user.cf
virtual_alias_maps.cf
virtual_mailbox_domains.cf
virtual_mailbox_maps.cf
```
```
Dec 11 10:49:31 prd-mail-1n1 postfix/submission/smtpd[1140159]: connect from unknown[192.168.1.44]
Dec 11 10:49:31 prd-mail-1n1 postfix/submission/smtpd[1140159]: Anonymous TLS connection established from unknown[192.168.1.44]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Dec 11 10:49:31 prd-mail-1n1 postfix/submission/smtpd[1140159]: NOQUEUE: reject: RCPT from unknown[192.168.1.44]: 550 5.1.1 <noreply@domain.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<bob@domain.com> to=<noreply@domain.com> proto=ESMTP helo=<[192.168.1.44]>
Dec 11 10:49:31 prd-mail-1n1 postfix/submission/smtpd[1140159]: disconnect from unknown[192.168.1.44] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=6/7
```

**Comment by iredmail** [comment]
> Seems to be fixed ! Could it be that there was a forward previously set (even though there was no forward set in IredAdmin-Pro) and disabling the **Accepting mails sent to this account on mail server** does not remove any forward for the address ? Now at least the email sent to [noreply@domain.com](mailto:noreply@domain.com) are no longer visible in the statistic in iRedAdmin-Pro. Thanks for the help !

It should be considered as a bug of iRedAdmin-Pro.

I need a favor: could you please add the removed SQL row manually, but set `active=0`, and send testing email again?

```
USE vmail;
INSERT INTO forwardings (address, forwarding, domain, dest_domain, is_forwarding, active) VALUES ('noreply@domain.com', 'noreply@domain.com', 'domain.com', 'domain.com', 1, 0);
```

**Comment by camaer** [comment]
> If setting `active=0` works too, then we don't need to remove the row(s).

I can confirm that setting 'active=0' works too and the received emails don't appear in the statistic pages.

```
vmail=# select * from forwardings where address='noreply@domain.com';
  id  |      address       |     forwarding     |   domain   | dest_domain | is_list | is_forwarding | is_alias | active | is_maillist
------+--------------------+--------------------+------------+-------------+---------+---------------+----------+--------+-------------
 1116 | noreply@domain.com | noreply@domain.com | domain.com | domain.com  |       0 |             1 |        0 |      0 |           0
```

```
Dec 14 11:30:02 prd-mail-1n1 postfix/submission/smtpd[1872115]: connect from unknown[192.168.1.44]
Dec 14 11:30:02 prd-mail-1n1 postfix/submission/smtpd[1872115]: Anonymous TLS connection established from unknown[192.168.1.44]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Dec 14 11:30:02 prd-mail-1n1 postfix/submission/smtpd[1872115]: NOQUEUE: reject: RCPT from unknown[192.168.1.44]: 550 5.1.1 <noreply@domain.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<bob@domain.com> to=<noreply@domain.com> proto=ESMTP helo=<[192.168.1.44]>
Dec 14 11:30:02 prd-mail-1n1 postfix/submission/smtpd[1872115]: disconnect from unknown[192.168.1.44] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=6/7
```

**Comment by iredmail** [comment]
Thank you for the feedback. This has been fixed in iRedAdmin-Pro moment ago, i can send you a patched version if you want it now, contact us: https://www.iredmail.org/contact.html
