### ISSUE TITLE
iRedMail installation does not sanatize SQL commands

### ISSUE THREAD

**Issue by saandre15** [iredmail/iRedMail#104]
**Version**
1.3.2

**Deployed**
Downloadable Installer

**Distribution**
FreeBSD 12.2

**Backend**
OpenLDAP

**Web Server**
Nginx

The installer doesn't seem to sanitize SQL commands. Thus, any characters such as an apostrophe causes the installation break. In my case it was the inability to initialize the SQL server.

**Comment by iredmail** [comment]
Does it work if you use a password with just letters and digits?

**Comment by saandre15** [comment]
It works with letters and digits, perhaps there needs to be a character check put in place before the installation proceeds.

**Comment by iredmail** [comment]
The installation wizard shows a note to ask sysadmins not to use special characters, but it's clear displaying a message is not enough. :(

I will see what i can do to improve this.

**Comment by saandre15** [comment]
My bad. I was doing the installation in rush and I didn't see the message.
