### ISSUE TITLE
Remove pbl.spamhaus.org from postscreen_dnsbl_sites

### ISSUE THREAD

**Issue by Shnoulle** [iredmail/iRedMail#105]
zen.spamhaus.org lits all IP adress from end user.

But some end user start to have their own email server (with iredmail, yunohost, coszycloud, alternc … …) but zen.spamhaus.org disallow usage of self-hosting …

It can be great to move to xbl.spamhaus.org + sbl + css

Or (maybe) use
`zen.spamhaus.org=127.0.0.[2..7]*3 `by default ?

The important things is **by default** i can fix it in my mail server, but in my opinion :  pbl is always a bad idea.

**Comment by iredmail** [comment]
Sorry, no plan to remove pbl.spamhaus.org. Too many spammers send email from dynamic IP addresses.

**Comment by Shnoulle** [comment]
Then they are in SBL …
