### ISSUE TITLE
Possible error update-ldap-dovecot-2.3.py

### ISSUE THREAD

**Issue by mmmherma** [iredmail/iRedMail#109]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.2
- Deployed with iRedMail Easy or the downloadable installer? Downloadable installer
- Linux/BSD distribution name and version: Ubuntu 20.04.2
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? NO
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hello everyone,

Today I tried to execute the script `update-ldap-dovecot-2.3.py` and it didn't update my LDAP enabledService values.

Digging into the script y removed the byte literal at line 37 (https://github.com/iredmail/iRedMail/blob/master/update/ldap/update-ldap-dovecot-2.3.py#L37) and it worked like a charm. Seems like this field must not be treated as byte literal.

I executed the script using `python3.8 scripts/update-ldap/update-ldap-dovecot-2.3.py`.

Does anybody has experienced this issue?

Thank you.

**Comment by iredmail** [comment]
Thanks for the feedback. Fixed locally and will commit later (together with some other changes).
