### ISSUE TITLE
Invalid DB password.

### ISSUE THREAD

**Issue by masyagin1998** [iredmail/iRedMail#11]
Hello!

Thank You for awesome iRedMail. I have been working with it on CentOS-7 more than year and it is great!

Now I installed iRedMail successfully on CentOS-8 with PostgreSQL-12, Nginx and all dependencies.
After trying to make requests I get following results in /var/log/maillog for roundcube:
`DB Error: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "roundcube" in /opt/www/roundcubemail-1.4.3/program/lib/Roundcube/rcube_db.php on line 175 (GET /mail/)`

Also /iredadmin fails with 502 error on in /var/log/messages I got following: `WSGI app 1 (mountpoint='buildresource.ru|/iredadmin') ready in 0 seconds on interpreter 0xb69100 pid: 2074
Mar 16 12:34:27 d40641 uwsgi[1951]: Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/web/application.py", line 287, in process#012    return p(lambda: process(processors))#012  File "/usr/lib/python2.7/site-packages/web/session.py", line 96, in _processor#012    self._cleanup()#012  File "/usr/lib/python2.7/site-packages/web/session.py", line 203, in _cleanup#012    self.store.cleanup(timeout)#012  File "/usr/lib/python2.7/site-packages/web/session.py", line 367, in cleanup#012    self.db.delete(self.table, where="$last_allowed_time > atime", vars=locals())#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 1168, in delete#012    db_cursor = self._db_cursor()#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 736, in _db_cursor#012    return self.ctx.db.cursor()#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 676, in _getctx#012    self._load_context(self._ctx)#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 688, in _load_context#012    ctx.db = self._connect(self.keywords)#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 1228, in _connect#012    conn = DB._connect(self, keywords)#012  File "/usr/lib/python2.7/site-packages/web/db.py", line 716, in _connect#012    return self.db_module.connect(**keywords)#012  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect#012    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)#012OperationalError: FATAL:  password authentication failed for user "iredadmin"`

What should I do to fix bugs?

**Comment by iredmail** [comment]
The latest iRedMail-1.1 stable release doesn't support CentOS 8 yet, you have to check out the latest development edition instead. :)

**Comment by masyagin1998** [comment]
I installed latest version from Git for CentOS 8.

On CentOS 7 I have old stable version

**Comment by iredmail** [comment]
ok, seems a bug. I will test it and come back with a fix later. Stay tuned. :)

**Comment by masyagin1998** [comment]
Thank You!

**Comment by iredmail** [comment]
I can not produce this issue, all passwords are fine for me while testing.
Did you notice any error on console while running iRedMail installer?

**Comment by masyagin1998** [comment]
Only Python warnings:

`
Complete!
[ INFO ] Installing required Python-2 modules with pip.
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip2 install --user` instead.
Url '''/web-py/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: web.py==0.40 in /usr/lib/python2.7/site-packages
Url '''/pycurl/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: pycurl in /usr/lib64/python2.7/site-packages
Url '''/uwsgi/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: uwsgi in /usr/lib/python2.7/site-packages
Url '''/netifaces/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: netifaces in /usr/lib64/python2.7/site-packages
Url '''/cheroot/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: cheroot in /usr/lib/python2.7/site-packages (from web.py==0.40)
Url '''/markdown/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: markdown in /usr/lib64/python2.7/site-packages (from web.py==0.40)
Url '''/jaraco-functools/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: jaraco.functools in /usr/lib/python2.7/site-packages (from cheroot->web.py==0.40)
Url '''/six/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: six>=1.11.0 in /usr/lib/python2.7/site-packages (from cheroot->web.py==0.40)
Url '''/more-itertools/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: more-itertools>=2.6 in /usr/lib/python2.7/site-packages (from cheroot->web.py==0.40)
Url '''/backports-functools-lru-cache/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: backports.functools-lru-cache; python_version < "3.3" in /usr/lib/python2.7/site-packages (from cheroot->web.py==0.40)
Url '''/setuptools/' is ignored. It is either a non-existing path or lacks a specific scheme.
Requirement already up-to-date: setuptools>=36 in /usr/lib/python2.7/site-packages (from markdown->web.py==0.40)
`

**Comment by iredmail** [comment]
- Any related error in file ‘runtime/install.log’?
- did you use a custom pip mirror site?

**Comment by masyagin1998** [comment]
I used default pip mirror.

Checked `runtime/install.log`. Everything seems to be okay. Also in `install.status` all marked as done.

**Comment by masyagin1998** [comment]
In Nginx log found: `2020/03/16 18:46:24 [error] 16622#16622: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 109.252.125.249, server: _, request: "GET /iredadmin HTTP/1.1", upstream: "uwsgi://127.0.0.1:7791"`

**Comment by masyagin1998** [comment]
Now all works.
Sorry to bother you :(
