### ISSUE TITLE
iRedAdmin-Pro: RESTful API - GET /api/users/<domain> causing internal server error

### ISSUE THREAD

**Issue by topaz123123** [iredmail/iRedMail#110]
I try to test iRedAdmin-PRO RESTful API using demo accessible on the site https://demo-ldap.iredmail.org/. Everything seems to works well till the time when I created couple of user accounts either on example.com or newdomain.com domain. At the moment there is no way to explore user profiles list. Server returns "internal server error" every time I call "GET /api/users/<domain>"  function for both domains. After deleting former added users accounts (only one admin accout left) everything back to working fine. Is this a bug or I'm doing somethong wrong?

**Comment by iredmail** [comment]
Any error in /var/log/syslog or /var/log/messages?

**Comment by topaz123123** [comment]
I have no access to OS. It is demo site from iRedMail.org. Only web access allowed.

**Comment by iredmail** [comment]
Will check later and fix it. Thanks for the feedback. :)

**Comment by iredmail** [comment]
A reminder: the demo domains are not modifiable: example.com and test.com. Could you please create a new domain name and test with the new domain instead?

**Comment by topaz123123** [comment]
OK, I'll do it and will back. Thanks for advise.

**Comment by topaz123123** [comment]
OK, I finished the test. I created a new domain topaz123123.com and added users. If there is more than one account, a server error also occurs.

**Comment by iredmail** [comment]
Confirmed and fixed. You can now try again.
Thank you very much for the feedback. :)

**Comment by topaz123123** [comment]
Many thanks, now it is OK.
