### ISSUE TITLE
/var/vmail/backup/backup_mysql.sh: line 197: [: argument expected

### ISSUE THREAD

**Issue by zignzag12** [iredmail/iRedMail#111]
This error happens from time to time, not always... Using iRedMail-1.3.2 on Ubuntu 20.04.2 LTS x86_64 - no additional information in the detailed log /var/vmail/backup/mysql/2021/02/13/2021-02-13-03-30-01.log

==> Backup completed successfully.
**/var/vmail/backup/backup_mysql.sh: line 197: [: argument expected**
==> Detailed log (/var/vmail/backup/mysql/2021/02/13/2021-02-13-03-30-01.log):
=========================
* Starting backup: 2021-02-13-03-30-01.
* Backup directory: /var/vmail/backup/mysql/2021/02/13.
* Backing up databases: mysql vmail roundcubemail amavisd iredadmin sogo iredapd.
* File size:
----
44K	amavisd-2021-02-13-03-30-01.sql.bz2
8.0K	iredadmin-2021-02-13-03-30-01.sql.bz2
12K	iredapd-2021-02-13-03-30-01.sql.bz2
104K	mysql-2021-02-13-03-30-01.sql.bz2
4.0K	roundcubemail-2021-02-13-03-30-01.sql.bz2
8.0K	vmail-2021-02-13-03-30-01.sql.bz2
----
* Backup completed (Success? YES).

Line 197 of /var/vmail/backup/backup_mysql.sh:
if [ X"${REMOVE_OLD_BACKUP}" == X'YES' -a -d ${REMOVED_BACKUP_DIR} ]; then

**Comment by iredmail** [comment]
Please run it with “bash”, not “sh”.

**Comment by zignzag12** [comment]
It is running bash...

#!/usr/bin/env bash

**Comment by zignzag12** [comment]
And cron:
30   3   *   *   *   /bin/bash /var/vmail/backup/backup_mysql.sh

**Comment by iredmail** [comment]
Got it, it’s caused by empty value of variable “REMOVED_BACKUP_DIR”, will fix it soon. 

Thank you very much for the feedback. :)

**Comment by iredmail** [comment]
Could you please show me full output of commands below?

```
ls -l /bin/bash
bash -xv /var/vmail/backup/backup_mysql.sh
```

**Comment by zignzag12** [comment]
ls -l /bin/bash
-rwxr-xr-x+ 1 root root 1183448 Jun 18  2020 /bin/bash


bash -xv /var/vmail/backup/backup_mysql.sh
#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb@iredmail.org)
# Date:     16/09/2007
# Purpose:  Backup specified mysql databases with command 'mysqldump'.
# License:  This shell script is part of iRedMail project, released under
#           GPL v2.

###########################
# REQUIREMENTS
###########################
#
#   * Required commands:
#       + mysqldump
#       + du
#       + bzip2     # If bzip2 is not available, change 'CMD_COMPRESS'
#                   # to use 'gzip'.
#

###########################
# USAGE
###########################
#
#   * It stores all backup copies in directory '/var/vmail/backup' by default,
#     You can change it in variable $BACKUP_ROOTDIR below.
#
#   * Set correct values for below variables:
#
#       BACKUP_ROOTDIR
#       MYSQL_ROOT_USER
#       DATABASES
#       DB_CHARACTER_SET
#
#   * Add crontab job for root user (or whatever user you want):
#
#       # crontab -e -u root
#       1   4   *   *   *   bash /path/to/backup_mysql.sh
#
#   * Make sure 'crond' service is running, and will start automatically when
#     system startup:
#
#       # ---- On RHEL/CentOS ----
#       # chkconfig --level 345 crond on
#       # /etc/init.d/crond status
#
#       # ---- On Debian/Ubuntu ----
#       # update-rc.d cron defaults
#       # /etc/init.d/cron status
#

#########################################################
# Modify below variables to fit your need ----
#########################################################
# Keep backup for how many days. Default is 90 days.
KEEP_DAYS='90'
+ KEEP_DAYS=90

# Where to store backup copies.
export BACKUP_ROOTDIR="/var/vmail/backup"
+ export BACKUP_ROOTDIR=/var/vmail/backup
+ BACKUP_ROOTDIR=/var/vmail/backup

# MySQL username. Root user is required to dump all databases.
export MYSQL_ROOT_USER='root'
+ export MYSQL_ROOT_USER=root
+ MYSQL_ROOT_USER=root

# ~/.my.cnf
export MYSQL_DOT_MY_CNF='/root/.my.cnf'
+ export MYSQL_DOT_MY_CNF=/root/.my.cnf
+ MYSQL_DOT_MY_CNF=/root/.my.cnf

# Databases we should backup.
# Multiple databases MUST be seperated by SPACE.
export DATABASES='mysql vmail roundcubemail amavisd iredadmin sogo iredapd'
+ export 'DATABASES=mysql vmail roundcubemail amavisd iredadmin sogo iredapd'
+ DATABASES='mysql vmail roundcubemail amavisd iredadmin sogo iredapd'

# Database character set for ALL databases.
# Note: Currently, it doesn't support to specify character set for each databases.
export DB_CHARACTER_SET="utf8"
+ export DB_CHARACTER_SET=utf8
+ DB_CHARACTER_SET=utf8

#########################################################
# You do *NOT* need to modify below lines.
#########################################################
export PATH='/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin'
+ export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin

# Commands.
export CMD_DATE='/bin/date'
+ export CMD_DATE=/bin/date
+ CMD_DATE=/bin/date
export CMD_DU='du -sh'
+ export 'CMD_DU=du -sh'
+ CMD_DU='du -sh'
export CMD_COMPRESS='bzip2 -9'
+ export 'CMD_COMPRESS=bzip2 -9'
+ CMD_COMPRESS='bzip2 -9'
export COMPRESS_SUFFIX='bz2'
+ export COMPRESS_SUFFIX=bz2
+ COMPRESS_SUFFIX=bz2
export CMD_MYSQL="mysql --defaults-file=${MYSQL_DOT_MY_CNF} -u${MYSQL_ROOT_USER}"
+ export 'CMD_MYSQL=mysql --defaults-file=/root/.my.cnf -uroot'
+ CMD_MYSQL='mysql --defaults-file=/root/.my.cnf -uroot'
export CMD_MYSQLDUMP="mysqldump --defaults-file=${MYSQL_DOT_MY_CNF} -u${MYSQL_ROOT_USER} --events --ignore-table=mysql.event --default-character-set=${DB_CHARACTER_SET} --skip-comments"
+ export 'CMD_MYSQLDUMP=mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments'
+ CMD_MYSQLDUMP='mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments'

# Date.
export YEAR="$(${CMD_DATE} +%Y)"
++ /bin/date +%Y
+ export YEAR=2021
+ YEAR=2021
export MONTH="$(${CMD_DATE} +%m)"
++ /bin/date +%m
+ export MONTH=02
+ MONTH=02
export DAY="$(${CMD_DATE} +%d)"
++ /bin/date +%d
+ export DAY=15
+ DAY=15
export TIME="$(${CMD_DATE} +%H-%M-%S)"
++ /bin/date +%H-%M-%S
+ export TIME=23-25-49
+ TIME=23-25-49
export TIMESTAMP="${YEAR}-${MONTH}-${DAY}-${TIME}"
+ export TIMESTAMP=2021-02-15-23-25-49
+ TIMESTAMP=2021-02-15-23-25-49

# Pre-defined backup status
export BACKUP_SUCCESS='YES'
+ export BACKUP_SUCCESS=YES
+ BACKUP_SUCCESS=YES

# Define, check, create directories.
export BACKUP_DIR="${BACKUP_ROOTDIR}/mysql/${YEAR}/${MONTH}/${DAY}"
+ export BACKUP_DIR=/var/vmail/backup/mysql/2021/02/15
+ BACKUP_DIR=/var/vmail/backup/mysql/2021/02/15

# Find the old backup which should be removed.
export REMOVE_OLD_BACKUP='NO'
+ export REMOVE_OLD_BACKUP=NO
+ REMOVE_OLD_BACKUP=NO
if which python &>/dev/null; then
    export REMOVE_OLD_BACKUP='YES'
    py_cmd="import time; import datetime; t=time.localtime(); print datetime.date(t.tm_year, t.tm_mon, t.tm_mday) - datetime.timedelta(days=${KEEP_DAYS})"
    shift_date=$(python -c "${py_cmd}")
    shift_year="$(echo ${shift_date} | awk -F'-' '{print $1}')"
    shift_month="$(echo ${shift_date} | awk -F'-' '{print $2}')"
    shift_day="$(echo ${shift_date} | awk -F'-' '{print $3}')"
    export REMOVED_BACKUP_DIR="${BACKUP_ROOTDIR}/mysql/${shift_year}/${shift_month}/${shift_day}"
fi
+ which python

# Log file
export LOGFILE="${BACKUP_DIR}/${TIMESTAMP}.log"
+ export LOGFILE=/var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log
+ LOGFILE=/var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log

# Verify MySQL connection.
${CMD_MYSQL} -e "show databases" &>/dev/null
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'show databases'
if [ X"$?" != X"0" ]; then
    echo "[ERROR] MySQL username or password is incorrect in file ${0}." 1>&2
    echo "Please fix them first." 1>&2

    exit 255
fi
+ '[' X0 '!=' X0 ']'

# Check and create directories.
[ ! -d ${BACKUP_DIR} ] && mkdir -p ${BACKUP_DIR} 2>/dev/null
+ '[' '!' -d /var/vmail/backup/mysql/2021/02/15 ']'
chown root ${BACKUP_DIR}
+ chown root /var/vmail/backup/mysql/2021/02/15
chmod 0400 ${BACKUP_DIR}
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15

# Initialize log file.
echo "* Starting backup: ${TIMESTAMP}." >${LOGFILE}
+ echo '* Starting backup: 2021-02-15-23-25-49.'
echo "* Backup directory: ${BACKUP_DIR}." >>${LOGFILE}
+ echo '* Backup directory: /var/vmail/backup/mysql/2021/02/15.'
chmod 0400 ${LOGFILE}
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log

# Backup.
echo "* Backing up databases: ${DATABASES}." >> ${LOGFILE}
+ echo '* Backing up databases: mysql vmail roundcubemail amavisd iredadmin sogo iredapd.'
for db in ${DATABASES}; do
    #backup_db ${db} >>${LOGFILE}

    #if [ X"$?" == X"0" ]; then
    #    echo "  - ${db} [DONE]" >> ${LOGFILE}
    #else
    #    [ X"${BACKUP_SUCCESS}" == X'YES' ] && export BACKUP_SUCCESS='NO'
    #fi
    output_sql="${BACKUP_DIR}/${db}-${TIMESTAMP}.sql"

    # Check database existence
    ${CMD_MYSQL} -e "USE ${db}" &>/dev/null

    if [ X"$?" == X'0' ]; then
        # Dump
        ${CMD_MYSQLDUMP} ${db} > ${output_sql}
        chmod 0400 ${output_sql}

        if [ X"$?" == X'0' ]; then
            # Get original SQL file size
            original_size="$(${CMD_DU} ${output_sql} | awk '{print $1}')"

            # Compress
            ${CMD_COMPRESS} ${output_sql} >>${LOGFILE}
            chmod 0400 ${output_sql}.*

            if [ X"$?" == X'0' ]; then
                rm -f ${output_sql} >> ${LOGFILE}
            fi

            # Get compressed file size
            compressed_file_name="${output_sql}.${COMPRESS_SUFFIX}"
            compressed_size="$(${CMD_DU} ${compressed_file_name} | awk '{print $1}')"

            sql_log_msg="INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('backup', 'info', 'Database: ${db}, size: ${compressed_size} (original: ${original_size})', 'cron_backup_sql', '127.0.0.1', UTC_TIMESTAMP());"
        else
            # backup failed
            export BACKUP_SUCCESS='NO'
            sql_log_msg="INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('backup', 'info', 'Database backup failed: ${db}. Log: $(cat ${LOGFILE})', 'cron_backup_sql', '127.0.0.1', UTC_TIMESTAMP());"
        fi

        # Log to SQL table `iredadmin.log`, so that global domain admins can
        # check backup status (System -> Admin Log)
        ${CMD_MYSQL} iredadmin -e "${sql_log_msg}"
    fi
done
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE mysql'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments mysql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql
+ original_size=580K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/mysql-2021-02-15-23-25-49.sql.bz2
+ compressed_size=104K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: mysql, size: 104K (original: 580K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: mysql, size: 104K (original: 580K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE vmail'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments vmail
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql
+ original_size=40K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/vmail-2021-02-15-23-25-49.sql.bz2
+ compressed_size=8.0K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: vmail, size: 8.0K (original: 40K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: vmail, size: 8.0K (original: 40K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE roundcubemail'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments roundcubemail
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql
+ original_size=20K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/roundcubemail-2021-02-15-23-25-49.sql.bz2
+ compressed_size=4.0K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: roundcubemail, size: 4.0K (original: 20K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: roundcubemail, size: 4.0K (original: 20K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE amavisd'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments amavisd
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql
+ original_size=268K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/amavisd-2021-02-15-23-25-49.sql.bz2
+ compressed_size=44K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: amavisd, size: 44K (original: 268K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: amavisd, size: 44K (original: 268K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE iredadmin'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments iredadmin
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql
+ original_size=84K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/iredadmin-2021-02-15-23-25-49.sql.bz2
+ compressed_size=8.0K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: iredadmin, size: 8.0K (original: 84K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: iredadmin, size: 8.0K (original: 84K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/sogo-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE sogo'
+ '[' X1 == X0 ']'
+ for db in ${DATABASES}
+ output_sql=/var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql
+ mysql --defaults-file=/root/.my.cnf -uroot -e 'USE iredapd'
+ '[' X0 == X0 ']'
+ mysqldump --defaults-file=/root/.my.cnf -uroot --events --ignore-table=mysql.event --default-character-set=utf8 --skip-comments iredapd
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql
+ '[' X0 == X0 ']'
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql
+ original_size=76K
+ bzip2 -9 /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql
+ chmod 0400 /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql.bz2
+ '[' X0 == X0 ']'
+ rm -f /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql
+ compressed_file_name=/var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql.bz2
++ awk '{print $1}'
++ du -sh /var/vmail/backup/mysql/2021/02/15/iredapd-2021-02-15-23-25-49.sql.bz2
+ compressed_size=12K
+ sql_log_msg='INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: iredapd, size: 12K (original: 76K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'
+ mysql --defaults-file=/root/.my.cnf -uroot iredadmin -e 'INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('\''backup'\'', '\''info'\'', '\''Database: iredapd, size: 12K (original: 76K)'\'', '\''cron_backup_sql'\'', '\''127.0.0.1'\'', UTC_TIMESTAMP());'

# Append file size of backup files.
echo -e "* File size:\n----" >>${LOGFILE}
+ echo -e '* File size:\n----'
cd ${BACKUP_DIR} && \
${CMD_DU} *${TIMESTAMP}*sql* >>${LOGFILE}
+ cd /var/vmail/backup/mysql/2021/02/15
+ du -sh amavisd-2021-02-15-23-25-49.sql.bz2 iredadmin-2021-02-15-23-25-49.sql.bz2 iredapd-2021-02-15-23-25-49.sql.bz2 mysql-2021-02-15-23-25-49.sql.bz2 roundcubemail-2021-02-15-23-25-49.sql.bz2 vmail-2021-02-15-23-25-49.sql.bz2
echo "----" >>${LOGFILE}
+ echo ----

echo "* Backup completed (Success? ${BACKUP_SUCCESS})." >>${LOGFILE}
+ echo '* Backup completed (Success? YES).'

if [ X"${BACKUP_SUCCESS}" == X'YES' ]; then
    echo "==> Backup completed successfully."
else
    echo -e "==> Backup completed with !!!ERRORS!!!.\n" 1>&2
fi
+ '[' XYES == XYES ']'
+ echo '==> Backup completed successfully.'
==> Backup completed successfully.

if [ X"${REMOVE_OLD_BACKUP}" == X'YES' -a -d ${REMOVED_BACKUP_DIR} ]; then
    echo -e "* Old backup found. Deleting: ${REMOVED_BACKUP_DIR}." >>${LOGFILE}
    rm -rf ${REMOVED_BACKUP_DIR} >> ${LOGFILE} 2>&1

    sql_log_msg="INSERT INTO log (event, loglevel, msg, admin, ip, timestamp) VALUES ('backup', 'info', 'Remove old backup: ${REMOVED_BACKUP_DIR}.', 'cron_backup_sql', '127.0.0.1', UTC_TIMESTAMP());"
    ${CMD_MYSQL} iredadmin -e "${sql_log_msg}"
fi
+ '[' XNO == XYES -a -d ']'
/var/vmail/backup/backup_mysql.sh: line 197: [: argument expected

echo "==> Detailed log (${LOGFILE}):"
+ echo '==> Detailed log (/var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log):'==> Detailed log (/var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log):
echo "========================="
+ echo =========================
=========================
cat ${LOGFILE}
+ cat /var/vmail/backup/mysql/2021/02/15/2021-02-15-23-25-49.log
* Starting backup: 2021-02-15-23-25-49.
* Backup directory: /var/vmail/backup/mysql/2021/02/15.
* Backing up databases: mysql vmail roundcubemail amavisd iredadmin sogo iredapd.
* File size:
----
44K     amavisd-2021-02-15-23-25-49.sql.bz2
8.0K    iredadmin-2021-02-15-23-25-49.sql.bz2
12K     iredapd-2021-02-15-23-25-49.sql.bz2
104K    mysql-2021-02-15-23-25-49.sql.bz2
4.0K    roundcubemail-2021-02-15-23-25-49.sql.bz2
8.0K    vmail-2021-02-15-23-25-49.sql.bz2
----
* Backup completed (Success? YES).


On Feb 15, 2021, at 09:53, iRedMail <notifications@github.com> wrote:

﻿
Could you please show me full output of commands below?

ls -l /bin/bash
bash -xv /var/vmail/backup/backup_mysql.sh

**Comment by iredmail** [comment]
Seems you upgraded this server from and old iRedMail release but didn't upgrade the `backup_mysql.sh` script. This fix was introduced in iRedMail-1.1:
https://docs.iredmail.org/upgrade.iredmail.1.0-1.1.html#fixed-mysql-backup-script-doesnt-relies-on-python-anymore

**Comment by zignzag12** [comment]
No I installed from scratch

Sent from my iPad

On Feb 15, 2021, at 23:40, iRedMail <notifications@github.com> wrote:

﻿
Seems you upgraded this server from and old iRedMail release but didn't upgrade the backup_mysql.sh script. This fix was introduced in iRedMail-1.1:
https://docs.iredmail.org/upgrade.iredmail.1.0-1.1.html#fixed-mysql-backup-script-doesnt-relies-on-python-anymore

**Comment by zignzag12** [comment]
But you are right, /var/mail is it’s own file system and came from a previous install - would have been better if scripts were not in this location 

Sent from my iPad

On Feb 16, 2021, at 00:40, Magnus Larsson <mlarsson@mserv.pw> wrote:

﻿No I installed from scratch

Sent from my iPad

On Feb 15, 2021, at 23:40, iRedMail <notifications@github.com> wrote:

﻿
Seems you upgraded this server from and old iRedMail release but didn't upgrade the backup_mysql.sh script. This fix was introduced in iRedMail-1.1:
https://docs.iredmail.org/upgrade.iredmail.1.0-1.1.html#fixed-mysql-backup-script-doesnt-relies-on-python-anymore
