### ISSUE TITLE
Autoconfig gives 301

### ISSUE THREAD

**Issue by liszca** [iredmail/iRedMail#112]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
iRedMail  1.3.2

- Deployed with iRedMail Easy or the downloadable installer?
downloadable installer

- Linux/BSD distribution name and version: 
Debian 10

- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
LDAP

- Web server (Apache or Nginx):
NGINX
- Manage mail accounts with iRedAdmin-Pro?
LDAP
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

I am trying to setup autoconfig for my Thunderbird, but the test with curl returns 301.
```
 curl -k http://iredmail.der-space.prod/mail/config-v1.1.xml?emailaddress=ruby@mobilityacademy.de
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Same for `.well-known`

**Comment by iredmail** [comment]
iRedMail downloadable installer doesn't setup autoconfig support on server side.
