### ISSUE TITLE
ERROR: /var/log/clamav/freshclam.log is locked by another process

### ISSUE THREAD

**Issue by jp8** [iredmail/iRedMail#114]
- iRedMail version: 1.3.2
- Deployed with iRedMail Easy or the downloadable installer?  downloadable installer
- Linux/BSD distribution name and version: Debian 10 or Ubuntu 20.4
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx):Nginx
- Manage mail accounts with iRedAdmin-Pro?N

At the end of the install, I get the error related to the clamav log file:

* iRedMail-1.3.2 installation and configuration complete.
*************************************************************************

< Question > Would you like to use firewall rules provided by iRedMail?
< Question > File: /etc/nftables.conf, with SSHD ports: 22. [Y|n]
[ INFO ] Copy firewall sample rules.
< Question > Restart firewall now (with ssh ports: 22)? [y|N]
[ INFO ] Updating ClamAV database (freshclam), please wait ...
ERROR: /var/log/clamav/freshclam.log is locked by another process

**Comment by iredmail** [comment]
It's expected and safe to ignore it.

iRedMail installer tries to run "freshclam" command to update clamav virus signature database, but it was ran (by apt) after clamav package installed.
