### ISSUE TITLE
Wildcard SSL certification

### ISSUE THREAD

**Issue by NareshAvunoori** [iredmail/iRedMail#115]
Hi Team, 
I don't want to call it a bug or issue, but I feel somehow related to the knowledgebase and documentation.

I have installed the iRedMial server for internal purposes, in the intranet. was trying to implement the SSL (Wildcard) certificates, I don't see a direct approach or document to achieve the same. 

I have gone through the https://docs.iredmail.org/use.a.bought.ssl.certificate.html (Use the bought cert) for the iRedMail Easy platform, but I have installed it with the downloaded files, I am not able to see the directories /etc/pki/tls/**private** 

REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
1.3.2 MARIADB edition
- Deployed with iRedMail Easy or the downloadable installer?
downloadable installer
- Linux/BSD distribution name and version: 
CentOS Linux Release 8.3.2011
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
MySQL
- Web server (Apache or Nginx):
Nginx
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

**Comment by iredmail** [comment]
On CentOS 8, package `openssl-libs` will create `/etc/pki/tls/private/`. Please install it.
