### ISSUE TITLE
Notification to server admin when outgoing limit exceed for account

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#116]
We would like to have notification for admin when some user exceedes its throttling sending mail limit.
When user gets virus or loses its password - there is no information for an admin.

Is it possible with iredmail pro?
Do You plan to implement such feature in future?

**Comment by iredmail** [comment]
> We would like to have notification for admin when some user exceedes its throttling sending mail limit.

This is implemented and enabled by default in the latest iRedAPD for `throttle` plugin. Recipient is `root` user by default, and you should have an entry in `/etc/postfix/aliases` to forward root's email to some real email address (defaults to `postmaster@<your-first-mail-domain-name>`).

> When user gets virus or loses its password - there is no information for an admin.

- Amavisd sends notification to `root` too when spam/virus/bad-header email detected.
- I don't know what's "lose password" event. :(
