### ISSUE TITLE
Dropping mails with more than 10 recipients in "TO"

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#117]
Is it possible to set limit for an specified domain to not send mail messages with not more than 10 recipients in mail headers.

If not is there a plan for such feature?

**Comment by iredmail** [comment]
Not yet implemented, but it's possible.
Would you like to sponsor us to implement this feature?

**Comment by interduo** [comment]
That is the purpose why I bought pro license. What would be the price for such feature?

**Comment by iredmail** [comment]
Never mind, i did a quick check and not hard to implement, and finished moment ago:
https://github.com/iredmail/iRedAPD/commit/3f7bc97bffe1b2cf97c93caef419bc44b4d2494d

Could you please apply the patch and help test it with a testing machine?

**Comment by iredmail** [comment]
Hold on, current commit is not working. i'm working on a fix.

**Comment by iredmail** [comment]
Done, you can now try it with steps below:

```
wget https://github.com/iredmail/iRedAPD/archive/master.zip
unzip master.zip
rm -f master.zip
mv iRedAPD-master iRedAPD-4.9
cd iRedAPD-4.9/tools/
bash upgrade_iredapd.sh
```

The SQL table `iredapd.throttle` now has a new column named `max_rcpts`. You can update it to a proper (integer) value for some existing user/domain or globally, then test it by sending a message to multiple recipients which exceeds the `max_rcpts` value.

**Comment by interduo** [comment]
Will this setting be avaible in iRedAdmin Pro web panel in next version or only from iRedAPD or SQL?

**Comment by iredmail** [comment]
Available in both iRedAPD AND iRedAdmin-Pro.

**Comment by iredmail** [comment]
hi @interduo 

Did you have any chance to help test it? I'm going to tag a new stable release (v`5.0`) soon.
New iRedMail, mlmmjadmin and iRedAdmin-Pro are coming too.

**Comment by interduo** [comment]
Yes give me a day or two

**Comment by iredmail** [comment]
@interduo Any update?

**Comment by interduo** [comment]
Sorry for no response. 
I was trying to find some issues but now till next week I cannot do aby upgrades.

**Comment by interduo** [comment]
I did update in one of site. All is OK I think.
I did not found any updates. You could do a release.
