### ISSUE TITLE
Wrong php-fpm ip address in FreeBSD jail installation

### ISSUE THREAD

**Issue by santonatale** [iredmail/iRedMail#12]
Hi,

when installing iRedmail 1.1 in a Freebsd 12-STABLE jail, there is a configuration file that seems to contain a parameter with an incorrect value, making nginx replying with a "bad gateway" error.
The parameter is:
listen.allowed_clients = 127.0.0.1

in the file /usr/local/etc/php-fpm.d/www.conf . Instead of 127.0.0.1 the value should be the ip of the  LOCAL_ADDRESS variable (the ip address of the jail). Using it, it just works.
Thank you,

**Comment by iredmail** [comment]
Fixed. Thanks for the feedback. :)
It would be better if you can help test the latest iRedMail development edition in a new jail again.
