### ISSUE TITLE
Possibility to login to disabled account

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#120]
**Question:** 
Is there any possibility to login to disabled account with mail client (thunderbird) or web based mail client (roundcube)?

**Comment by iredmail** [comment]
You may want to keep the account enabled, but disallow him/her to use some mail services, e.g. smtp, imap, pop3, sogo, you can find these restrictions in iRedAdmin-Pro, user profile page, tab "Advanced".

In your case, you may want to disable SMTP/SOGO/sieve services, but allow IMAP/POP3.
