### ISSUE TITLE
Mail accounts iRedMail

### ISSUE THREAD

**Issue by Gashir** [iredmail/iRedMail#125]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  1.3.2 MARIADB edition.
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version:  CentOS Linux 7 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): mysql (MARIADB)
- Web server (Apache or Nginx): nginx
- Manage mail accounts with iRedAdmin-Pro? yes  iRedAdmin-Pro
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Good afternoon, we have a question about the work of iredmail. We have email accounts stored on the server in Mysql, we also have several email domains on our server, the question is whether it is possible to transfer email accounts of a certain domain to LDAP, and leave the rest in Mysql. That is, to separate the methods of storing and authenticating users for different mail domains within the iredmail server? Thanks.

**Comment by iredmail** [comment]
Do i understand correctly that you want to store few domain/accounts in LDAP, but few in SQL? Why?

**Comment by Gashir** [comment]
Addition: Also, for this mail domain, LDAP authentication is required.

**Comment by iredmail** [comment]
Technically you can store mail domains/accounts in multiple SQL/LDAP servers, the problem is how are you going to manage these mail accounts?

My personal suggestion is, if LDAP is required, then migrate ALL to LDAP.
