### ISSUE TITLE
Suggestion: add translate system implementation

### ISSUE THREAD

**Issue by AVAtarMod** [iredmail/iRedMail#126]
At now, all logs and user interact dialogs written in English, and all text is **hardcoded**.
Therefore, add translation is pain at current moment (as example, I would like to add Russian translate at this year).
I suggest several variants of implementation (sorted from bad and easy to good and more complex):
1. Split app into language versions, ex. move English version to EN folder, etc.
2. Store all output text in files for any part of text and then modify work with echo and dialogs functions to add the support of "cat $LANG/$name_message" as argument
3. Store all output text in **variables** (as at [obsidian-translations](https://github.com/obsidianmd/obsidian-translations)) and then modify echo and dialogs functions to add the support of parsing process for variables
Second variant is good, but third is much better, because work of translators will be more easiest and clean,so I suggest №3.

**Comment by iredmail** [comment]
Thanks for the suggestion. 
The installation wizard / dialog is used for just few minutes, Is it really necessary?

**Comment by AVAtarMod** [comment]
I think if this app will more popular, then more people will need to translate, therefore I think yes, it will be cool if people will have the possibility easily translate this app.

**Comment by iredmail** [comment]
I'm sorry that no plan for this shortly.
