### ISSUE TITLE
[Feature request] Run as TOR hidden service option

### ISSUE THREAD

**Issue by 78bash** [iredmail/iRedMail#128]
Having the option, during install time, to have iRedMail run as a TOR hidden service would be a nifty hack.

Coding the TOR part of this feature into the install script invoves installing the `tor` package and editing its configuration files as [instructed here](https://2019.www.torproject.org/docs/tor-onion-service) to create the hidden service.

I'm not sure about the iRedMail part though, but I could contribute what I already know as well as complete testing.

**Comment by iredmail** [comment]
No plan for such integration. Sorry.
