### ISSUE TITLE
Send email attachments to an external server?

### ISSUE THREAD

**Issue by zipzit** [iredmail/iRedMail#131]
I'm working on an unusual application.  I'd like to receive emails with an image attachment, then have the ability to access that attachment from my own server (in this case to do some simple Artificial Intelligence / machine learning analysis on the image. )  My intent is to catch an email image attachment, plus the "from email address", plus a "date time" and send that to an external server.  After that the incoming emails are simply deleted.  

If I were using Twilio SendGrid, I'd be using the ["Inbound Parse Webhook" ](https://sendgrid.api-docs.io/v3.0/settings-inbound-parse/create-a-parse-setting)to break out the multipart / form-data.  

I'm pretty sure I can work directly with the email storage database essentially the same thing, but I'm wondering if such a thing exists within iRedMail setup?  

Many thanks...

**Comment by iredmail** [comment]
No. You can try other Postfix milter program instead. Or, write a simple Python script as milter program to extract attachment.

**Comment by zipzit** [comment]
I'm assuming you are referring to [this. ](http://www.postfix.org/MILTER_README.html)   And yes, at first glance that looks sort of ugly.  Sounds more like direct access to the Database might be a way to go.  

Many thanks to the iRedMail team for their support here.
