### ISSUE TITLE
Bullseye 11 - Last install stops

### ISSUE THREAD

**Issue by ludovicandrieux** [iredmail/iRedMail#133]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): actual master of today (1.4.1 ?)
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: debian 11 bullseye
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): no revelant
- Web server (Apache or Nginx): no revelant
- Manage mail accounts with iRedAdmin-Pro? no revelant
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hi,
I tried to install iredmail on a debian 11 bullseye.
Standard 1.4.0 stop at the beginning because it's not supported.
I downloaded the last version from the master.
The test of OS is OK now but the installer stop after because it can't download iredadmin 1.5
Best regards

**Comment by iredmail** [comment]
Fixed. Thanks for the feedback. :)
