### ISSUE TITLE
SOGo Groupware in bullseye

### ISSUE THREAD

**Issue by ludovicandrieux** [iredmail/iRedMail#134]
Hi,
I refer to this commit : https://github.com/iredmail/iRedMail/commit/3401f4b483a1570c83ed1d8d508112ba1a2b410f
It seems there is no support for SOGo Groupware for bullseye
But i found an official package here : https://packages.debian.org/bullseye/sogo
Do you planned to add this one in your product ?
Best regards

**Comment by iredmail** [comment]
No. The binary packages in Debian official apt repo is not always up to date, so we prefer the SOGo nightly build instead.
For example, Debian 11 ships SOGo-5.0.1, but the latest SOGo release is 5.2.0 with a security fix. FYI:
https://www.sogo.nu/news.html
