### ISSUE TITLE
Increase security in nginx SSL

### ISSUE THREAD

**Issue by ludovicandrieux** [iredmail/iRedMail#136]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.2
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: Debian 11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hi

After a successfull installed 1.4.2, i try a test with https://www.ssllabs.com/ssltest/

The score by default is A that is good
![image](https://user-images.githubusercontent.com/11213740/133117825-0e089a95-4bca-42f1-b874-a4858fadb74c.png)

There is only one real problem that concerns you
![image](https://user-images.githubusercontent.com/11213740/133117946-453c751c-0883-4c53-bc66-87beca71682f.png)

With only two changes, one in /etc/nginx/templates/ssl.tmpl , you should add something like that
`ssl_session_cache shared:ssl_session_cache:10m;`
And one to activate HSTS everywhere
You could have after that a A+ 
![image](https://user-images.githubusercontent.com/11213740/133118290-d21f1e55-bbbd-4b1a-b002-d08cf54bacdc.png)
![image](https://user-images.githubusercontent.com/11213740/133118417-ae72a0e5-1246-467a-bcd1-a4de26adade2.png)

Best regards

**Comment by iredmail** [comment]
PR is welcome. :)
