### ISSUE TITLE
TLSv1.3 in webserver

### ISSUE THREAD

**Issue by ludovicandrieux** [iredmail/iRedMail#137]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.2
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: Debian 11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No

Hi
Do you plan to activate TLSv1.3 in addition with TLSv1.2 ?
Best regards

**Comment by iredmail** [comment]
PR (pull request) is welcome. :)
