### ISSUE TITLE
Improve ciphers in SSL

### ISSUE THREAD

**Issue by ludovicandrieux** [iredmail/iRedMail#138]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.2
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: Debian 11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No

Hi
In the continuation of my previous tickets about SSL, i think ciphers could be improved.

Now, you have in ssl.tmpl
`ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;`

You can remove 'AES256+EDH'(it's weak) in order to have
`ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH;` 

You can add a modern cipher 'EECDH+CHACHA20' like this
`ssl_ciphers EECDH+CHACHA20:EECDH+AESGCM:EDH+AESGCM:AES256+EECDH;` 

With this change, you have the same support of browser but it could be better with remove of 'AES256+EECDH' 
`ssl_ciphers EECDH+CHACHA20:EECDH+AESGCM:EDH+AESGCM;` 
but Safari 6/7/8 on Mac OS X 10.10 (and previous) and iOS 8.4 (and previous) will not work anymore, all other browser will be good

Best regards

**Comment by iredmail** [comment]
Using only modern / secure ciphers might cause issue with old clients (MUA, web browser, etc). I prefer keeping current ciphers, but adding new one like `EECDH+CHACHA20` is ok.

Did you try EECDH+CHACHA20 on different linux/bsd releases?

- CentOS 7, 8
- CentOS Stream 8
- Rocky Linux 8
- Debian 9, 10, 11
- Ubuntu 18.04, 20.04
- OpenBSD 6.9
- FreeBSD 13

**Comment by ludovicandrieux** [comment]
About old cipher, you can remove "AES256+EDH" without problems because you keep "AES256+EECDH". I think it's just better to reduce a little bit weak ciphers.

About EECDH+CHACHA20, I use it on my servers with Debian 10 (and 11 of course). 

Usualy, a cipher is managed by OpenSSL and it was introduce in OpenSSL 1.0.2h and OpenSSL 1.1.0 : https://www.openssl.org/news/openssl-1.1.0-notes.html
For Debian 9, it should be good because it use OpenSSL 1.1.0l : https://packages.debian.org/stretch/openssl

Best regards

**Comment by iredmail** [comment]
All your 3 contributions now live in iRedMail development edition, and i mentioned the changes in upgrade tutorial for next iRedMail release (maybe 1.4.3, but version number is not the point):
https://docs.iredmail.org/upgrade.iredmail.1.4.2-1.4.3.html

THANK YOU VERY MUCH.

**Comment by ludovicandrieux** [comment]
You're welcome @iredmail

**Comment by ludovicandrieux** [comment]
Just a small addition about Ubuntu 18.04 (and 20.04 by the way), both supports :
- Nginx 1.13.0+ (TLSv1.3) : https://packages.ubuntu.com/bionic/nginx
- OpenSSL 1.1.0+ (EECDH+CHACHA20) : https://packages.ubuntu.com/bionic/openssl

Best regards

**Comment by iredmail** [comment]
Thanks for the feedback. I already tested this cipher (and TLSv1.3) with iRedMail Easy platform locally after you posted this issue. :)

- TLSv1.3 is not available on Debian 9 since Nginx is older than 1.13.0.
- EECDH+CHACHA20 is ok on all distribution releases.

**Comment by ludovicandrieux** [comment]
OK Nice :)
So there is just a bug in documentation for Ubuntu. Here for exemple : https://docs.iredmail.org/upgrade.iredmail.1.4.2-1.4.3.html
![image](https://user-images.githubusercontent.com/11213740/133455261-2612354e-8a31-40c8-aea2-9c040d0d8478.png)

**Comment by iredmail** [comment]
Added Ubuntu (18.04+) in doc. :)

**Comment by ludovicandrieux** [comment]
👍
