### ISSUE TITLE
iRedAdmin-Pro-SQL-4.9

### ISSUE THREAD

**Issue by laiyukwa** [iredmail/iRedMail#139]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

**Comment by laiyukwa** [comment]
I am using Freebsd 13 and iredmail-1.4.2 with iRedAdmin-Pro-SQL-4.9, and find the following errors showing "internal server error" : -

1. system->Global Spam Policy  --- internal server error
2. create domain -- after creating a domain showing internal server error but such domain can successfully created.
3. create user -- after creating a user showing internal server error but such user can successfully created.

Please help.

Mr. Y. W. Lai

**Comment by iredmail** [comment]
Any error in `/var/log/messages` when you got the `internal server error`?

**Comment by laiyukwa** [comment]
Dear Sir,

I only got the message :-

Sep 21 11:37:00 x100 iredadmin 0 (/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/f2b/log.py, L18)

No other

**Comment by iredmail** [comment]
There must be some other log lines above or below this line, please double check.

**Comment by laiyukwa** [comment]
I discover that my situation is appeared in a fresh installation.  But in upgrade from iredadmin-pro 4.8, it is not and is without this problem.

On the other hand, I also discover in fresh installation of Freebsd 13 and iredadmin-pro 4.9 that a directory of /usr/local/www/iredadmin/__pycache__ is created by the root with two files of settings.cpython-38.pyc and iredadmin.cpython-38.pyc.  Even if you delete the file of iredadmin.cpython-38.pyc, iredadmin-pro will automatically create this file again.   Even if I change the ownership to iredadmin (/usr/local/www/iredadmin/__pycache__), there is no difference with the same result of the internal server error being still continued.

In upgrade situation, only settings.cpython-38.pyc is existed in the such directory.

Mr. Lai

**Comment by iredmail** [comment]
These __pycache__ files are safe to ignore, it’s generated by Python 3.

try this way to get detailed debug:

- append line “ MAIL_ERROR_TO_WEBMASTER = True” in /usr/local/www/iredadmin/settings.py
- restart iredadmin service
- Trigger the issue again. Then your email address (defined in parameter “webmaster” in iRedAdmin-Pro config file) will receive a HTML file with detailed error report. Mail me this html file for troubleshooting.

**Comment by laiyukwa** [comment]
Thanks you for your information.

The error coming from Global Spam Policy and Create Domain/User is the same and is ‘_banned_rulenames’ being undefined.

The following is such error message :-

Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/web/application.py", line 280, in process
   return self.handle()
 File "/usr/local/lib/python3.8/site-packages/web/application.py", line 271, in handle
   return self._delegate(fn, self.fvars, args)
 File "/usr/local/lib/python3.8/site-packages/web/application.py", line 517, in _delegate
   return handle_class(cls)
 File "/usr/local/lib/python3.8/site-packages/web/application.py", line 495, in handle_class
   return tocall(*args)
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/controllers/decorators.py", line 120, in proxyfunc2
   return func(*args, **kw)
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/controllers/decorators.py", line 15, in proxyfunc
   return func(*args, **kw)
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/controllers/amavisd/spampolicy.py", line 106, in GET
   return web.render(
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/iredbase.py", line 178, in render_template
   return jinja_env.get_template(template_name).render(kwargs)
 File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
   self.environment.handle_exception()
 File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
   raise rewrite_traceback_stack(source=source)
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/../templates/default/amavisd/spampolicy.html", line 44, in top-level template code
   {% block main %}
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/../templates/default/layout.html", line 205, in top-level template code
   {% block main %}{% endblock %}
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/../templates/default/amavisd/spampolicy.html", line 55, in block 'main'
   {{ display_spam_policy(account_type=account_type,
 File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 828, in _invoke
   rv = self._func(*arguments)
 File "/usr/local/www/iRedAdmin-Pro-SQL-4.9/libs/../templates/default/macros/amavisd.html", line 347, in template
   {% if "ALLOW_MS_OFFICE" in _banned_rulenames %}checked="checked"{% endif %}
jinja2.exceptions.UndefinedError: '_banned_rulenames' is undefined

**Comment by iredmail** [comment]
Confirmed it's a bug of iRedAdmin-Pro-SQL-4.9. Here's the patch to fix it. Don't forget to restart `iredadmin` service after patched.

If you're not familiar with patch, please contact us to get a patched version of iRedAdmin-Pro.

Thank you very much for the report. :)

```
diff --git a/templates/default/macros/amavisd.html b/templates/default/macros/amavisd.html
index c39a2229..814ed0d4 100644
--- a/templates/default/macros/amavisd.html
+++ b/templates/default/macros/amavisd.html
@@ -219,9 +219,10 @@
     {% set _virus_quarantine_to = spampolicy.get('virus_quarantine_to') %}
     {% set _banned_quarantine_to = spampolicy.get('banned_quarantine_to') %}
     {% set _bad_header_quarantine_to = spampolicy.get('bad_header_quarantine_to') %}
+    {% set _banned_rulenames = [] %}
 
     {# banned_rulenames could be whitespace-separated or comma-separated, we use comma-separated syntax but try to support comma-separated too. #}
-    {# replace whiltespace by comma, then split by comma #}
+    {# replace whiltespace by comma first, then split by comma #}
     {% set _sql_banned_rulenames = spampolicy.get("banned_rulenames", "") %}
     {% if _sql_banned_rulenames %}
         {% set _banned_rulenames = _sql_banned_rulenames.replace(" ", ",").split(",") %}
```

**Comment by laiyukwa** [comment]
Thank you for your assistance but I am not familiar with patch.  Please give me a patched version of IRedAdmin-Pro.

**Comment by laiyukwa** [comment]
I have resolved the patch problem.  No need to give me.

Thanks again
