### ISSUE TITLE
Use apt instead of apt-get

### ISSUE THREAD

**Issue by IIPoliII** [iredmail/iRedMail#14]
Hey,

I just saw about iredmail and finnaly founded a working thing. 
In ubuntu/debian the code is using apt-get wich is recommanded too in scripts but if you use apt (there will be a little warning) but there will be a progress bar that could be an intressting freature.

**Comment by iredmail** [comment]
Oops, have to revert my commit due to this warning:

> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by IIPoliII** [comment]
No worries that's the issue i said. I will look maybe we can show a progress bar with a setting using `apt-get`

**Comment by IIPoliII** [comment]
https://askubuntu.com/questions/245808/view-progress-of-a-package-installation-in-terminal

it looks like it's possible with `sudo apt-get install <package> | debconf-apt-progress`
