### ISSUE TITLE
typo in variable name ENABLED_SERVICES in functions/packages.sh

### ISSUE THREAD

**Issue by elchusco** [iredmail/iRedMail#140]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hi not sure how important it is, but there is a typo on the variable name ENABLED_SERVICES (currently named NABLED_SERVICES) in functions/packages.sh file line 27.

Just to let you know.

Thx for your amazing job

**Comment by iredmail** [comment]
> not sure how important it is

It's used to initial or reset a variable. Since `ENABLED_SERVICES` is not defined in other files, so bash shell considers it's empty string by default. Not bug or issue introduced.

Thanks for the feedback. :)
