### ISSUE TITLE
Very short session time

### ISSUE THREAD

**Issue by JuzioMiecio520** [iredmail/iRedMail#141]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.2 MARIADB edition.
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: Debian GNU/Linux 10 (buster) x86_64
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

I just downloaded and successfully installed iRedMail server on my VPS. The problem is, after logging in on iRedAdmin or Roundcube, the session time is only a couple of seconds and after it runs out immediately logs me out. It's a fresh install so I haven't yet changed anything in the config file. Also, the SESSION_TIMEOUT option seems to be missing from `/opt/www/iredadmin/settings.py`. Can anyone please tell me how I can lengthen the session time?

**Comment by crackersam** [comment]
well (please) how do we fix it, i've got the same issue
