### ISSUE TITLE
Normal admin can add domains or not ? | iRedAdmin Pro 

### ISSUE THREAD

**Issue by ChandanP1994** [iredmail/iRedMail#142]
Hi Team,

I have configured iRedAdmin Pro version in my VPS : Ubuntu 18.04
iRedadmin version :  iRedAdmin-Pro-SQL-4.9
Everything is working fine, 

My question is : 

I have added **admin** from the **global admin** access, 
My normal admin dashboard there are no option for adding domains, I have checked the permission but I didn't get the right solution for adding domain from normal admin dashboard. 

Only the **global admin** can add domains ?

Please let me the right permissions for adding domains from **normal admin dashboard**.

Thanks.
Chandan

**Comment by iredmail** [comment]
Please go to admin profile page and grant the required privileges for adding new domains.
<img width="805" alt="Screen Shot 2021-11-01 at 9 01 14 PM" src="https://user-images.githubusercontent.com/2048991/139675649-2717a1c4-af89-4d1b-94e5-9a7ec103e9e1.png">
