### ISSUE TITLE
API call to update user password resets mailboxfolder to blank value

### ISSUE THREAD

**Issue by joel6890** [iredmail/iRedMail#143]
- iRedMail version 1.4.2 PGSQL edition
- Deployed with the downloadable installer some versions back and upgraded per instructions
- Linux/BSD distribution name and version: Ubuntu Server 20.04 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  PGSQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? Yes, iRedAdmin-Pro version 4.9

ISSUE: Doing a PUT to `/api/user/<mail>` with payload of `{'password': '<new-password>'}` resets the `mailboxfolder` column of vmail database to an empty string.

WORKAROUND: To avoid this behavior, we must use `{'password': '<new-password>', 'mailboxFolder': 'Maildir'}`

Issue may have started at the same time we upgraded to iRedAdmin 4.9.

**Comment by iredmail** [comment]
Dear  @joel6890 

Thanks for the feedback.
This is a known bug and fixed days ago, the fix will be available in upcoming iRedAdmin-Pro release.
