### ISSUE TITLE
Version 1.4.2 not equal to actual downloads

### ISSUE THREAD

**Issue by mr-manuel** [iredmail/iRedMail#146]
Hello,

I saw, that the actual GitHub code from version 1.4.2 is not equal to the versions which you can download from your [website](https://www.iredmail.org/download.html) and from https://github.com/iredmail/iRedMail/releases/tag/1.4.2

E.g.: This commit is missing: https://github.com/iredmail/iRedMail/commit/58a0801471f482227777b08c42b4283954eef47e#diff-5c801389dfab656b79afe865f776615375c1ed427f4e4d83bfddf71ef62b72d5

**Comment by iredmail** [comment]
1.4.2 was tagged on Sep 13, the "missing" commit was committed in Oct.
I don't get your point. :(

**Comment by mr-manuel** [comment]
Download the stable version from here: https://www.iredmail.org/download.html and open the "web_applications.sh" file in the "dialog" directory. Check line 37. This prevents the installation of SOGo under Debian 11 (Bullyeye) even if it is supported. If you compare to the GitHub codebase this line was removed. So why not in the downloadable versions?

**Comment by iredmail** [comment]
`1.4.2` was tagged on Sep 13, the removed line was committed in Oct.
We didn't re-tag version 1.4.2 with this change.

**Comment by mr-manuel** [comment]
Ok, so maybe it should be retaged or the description should be moved to the next version. Since this is confusing for me and others: https://forum.iredmail.org/topic18568-sogo-not-showing-up-in-the-installer.html

**Comment by iredmail** [comment]
We will tag a new iRedMail release soon, it will fix the issue you reported. Thanks for the feedback. :)
