### ISSUE TITLE
[feature request] make firewall an option in the install process

### ISSUE THREAD

**Issue by changchichung** [iredmail/iRedMail#147]
May I suggest making firewall an option (install or not ) in the installation process ?

I guess in some environment , there are "real firewall" behind the iredmail instance. so the ufw/iptables in iredmail seems not that necessary.

I always change the default ssh port , and forgot to update ufw. that make me not able to ssh iredmail.

hope that during the install process , there's an option to choose install/enable ufw/iptables or not (maybe default on is a good idea)

**Comment by Anzulo1984** [comment]
Isn't this implemented already?

afaik, there was a prompft if firewall rules should be applied and enforced on last test install

so this can be closed i guess?
