### ISSUE TITLE
PHP wrong config when you have the lastest version installed (via ppa)

### ISSUE THREAD

**Issue by IIPoliII** [iredmail/iRedMail#15]
Hey,
Thanks for that awesome fast fix!
Now i just founded out i have a issue with php since i use php7.4 (and upgraded to it) the php7.2 folder exsists but the php-ini or php-fpm.conf don't exsist. I know that under ubuntu if you use the default packages you would use only php7.2 but in this case the problem is that the apt you are using is surely written like `apt install php php-xml php-mymoduleblalal` but when you generate the config it goes in `php/7.2` ( i am not sure if it's checking or not trough).

Maybe you already did it but there is 2 possiblities or you define the version in apt or yum,... by doing `apt install php7.2 php7.2-xml` or you can use the php -v command and find the php version with like `php --version | head -n 1 | cut -d " " -f 2` or ` php --version | head -n 1 | cut -d " " -f 2 | cut -c 1,3`

I founded it out because i can't see my webserver.

**Comment by iredmail** [comment]
No plan to “fix” this at all. 

iRedMail uses packages from official apt repositories, not PPA or any other third-party repos, we cannot cover them all.
