### ISSUE TITLE
Installation Error When Configuring slapd

### ISSUE THREAD

**Issue by Sputnik93** [iredmail/iRedMail#150]
Hi !

- iRedMail version (check /etc/iredmail-release):  **1.5.1**
- Deployed with iRedMail Easy or the downloadable installer? **with downloadable installer**
- Linux/BSD distribution name and version: **Debian 11.2**
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  **LDAP**
- Web server (Apache or Nginx): **Nginx**
- Manage mail accounts with iRedAdmin-Pro? **No**
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
```
Setting up slapd (2.4.57+dfsg-3) ...
  Creating new user openldap... done.
  Creating initial configuration... mktemp: failed to create file via template '/tmp/user/0/slapadd.XXXXXX': No such file or directory
dpkg: error processing package slapd (--configure):
 installed slapd package post-installation script subprocess returned error exit status 1

[...]

Errors were encountered while processing:
 slapd
E: Sub-process /usr/bin/dpkg returned an error code (1)
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/
```
slapd version is 2.4.57+dfsg-3

**Comment by iredmail** [comment]
Seems a Debian packaging issue. Could you use a different apt mirror site and try again?

**Comment by Sputnik93** [comment]
You're right, it seems I can not install slapd on my LXC container (nor 2.4.57 from various Bullseye repos, nor 2.4.59 from backports), postinst fails at the same line.
Anyway, this is obviously not related to iRedMail, sorry for the issue (and thank you for your work) !
