### ISSUE TITLE
SoGo Fails to install on clean install of Debian 11 using bash iRedMail.sh  (gnupg, gnupg2 and gnupg1 do not seem to be installed)

### ISSUE THREAD

**Issue by mikebetz42** [iredmail/iRedMail#152]
[ INFO ] Add apt repo for SOGo: https://packages.inverse.ca
[ INFO ] Import apt key (0x810273C4) for SOGo repo (https://packages.inverse.ca).
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
[ INFO ] Resynchronizing the package index files (apt update) ...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:5 http://deb.debian.org/debian bullseye-backports InRelease
Get:6 https://packages.inverse.ca/SOGo/nightly/5/debian bullseye InRelease [2565 B]
Err:6 https://packages.inverse.ca/SOGo/nightly/5/debian bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 19CDA6A9810273C4
Reading package lists... Done
W: GPG error: https://packages.inverse.ca/SOGo/nightly/5/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 19CDA6A9810273C4
E: The repository 'https://packages.inverse.ca/SOGo/nightly/5/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[ INFO ] Installing package(s): python3-setuptools python3-pip python3-wheel python3-requests uwsgi uwsgi-plugin-python3 postfix postfix-pcre libsasl2-modules mariadb-client mariadb-server postfix-mysql libdbd-mysql-perl php-cli php-fpm php-json php-gd php-curl mcrypt php-intl php-xml php-mbstring php-zip php-mysql nginx-full dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-managesieved dovecot-sieve dovecot-mysql amavisd-new libcrypt-openssl-rsa-perl libmail-dkim-perl clamav-freshclam clamav-daemon spamassassin altermime arj nomarch cpio lzop cabextract p7zip-full rpm libmail-spf-perl unrar-free pax lrzip gpg-agent mlmmj python3-pymysql memcached sogo sogo-activesync sope4.9-gdl1-mysql python3-sqlalchemy python3-dnspython python3-pymysql python3-jinja2 python3-netifaces python3-bcrypt python3-dnspython python3-simplejson python3-pymysql fail2ban geoip-bin geoip-database zlib1g libuuid1 libmnl0 curl lm-sensors netcat bzip2 acl patch cron tofrodos logwatch unzip bsdutils liblz4-tool rsyslog nftables
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sogo-activesync
E: Unable to locate package sope4.9-gdl1-mysql
E: Couldn't find any package by glob 'sope4.9-gdl1-mysql'
E: Couldn't find any package by regex 'sope4.9-gdl1-mysql'
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/

**Comment by iredmail** [comment]
Please install the gnupg package first, then run the iRedMail installer again. 

Will fix it shortly. Thanks for the feedback. :)
