### ISSUE TITLE
iRedmail Configuration with Remote Open ldap

### ISSUE THREAD

**Issue by ChandanP1994** [iredmail/iRedMail#153]
Information :
Ubuntu 20.04
iRedmail Version : 1.5.1 OPENLDAP edition (Free).
Open ldap.
================================================

I have installed two ubuntu servers, one for iRedmail setup with ldap backend and second for Open ldap configuration.

I am trying to setup remote LDAP server and point the iRedmail server to it. 
I have done a ton of web searches related to this topic.

So far nothing works and there is nothing current.

Given the changes to openLDAP has anyone been able to do this?

I have changed the remote ldap host IP and bind_dn and bind_pw (Remote ldap with those credentials I am able to login in ldap admin) .

"I didnt change the search_base url."

Postfix (LDAP): i change server_host = ip pf my LDAP server
    * Configuration files:
        - /etc/postfix/ldap/virtual_mailbox_domains.cf
        - /etc/postfix/ldap/relay_domains.cf
        - /etc/postfix/ldap/transport_maps_domain.cf
        - /etc/postfix/ldap/transport_maps_user.cf
        - /etc/postfix/ldap/virtual_mailbox_maps.cf
        - /etc/postfix/ldap/sender_login_maps.cf
        - /etc/postfix/ldap/virtual_alias_maps.cf
        - /etc/postfix/ldap/virtual_group_maps.cf
        - /etc/postfix/ldap/virtual_group_members_maps.cf
        - /etc/postfix/ldap/catchall_maps.cf
        - /etc/postfix/ldap/recipient_bcc_maps_domain.cf
        - /etc/postfix/ldap/recipient_bcc_maps_user.cf
        - /etc/postfix/ldap/sender_bcc_maps_domain.cf
        - /etc/postfix/ldap/sender_bcc_maps_user.cf

Dovecot:
    * Configuration files:
       
       - /etc/dovecot/dovecot-ldap.conf 

Copied required file in remote ldap server - location: /etc/ldap/schema
* amavis.schema 
* iredmail.schema
* ldap_init.ldif

All required ports are open.

I don't know what I am missing, can you please some one help me.
I am waiting for the positive response.

Thank you.

**Comment by iredmail** [comment]
> So far nothing works

Any error log or messages?

**Comment by ChandanP1994** [comment]
Thank you for replay. 

Which error log should I share here.
Can you please share the log name so I will copy and paste the logs here.

Still iRedmail server is working with built in ldap server (iRedmail backend) .

But I want to use remote ldap.
