### ISSUE TITLE
How to permanently delete emails with IMAP library to free space?

### ISSUE THREAD

**Issue by bluepuma77** [iredmail/iRedMail#154]
I am running iRedMail Dockerized and want to permanently delete sent emails via IMAP library to free storage space.

I use Python [imaplib](https://docs.python.org/3/library/imaplib.html) `mail.uid('STORE', uid, '+FLAGS', '\\Deleted')` to flag emails in iRedMail as deleted. The emails vanish from the folder in RoundCube. The emails are also removed from the according `vmail` folder (the folder gets smaller).

But the deleted emails are "secretly" moved to the `vmail Maildir/.Trash/tmp` folder (the folder gets larger). They do **not** show up in RoundCube `Trash`, they do **not** get picked up by `mail.expunge()` and they do **not** get removed by `doveadm expunge -u user@mailbox mailbox Trash all`. (`doveadm expunge` did delete few emails that where in Trash before, they don't show up in RoundCube anymore.)

Why is that? Is that a configuration/Dovecot/IMAP library problem? How can I permanently delete emails to free space?

iRedMail version: `2021091301 (mariadb backend, dockerized eidtion: https://www.iredmail.org/)`
```
# dovecot -n | head -2
# 2.3.7.2 (3c910f64b): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.5.7.2 ()
```

**Comment by bluepuma77** [comment]
Can I just delete the files within `Maildir/.Trash/tmp`? Or are there references in the database to be taken care of?

**Comment by iredmail** [comment]
> I use Python [imaplib](https://docs.python.org/3/library/imaplib.html) `mail.uid('STORE', uid, '+FLAGS', '\\Deleted')` to flag emails in iRedMail as deleted.

This is flagged, not deleted.
