### ISSUE TITLE
Send an email alert to postmaster@ when user exceeeds its sent mail limit

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#155]
Is it possible to configure iredmail to send an alert for postmaster@ when users exceed theirs sent mail limit?

This is important:
Imagine situation when some user get an virus.
The virus is sending spam messages to other servers.
Whole domain can get to RBL's even if the limit is not so high but the spam is sending for few days.
Fast reaction for that is the main thing.

REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  4.9
- Deployed with iRedMail Easy or the downloadable installer? installer
- Linux/BSD distribution name and version:  debian 10
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): pgsql
- Web server (Apache or Nginx): apache
- Manage mail accounts with iRedAdmin-Pro? yes
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

**Comment by iredmail** [comment]
iRedAPD offers this feature, you just need to make sure it's configured to use a valid smtp user to send email:

This is the default settings in `/opt/iredapd/libs/default_settings.py`, you should copy the variables to `/opt/iredapd/settings.py` and set a proper value, then restart iredapd service:

```
# Recipients of notification email
NOTIFICATION_RECIPIENTS = ['root']

# SMTP server address, port, username, password used to send notification mail.
NOTIFICATION_SMTP_SERVER = 'localhost'
NOTIFICATION_SMTP_PORT = 587
NOTIFICATION_SMTP_STARTTLS = True
NOTIFICATION_SMTP_USER = 'no-reply@localhost.localdomain'
NOTIFICATION_SMTP_PASSWORD = ''
NOTIFICATION_SMTP_DEBUG_LEVEL = 0

# The short description or full name of this smtp user. e.g. 'No Reply'
NOTIFICATION_SENDER_NAME = 'No Reply'
```

**Comment by iredmail** [comment]
Note: please upgrade iRedAPD to the latest release to make sure you have this feature.
