### ISSUE TITLE
admin_iredmail user should not be deleted after an install with a remote MySQL server

### ISSUE THREAD

**Issue by dgervalle** [iredmail/iRedMail#159]
Opposed to what is written at the end of the "[Install iRedMail with a remote MySQL server](https://docs.iredmail.org/install.iredmail.with.remote.mysql.server.html)" installation guides, the database user admin_iredmail is still used after the initial setup. So, the user might be reduced to more limited access to the created databases, but it can't be simply deleted as suggested by the guide.

Not only the user is used by some backup scripts in /var/vmail/backup, it is also the definer of views that allows sharing users between the different tools, while separating the used databases.

**Comment by iredmail** [comment]
Dear @dgervalle 

Thank you very much for the feedback. Document has been updated. :)
