### ISSUE TITLE
Error in SOGo activesync no update email

### ISSUE THREAD

**Issue by neogenius** [iredmail/iRedMail#161]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.5.1 MARIADB edition.
- Deployed with iRedMail Easy or the downloadable installer? Downloadable installer
- Linux/BSD distribution name and version: Ubuntu 20.04.4 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL - MariaDB
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? NO
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Feb 24 09:25:21 sogod [1237]: mx3.domain.com "OPTIONS /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 200 0/0 0.004 - - 0 - 13
Feb 24 09:25:40 sogod [1237]: mx3.domain.com "OPTIONS /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 200 0/0 0.001 - - 0 - 13
Feb 24 09:25:40 sogod [1237]: [WARN] <0x0x557649981f50[SOGoWebDAVAclManager]> entry '{DAV:}write' already exists in DAV permissions table
Feb 24 09:25:40 sogod [1237]: [WARN] <0x0x557649981f50[SOGoWebDAVAclManager]> entry '{DAV:}write-properties' already exists in DAV permissions table
Feb 24 09:25:40 sogod [1237]: [WARN] <0x0x557649981f50[SOGoWebDAVAclManager]> entry '{DAV:}write-content' already exists in DAV permissions table
Feb 24 09:25:41 sogod [1237]: <0x0x5576498c0cf0[NGImap4Client]> TLS started successfully.
Feb 24 09:25:41 sogod [1237]: [ERROR] <0x0x557649a4c130[NSDataMalloc]> xml2wbxmlFromContent: failed: Parsing of XML Document Failed

Feb 24 09:25:41 sogod [1237]: mx3.domain.com "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=FolderSync&User=user@domain&DeviceId=A0BF00F343454E119004FDAAECDE5967&DeviceType=WindowsOutlook15 HTTP/1.0" 200 0/13 0.771 - - 980K - 15
Feb 24 09:25:43 sogod [1237]: [ERROR] <0x0x5576499fe7d0[NSDataMalloc]> xml2wbxmlFromContent: failed: Parsing of XML Document Failed

Feb 24 09:25:43 sogod [1237]: mx3.domain.com "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=FolderSync&User=user@domain&DeviceId=A0BF00F343454E119004FDAAECDE5967&DeviceType=WindowsOutlook15 HTTP/1.0" 200 0/13 1.711 - - 0 - 15
Feb 24 09:25:50 sogod [1237]: [ERROR] <0x0x557649a46870[NSDataMalloc]> xml2wbxmlFromContent: failed: Parsing of XML Document Failed

Feb 24 09:25:50 sogod [1237]: mx3.domain.com "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=FolderSync&User=user@domain&DeviceId=A0BF00F343454E119004FDAAECDE5967&DeviceType=WindowsOutlook15 HTTP/1.0" 200 0/13 0.317 - - 0 - 15
Feb 24 09:25:50 sogod [1237]: [ERROR] <0x0x557649a06430[NSDataMalloc]> xml2wbxmlFromContent: failed: Parsing of XML Document Failed

I had this problem after running the update 2 days ago.

I installed everything new from scratch but the result is still the same.

Thank you for your support.

**Comment by iredmail** [comment]
FYI: https://www.sogo.nu/bugs/view.php?id=5486
