### ISSUE TITLE
SOGo url details

### ISSUE THREAD

**Issue by soumiasari7** [iredmail/iRedMail#163]
Hi there,

Actually im using SOGo as default Webmail to my iRedMail server.
My issue is when users login.  **The url** shows all details **username, mailboxes, ..**  so is there anyway to hide all these informations and just keep the domain name.

thank you.

**Comment by iredmail** [comment]
I don't know SOGo offers different url scheme, so i suggest asking in SOGo mailing list or its bug tracker:
https://www.sogo.nu/support.html
