### ISSUE TITLE
Sogo V5 Unhandled error response

### ISSUE THREAD

**Issue by whitten2002** [iredmail/iRedMail#164]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.5.1
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: Ubuntu 18
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? YES
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

After installing updates + Sogo Updates i'm getting Unhandled error response when i try login to webmail via Sogo

**Comment by whitten2002** [comment]
Just tried to login with the Dev tool on. here is the results
  POST https://****HIDDEN URL****/SOGo/connect 502    angular.js:13692        

Line13692       xhr.send(isUndefined(post) ? null : post);

**Comment by whitten2002** [comment]
Solved by adding the following config to /etc/nginx/sites-avalabe/ 00-default-ssl.conf

    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

**Comment by whitten2002** [comment]
Hi, I have updated iredmail to the latest, and after about 5min SOGo does not respond. i have to close the browser and clear cache to log back in.  Any one can help please?

**Comment by iredmail** [comment]
The nginx change is mentioned in iRedMail upgrade tutorial for iRedMail-1.5.2. https://docs.iredmail.org/iredmail.releases.html 

the issue in your last post was unknown. Any error in SOGo log file?

**Comment by whitten2002** [comment]
What about this error?

<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ole="presentation"><tbody><tr><td class="0" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
eft:0" class="mceSpacing-24" id="mceColumnContainer" align="center" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
eft:0" class="mceSpacing-24" id="mceColumnContainer" align="center" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
px;padding-left:48px" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ole="presentation"><tbody><tr><td class="0" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
px;padding-left:48px" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ole="presentation"><tbody><tr><td class="0" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
px;padding-left:48px" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ght:0;padding-left:0" class="mceSpacing-24" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
ole="presentation"><tbody><tr><td class="0" id="mceColumnContainer" valign="top"
                                                                               ^
<data>:24: element td: validity error : ID mceColumnContainer already defined
eft:0" class="mceSpacing-24" id="mceColumnContainer" align="center" valign="top"

**Comment by whitten2002** [comment]
Also this 

Mar 20 14:22:02 sogod [5258]: [WARN] <0x0x55a3b2956e10[SOGoWebDAVAclManager]> entry '{DAV:}write' already exists in DAV permissions table
Mar 20 14:22:02 sogod [5258]: [WARN] <0x0x55a3b2956e10[SOGoWebDAVAclManager]> entry '{DAV:}write-properties' already exists in DAV permissions table
Mar 20 14:22:02 sogod [5258]: [WARN] <0x0x55a3b2956e10[SOGoWebDAVAclManager]> entry '{DAV:}write-content' already exists in DAV permissions table

**Comment by whitten2002** [comment]
Also i have notice this, Does ths cause issue as SOGo works for 5min/ 300sec and then i get a blank white page.

: <0x0x5588d7c96fb0[SOGoCache]> Cache cleanup interval set every 300.000000 seconds

**Comment by iredmail** [comment]
@whitten2002 please try to upgrade SOGo packages and reproduce the issue.

**Comment by whitten2002** [comment]
@iredmail I have upgraded SOGo and still same issue

**Comment by iredmail** [comment]
Try this fix: https://github.com/iredmail/iRedMail/issues/171#issuecomment-1081069665
