### ISSUE TITLE
install 1.5.2iredmail  ‘service iredapd restart’ Unable to start

### ISSUE THREAD

**Issue by ningtt** [iredmail/iRedMail#165]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.5.2
- Deployed with iRedMail Easy or the downloadable installer? no
- Linux/BSD distribution name and version: debian11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx):Nginx
- Manage mail accounts with iRedAdmin-Pro?no
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
nginx error log
![Snipaste_2022-03-16_16-50-23](https://user-images.githubusercontent.com/61641974/158552128-2281a82d-0499-4063-9162-fd4ac2ac521f.png)

**Comment by iredmail** [comment]
Does restarting php-fpm service fix the issue? Any error in /var/log/syslog?

**Comment by iredmail** [comment]
Any update? If no update I will close this issue soon.
