### ISSUE TITLE
Please Update Sogo

### ISSUE THREAD

**Issue by SniffRx** [iredmail/iRedMail#169]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.5.2
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: Debian 11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL
- Web server (Apache or Nginx): NginX
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Please update sogo rep (LAST VERSION [sogo-activesync_5.5.1.20220317-1_amd64.deb](https://packages.inverse.ca/SOGo/nightly/5/debian/pool/bullseye/s/sogo/sogo-activesync_5.5.1.20220317-1_amd64.deb))
https://packages.inverse.ca/SOGo/nightly/5/debian/pool/bullseye/s/sogo/
I get error 404 Not found package
`E: Failed to fetch https://packages.inverse.ca/SOGo/nightly/5/debian/pool/bullseye/s/sogo/sogo_5.5.1.20220316-                        1_amd64.deb  404  Not Found [IP: 96.16.49.221 443]
E: Failed to fetch https://packages.inverse.ca/SOGo/nightly/5/debian/pool/bullseye/s/sogo/sogo-activesync_5.5.                        1.20220316-1_amd64.deb  404  Not Found [IP: 96.16.49.221 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 166 MB in 5s (33.8 MB/s)
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/`

**Comment by iredmail** [comment]
SOGo repo is not maintained by iRedMail team, please help report to upstream: https://www.sogo.nu/support.html

**Comment by SniffRx** [comment]
@iredmail Thanks.
Decision: `apt clean && apt-get update && apt-get upgrade`
