### ISSUE TITLE
Autoconfiguration for email clients

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#170]
Always after iredmail installing I do the "autoconfiguration" for email clients.
Is there a purpose why this is not configured by default as a vhost.main_email_domain.pl?

**Comment by interduo** [comment]
This is very simple and useful:
https://wiki.mozilla.org/Thunderbird:Autoconfiguration

**Comment by iredmail** [comment]
Would you like to try automx2?
https://rseichter.github.io/automx2/

**Comment by interduo** [comment]
I will be bad tester because for us autoconfig in xml is all we need :)

**Comment by interduo** [comment]
All of us need needs to automatic create of vhost (autoconfig.domain.pl) and file in it (/mail/config-v1.1.xml).

and puting there a example file with:
```
<?xml version="1.0" encoding="UTF-8"?>

<clientConfig version="1.1">
  <emailProvider id="domain.pl">
    <domain>domain.pl</domain>
    <displayName>Poczta DOMAIN</displayName>
    <displayShortName>DOMAIN</displayShortName>
    <incomingServer type="imap">
      <hostname>poczta.domain.pl</hostname>
      <port>993</port>
      <socketType>SSL</socketType>
      <authentication>password-cleartext</authentication>
      <username>%EMAILADDRESS%</username>
    </incomingServer>
    <outgoingServer type="smtp">
      <hostname>poczta.domain.pl</hostname>
      <port>587</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>%EMAILADDRESS%</username>
    </outgoingServer>
    <outgoingServer type="smtp">
      <hostname>poczta.domain.pl</hostname>
      <port>587</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>%EMAILADDRESS%</username>
    </outgoingServer>
    <documentation url="https://poczta.domain.pl/support.html">
      <descr lang="en">Support Page</descr>
    </documentation>
  </emailProvider>
</clientConfig>
```

This is KISS (keep it simple stupid) & enough :)

**Comment by interduo** [comment]
There is also: https://github.com/Monogramm/autodiscover-email-settings

**Comment by interduo** [comment]
> Would you like to try automx2? https://rseichter.github.io/automx2/

Tried that and it's also OK

**Comment by interduo** [comment]
How is auto config works in iredmail? (You closed this issue as completed)
