### ISSUE TITLE
SOGo White blank screen after 5 min

### ISSUE THREAD

**Issue by whitten2002** [iredmail/iRedMail#171]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  1.5.2
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version:  Ubunty 18.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? YES
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
![sogoerror](https://user-images.githubusercontent.com/37750333/159343436-daf5dc86-04a7-4ca9-bb63-f160e2061167.png)

Getting this error after SOGo session pass 5min. please help

I have to close my browser and reopen the SOGo URL to get back to using SOGo

**Comment by whitten2002** [comment]
Anyone else having this issue?

**Comment by iredmail** [comment]
Any relevant error in SOGo log file /var/log/sogo/sogo.log?

**Comment by whitten2002** [comment]
> Any relevant error in SOGo log file /var/log/sogo/sogo.log?

Nothing obvious i can see. Is there something in settings that disconnects the session after 300 sec?

**Comment by iredmail** [comment]
Not sure whether it's relevant: SOGo uses memcached as cache service, and the interval is 5 minutes.

Try to disable memcached integration in /etc/sogo/sogo.conf (Search "Memcached" and comment out that line), then restart sogo service and try to reproduce the issue.

**Comment by whitten2002** [comment]
> Not sure whether it's relevant: SOGo uses memcached as cache service, and the interval is 5 minutes.
> 
> Try to disable memcached integration in /etc/sogo/sogo.conf (Search "Memcached" and comment out that line), then restart sogo service and try to reproduce the issue.

Still same issue with Memcached comment out

    // Memcached
    //SOGoMemcachedHost = 127.0.0.1;

**Comment by iredmail** [comment]
Yes please run it to fix the issue. 

Btw, you said no error in SOGo log file, which mislead me. :)
