### ISSUE TITLE
Email disable

### ISSUE THREAD

**Issue by DIVISIONSolar** [iredmail/iRedMail#172]
When ever I suspend an email it breaks the entire database which results in me needing to reset the server

**Comment by iredmail** [comment]
How did you "suspend an email"?

**Comment by DIVISIONSolar** [comment]
I clicked the disable button

**Comment by iredmail** [comment]
No idea at all. We didn't receive similar report before, i guess there's some other change happened right before or after you clicked the disable button. But if you cannot reproduce it, then it's hard to tell what the real problem is.
