### ISSUE TITLE
nginx logging should use real_ip module

### ISSUE THREAD

**Issue by rhyven** [iredmail/iRedMail#177]
Hi team!

I tried to do this as a pull request, but couldn't figure out how the config files are modified by the downloadable installer.  :)

The nginx config with iRedMail (up to version 1.5.2) doesn't enable the ngx_http_realip_module, so the reverse proxy IP address is logged instead of the real requester IP.

I fixed this by adding the following lines to the http block in nginx.conf:

```
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  192.168.0.0/16;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
```
_(Note this needs another line or so for IPv6; this is a tiny site with IPv6 disabled, so I couldn't test)_

Before:
`[reverse proxy IP] - - [01/May/2022:10:18:41 +1200] "GET / HTTP/1.1" 200 78 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"`

After:
`[my real IP] - - [01/May/2022:10:22:43 +1200] "GET /mail/ HTTP/1.1" 200 2362 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"`

**Comment by iredmail** [comment]
Thanks for the feedback.

Default iRedMail configuration is designed for running without a reverse proxy sits in front of iRedMail, so we don't have such Nginx config. I'm afraid that we won't add this in default configuration.

**Comment by rhyven** [comment]
Hey @iredmail, thanks for the quick reply! This setting isn't **only** for reverse proxies; it provides correct logging for sites behind a CDN or a WAF. (additionally, it doesn't break configurations which _are_ directly exposed to the internet)

I think it's worth reconsidering - this would improve the logging quality of iRedMail overall, even though iRedMail isn't built with a reverse proxy in mind.
