### ISSUE TITLE
how to update roundcube from iredmail when some changes are applied to it

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#178]
We got a situation when there is a iredmail with roundcube with:
- some plugins,
- some configuration changes,
- some HTML pages inside vhost.

Installer gets source release package instead using git by default - so we can't just `git pull`.

Maybe using `git clone` and stable branch like `release-1.4/release-1.5` would be better that using release tarbal?

I see also pros for You - less work when releasing new version of iredmail.
(You could only check is there any new stable branch instead of checking release)

**Comment by iredmail** [comment]
We don't support such customizations, I'm afraid that you have to handle this yourself. :(

**Comment by iredmail** [comment]
iRedMail recommends upgrading Roundcube by running its "bin/installto.sh" script, but it may overrides your customization made in php files (but it handles config files "config/*" well).
