### ISSUE TITLE
Docker: No email with settings in postmaster inbox on the first launch

### ISSUE THREAD

**Issue by TitanFighter** [iredmail/iRedMail#18]
Hi @iredmail 
As I understand this email either not generated or not added to Inbox. Do you need anything additionally from me to fix it?

**Comment by iredmail** [comment]
Will fix this later.

Do you think it's necessary to sent this file to postmaster's box each time the container runs?

**Comment by TitanFighter** [comment]
Yeah, quite helpful, especially links (I never remember them, because use rarely) and dkim part (no need to dig into docker :)

**Comment by tweenietomatoes** [comment]
> Yeah, quite helpful, especially links (I never remember them, because use rarely) and dkim part (no need to dig into docker :)

well caddy community here

**Comment by iredmail** [comment]
Update: File `iRedMail.tips` will be sent to `postmaster` each time you launch the container.
Image has been rebuilt with this change:
https://hub.docker.com/r/iredmail/mariadb
