### ISSUE TITLE
Terminal installer: A space in the password truncates it

### ISSUE THREAD

**Issue by SamSirry** [iredmail/iRedMail#182]
- iRedMail version (check /etc/iredmail-release): 1.6.0 MARIADB edition.
- Deployed with iRedMail Easy or the downloadable installer? Downloadable
- Linux/BSD distribution name and version: Debian 11
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

When using the downloadable installer in a terminal (SSH), the postmaster password is specified with spaces in the string.
Attempting to log in to iRedAdmin with the same full password fails, but logging in with the part of the password before the first space character is successful.

This is tested with the admin panel iRedAdmin. Probably the password for MariaDB also suffers the same issue.

**Comment by SamSirry** [comment]
Note: In the report shown at the end of the installation, the full password with spaces is displayed correctly.

**Comment by iredmail** [comment]
As mentioned in the installation wizard, do not use special chars in password, e.g. #, $. Space should be considered as one of the special chars. :(

**Comment by Anzulo1984** [comment]
not a bug, so this is kind of solved
