### ISSUE TITLE
Can't install Ubuntu 18.04

### ISSUE THREAD

**Issue by CraftedCat** [iredmail/iRedMail#187]
Hi!

root@vm63319 ~ # cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

When install :
Release version of the operating system on this server is unsupported by
iRedMail, please access below link to get the latest iRedMail and a list
of supported Linux/BSD distributions and release versions.

Supported distr:
Ubuntu 22.04 (Recommend), 20.04, 18.04

**Comment by iredmail** [comment]
- For NEW iRedMail installation, please use Ubuntu 22.04 or 20.04.
- Note: SOGo is not available on 22.04 yet since SOGo team doesn't offer binary packages for 22.04.
