### ISSUE TITLE
Deprecated key on the Sogo repository which leads to failing install script

### ISSUE THREAD

**Issue by Ard3ny** [iredmail/iRedMail#188]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.0
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version:  Debian 11.6
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  mysql
- Web server (Apache or Nginx): nginx
- Manage mail accounts with iRedAdmin-Pro? no

I've tried downloading and installing iRedMail on Debian according to this guide (https://docs.iredmail.org/install.iredmail.on.debian.ubuntu.html) few days ago and it worked perfectly, but I've tried it today to do some testing on fresh debian install and it failed. 

It looks like the key for the sogo repository (https://packages.sogo.nu/nightly/5/debian bullseye) got deprecated.

![image](https://user-images.githubusercontent.com/69809418/184157891-6cae71c4-7d06-4cef-b2ca-69256021f008.png)

![image](https://user-images.githubusercontent.com/69809418/184158033-863c6b8e-6765-4bd2-941a-924153301d3c.png)
![image](https://user-images.githubusercontent.com/69809418/184158122-45245a09-cc86-4c1c-8a46-f5a8013e9df9.png)

**Comment by ansibleguy** [comment]
Found the same problem while testing. Seems to be an issue of the SOGo project.
It seems they have a site for bugs/issues: https://bugs.sogo.nu/view_all_bug_page.php

**Comment by iredmail** [comment]
SOGo was acquired by other company months ago, and they're shifting ownership these days, new owner company may regenerated the apt/yum key, i will check tomorrow.

**Comment by Ard3ny** [comment]
I checked just a minute ago and it's still not working. I guess they just need a little time.

**Comment by iredmail** [comment]
Quote from SOGo mailing list:

> The nightly binary packages are now accessible from https://packages.sogo.nu/ and signed with a new GPG key that you will need to import. You can use the online installation helper (https://sogo.nu/download.html#helper) or consult the appropriate FAQ entry:

> https://www.sogo.nu/support/faq/how-to-install-a-nightly-version-through-yum.html
> https://www.sogo.nu/support/faq/how-to-install-nightly-sogo-versions-on-debian.html
> https://www.sogo.nu/support/faq/how-to-install-nightly-sogo-versions-on-ubuntu.html

As you can see, the yum/apt repo URLs have been changed (packages.inverse.ca -> packages.sogo.nu), and new GPG key must be imported.

**Comment by iredmail** [comment]
This has been fixed in latest iRedMail 1.6.1 (released today, Aug 22).
