### ISSUE TITLE
docker deployment - roundcube - failed to add recipient

### ISSUE THREAD

**Issue by Umlatt** [iredmail/iRedMail#191]
Good day

I really like iRedmail so far.

I am running into an issue which is stopping me from progressing (it may be my own misunderstanding, but have not found any information to correct it yet).

# Problem

Using the docker deployment (stable edition), I am receiving an error when attempting to send emails.

```
SMTP Error (451): Failed to add recipient "target_email_address" (4.3.0 <mail@domain>:  Temporary lookup failure).
```

One variation from the source is that I needed to create new SSL certs as there was a certificate error when connecting to the web portals (changed the files according to the [official docs](https://docs.iredmail.org/use.a.bought.ssl.certificate.html#replace-cert-files)

It appears that the docker container is deployed in the same fashion as iRedMail Easy platform.

![image](https://user-images.githubusercontent.com/44724035/189475270-6ca30998-e9d3-4dba-a5e3-2afdf60ea557.png)

Hence I moved my corrected certs into the paths identified in the warnings.

---

# REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
`2021091301 (mariadb backend, dockerized eidtion: https://www.iredmail.org/)`
- Deployed with iRedMail Easy or the downloadable installer?
[docker deployment](https://hub.docker.com/r/iredmail/mariadb)
- Linux/BSD distribution name and version: 
`Ubuntu 20.04.3 LTS`
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
`MySQL`
- Web server (Apache or Nginx):
`Nginx`
- Manage mail accounts with iRedAdmin-Pro?
`No`
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

# Logs & Error messages

`/var/log/mail.log`

```
Sep  9 19:35:08 mail postfix/pickup[888]: 4MPR643ZBnz5vvc: uid=0 from=<root@mail.domain.com>
Sep  9 19:35:08 mail postfix/cleanup[889]: warning: proxy:mysql:/etc/postfix/mysql/sender_bcc_maps_user.cf lookup error for "root@mail.domain.com"
Sep  9 19:35:08 mail postfix/cleanup[889]: warning: 4MPR643ZBnz5vvc: sender_bcc_maps map lookup problem -- message not accepted, try again later
Sep  9 19:35:08 mail postfix/pickup[888]: warning: maildrop/4MPQkP3v1Lz5vlB: error writing 4MPR643ZBnz5vvc: queue file write error
```
After some research, using the credentials found in:
`/etc/postfix/mysql/domain_alias_maps.cf`
```
#
# This file is managed by iRedMail Team <support@iredmail.org> with Ansible,
# please do __NOT__ modify it manually.
#

hosts       = 127.0.0.1:3306
user        = vmail
password    = 5q9bd--------------wy1xCetf
dbname      = vmail
query       = SELECT forwardings.forwarding FROM forwardings,alias_domain,domain WHERE alias_domain.alias_domain='%d' AND forwardings.address=CONCAT('%u', '@', alias_domain.target_domain) AND alias_domain.target_domain=domain.domain AND forwardings.active=1 AND alias_domain.active=1 AND domain.backupmx=0
```
The following access denied error occurs when attempting to connect to the db as the `vmail` user
```
root@mail:/# mysql -u vmail -p
Enter password:
*Password is supplied as above (i.e. 5q9bd--------------wy1xCetf)
ERROR 1045 (28000): Access denied for user 'vmail'@'localhost' (using password: YES)
```

**Comment by iredmail** [comment]
Did you try to use fixed sql passwords instead of random passwords?
