### ISSUE TITLE
Deploying on CapRover corrupts entire VM (AWS Lightsail)

### ISSUE THREAD

**Issue by MichaelNZ85** [iredmail/iRedMail#193]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): latest
- Deployed with iRedMail Easy or the downloadable installer? CapRover
- Linux/BSD distribution name and version: Ubuntu 18.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): N/A
- Web server (Apache or Nginx): Don't know (CapRover handles all that)
- Manage mail accounts with iRedAdmin-Pro? No

Installing iRedMail through [CapRover](https://caprover.com) as a one-click app and then attempting to access it corrupts the entire AWS Lightsail instance that CapRover is installed on. Attempting to access the CapRover web portal times out with the error 'Something went wrong'. I cannot SSH into my Lightsail instance to check the logs, and had to end up deleting it and creating a new one.

**System setup**

**Host:** AWS Lightsail
**OS:** Ubuntu 18.04
**Storage:** 40GB block storage disk
**Memory:** 1GB
**CPU:** 1 vCPU

**Comment by iredmail** [comment]
Dear @MichaelNZ85 

-iRedMail requires a fresh / clean OS for initial installation. 
-At least 4GB memory is required for low traffic mail server.
