### ISSUE TITLE
RAM check during installation/update

### ISSUE THREAD

**Issue by Anzulo1984** [iredmail/iRedMail#194]
Related to installer and update scripts:

The installation should check for available RAM and refuse to continue, if not at least 4GB of system RAM is available to avoid occouring problems with amavis crashing and rendering the whole mailserver inoperable

Code Snippet:

TOTAL_MEM=$(free -g | grep Mem: | awk '{print $2}')

should be very easy to implement in the installer

**Comment by jchimene** [comment]
No. I run this setup on a 2GB system just fine. I don't care if amavis crashes. If you really want this, it should leave behind configuration or warning.

**Comment by iredmail** [comment]
No plan to add such checks before installation. Sorry.
