### ISSUE TITLE
Package 'netcat' has no installation candidate

### ISSUE THREAD

**Issue by omolojakazeem** [iredmail/iRedMail#195]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.2
- Deployed with iRedMail Easy or the downloadable installer? 
- Linux/BSD distribution name and version: Ubuntu 22.10
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL
- Web server (Apache or Nginx): NGINX

Got this error during installation:
Package netcat is a virtual package provided by:
  netcat-traditional 1.10-47
  netcat-openbsd 1.218-5ubuntu1

E: Package 'netcat' has no installation candidate
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/

**Comment by iredmail** [comment]
iRedMail doesn't support Ubuntu 22.10, please use 22.04 LTS instead.
