### ISSUE TITLE
Can't build on FreeBSD - lsof requires kernel sources

### ISSUE THREAD

**Issue by michaelhovedk** [iredmail/iRedMail#197]
===>  lsof-4.96.4,8 requires kernel sources.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/sysutils/lsof
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/py-Jinja2
<< ERROR >> Failed in downloading package(s), please fix it manually and then relaunch iRedMail installer.

**Comment by Mitik974** [comment]
fetch ftp://ftp.freebsd.org/pub/`uname -s`/releases/`uname -m`/`uname -r | cut -d'-' -f1,2`/src.txz
tar -C / -xvzf src.txz

**Comment by iredmail** [comment]
More like a ports tree issue. 
If you're building a new iRedMail server, consider switching to Linux instead.
