### ISSUE TITLE
Is there a way, to track outgoing emails, whether they entered the inbox and whether they were read?

### ISSUE THREAD

**Issue by CatDogZ** [iredmail/iRedMail#198]
Is there a way, to track outgoing emails, whether they entered the inbox and whether they were read?

**Comment by iredmail** [comment]
Yes and no.

- When email left your server, it's out of your control. You can know whether recipient server receives the email, but you don't know whether it discards the message, or delivers to some mail folder.
- Usually people insert a linked image (e.g. `<img src="http://your-server/some-uri" />`) in mail body to track whether email was opened by recipient, but nowadays most MUAs disable loading remote images for security concerns, so it doesn't work all the time.
