### ISSUE TITLE
amavis INVALID and FAILED warning

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#2]
Hello
I just install fresh iRedMail 1.0 stable on Debian 10.
After reboot server i saw information in mail.log:

Dec 21 19:14:41 webmail amavis[2118]: (!)policy protocol: INVALID AM.PDP ATTRIBUTE LINE: POST / HTTP/1.1\r\n
Dec 21 19:14:41 webmail amavis[2118]: (!!)policy_server FAILED: Missing 'request' field at (eval 105) line 197, <GEN30> line 7.
Dec 21 19:14:42 webmail amavis[2118]: (!)policy protocol: INVALID AM.PDP ATTRIBUTE LINE: [{"version": "1.1", "params": [], "id": 0, "method": "getmempoolinfo"}, {"version": "1.1", "params": [], "id": 1, "method": "getnetworkinfo"}, {"version": "1.1", "params": [], "id": 2, "method": "getblockchaininfo"}, {"version": "1.1", "params": [], "id": 3, "method": "getmemoryinfo"}, {"version": "1.1", "params": [], "id": 4, "method": "gettxoutsetinfo"}]

Best Regards
TaKeN

**Comment by iredmail** [comment]
Seems “bug” of amavisd and not an iRedMail configuration issue.

**Comment by iredmail** [comment]
> INVALID AM.PDP ATTRIBUTE LINE: POST / HTTP/1.1\r\n

Seems some application sent HTTP request to this port. Do you run netdata on this server?

**Comment by takenek** [comment]
Hello,
Yes i got it netdata installed on this server.

Best Regards
TaKeN

**Comment by iredmail** [comment]
Could you help test this case:

- disable netdata service with command: systemctl disable netdata
- reboot server
- check log to see whether the error log appears again.

**Comment by takenek** [comment]
root@webmail:~# systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/netdata.service.d
           └─limits.conf
   Active: inactive (dead)

gru 22 08:43:24 webmail systemd[1]: Starting Real time performance monitoring...
gru 22 08:43:24 webmail systemd[1]: Started Real time performance monitoring.
gru 22 08:43:24 webmail [1897]: SIGNAL: Not enabling reaper
gru 22 08:43:24 webmail netdata[1897]: 2019-12-22 08:43:24: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
gru 22 08:44:02 webmail systemd[1]: netdata.service: Current command vanished from the unit file, execution of the command list won't be resumed.
gru 22 08:44:15 webmail systemd[1]: Stopping Real time performance monitoring...
gru 22 08:44:15 webmail systemd[1]: netdata.service: Succeeded.
gru 22 08:44:15 webmail systemd[1]: Stopped Real time performance monitoring.

Dec 22 08:45:09 webmail postfix/postfix-script[1713]: warning: symlink leaves directory: /etc/postfix/./makedefs.out
Dec 22 08:45:09 webmail postfix/postfix-script[1884]: starting the Postfix mail system
Dec 22 08:45:09 webmail postfix/master[1886]: daemon started -- version 3.4.7, configuration /etc/postfix

No errors.
You got right , netdata sending http request to amavis....

After 
root@webmail:~# systemctl start netdata
get again:
Dec 22 08:46:14 webmail amavis[1892]: (!)policy protocol: INVALID AM.PDP ATTRIBUTE LINE: POST / HTTP/1.1\r\n
Dec 22 08:46:14 webmail amavis[1892]: (!!)policy_server FAILED: Missing 'request' field at (eval 105) line 197, <GEN31> line 7.
Dec 22 08:46:15 webmail amavis[1892]: (!)policy protocol: INVALID AM.PDP ATTRIBUTE LINE: [{"version": "1.1", "params": [], "id": 0, "method": "getmempoolinfo"}, {"version": "1.1", "params": [], "id": 1, "method": "getnetworkinfo"}, {"version": "1.1", "params": [], "id": 2, "method": "getblockchaininfo"}, {"version": "1.1", "params": [], "id": 3, "method": "getmemoryinfo"}, {"version": "1.1", "params": [], "id": 4, "method": "gettxoutsetinfo"}]

**Comment by iredmail** [comment]
Thanks for helping. I will check which netdata plugin checks port 9998 and disable it.

**Comment by iredmail** [comment]
How to fix it manually:

- In file `/opt/netdata/etc/netdata/python.d.conf`, append one line:

```energid: no```

- In file `/opt/netdata/etc/netdata/go.d.conf`, append one line (WARNING: there're 2 whitespaces at the beginning of line):

```  energid: no```

Then restart netdata service.
