### ISSUE TITLE
Access denied for users stats and admin.

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#20]
Hello,
Again strange information in logs about MariaDB/MySQL.
iRedAdmin Version 1.1.0 - fresh install
OS: Debian 10

root@webmail:~# cat /var/log/mysql/error.log
2020-04-04 19:54:44 37 [Warning] Access denied for user 'stats'@'localhost' (using password: YES)
2020-04-04 19:54:44 38 [Warning] Access denied for user 'admin'@'localhost' (using password: YES)

Best Regards
TaKeN

**Comment by iredmail** [comment]
Are you running netdata? It may try to enable some netdata internal plugins and access the database with pre-defined SQL usernames. It's safe to ignore if it's in such case.

**Comment by takenek** [comment]
Yes, this is netdata, after install fresh version without netdata there is no errors in mysql logs about stats and admin users in MySQL.
