### ISSUE TITLE
Lasted version "Package verification failed."

### ISSUE THREAD

**Issue by saltinirmak** [iredmail/iRedMail#200]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6
- Deployed with iRedMail Easy or the downloadable installer?: downloadable 
- Linux/BSD distribution name and version: Ubuntu 20 arm based

[ INFO ] Validate downloaded source tarballs ...
misc/iRedAdmin-2.1.tar.gz: OK
misc/mlmmjadmin-3.1.6.tar.gz: OK
misc/iRedAPD-5.1.3.tar.gz: OK
sha256sum: misc/netdata-v1.37.1.gz.run: No such file or directory
misc/netdata-v1.37.1.gz.run: FAILED open or read
misc/roundcubemail-1.5.3-complete.tar.gz: OK
sha256sum: WARNING: 1 listed file could not be read
        [ FAILED ]
<< ERROR >> Package verification failed. Script exit ..

**Comment by iredmail** [comment]
Fixed. Please try again. Sorry about this trouble.

Seems you're running the latest development edition of iRedMail?

**Comment by saltinirmak** [comment]
Thanks for help. I did git clone Probably lasted version. I don't sure. Anyway my problem is solved. Thanks again
