### ISSUE TITLE
iredmail forwarding vs sieve rules

### ISSUE THREAD

**Issue by dev2021-ctrl** [iredmail/iRedMail#204]
I want to know if iredmail forwardings rules are executed before or after sieve rules.
Example
I added forwarding address for say  A user as mentioned  here https://docs.iredmail.org/sql.user.mail.forwarding.html
and add sieve rule , something like below

if not (header :contains "From" "XYZ")
{
    fileinto  "INBOX";
    stop;
    
}
So for if emails is sent to A user and does not have XYZ in from address , will it be forwarded as per the iredMail configuration or just moved to inbox as per the sieve rule.

Pls advise.
A bit urgent

**Comment by iredmail** [comment]
- Postfix expands mail alias and forwarding BEFORE sieve rules.
- Sieve rules are applied when Dovecot delivers email to mailbox.
