### ISSUE TITLE
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: connect from mail.xgpuc.com[127.0.0.1] Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: SSL_accept error from mail.xgpuc.com[127.0.0.1]: -1 Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: warning: TLS library problem: error:0A000126:SSL routines::unexpected eof while reading:../ssl/record/rec_layer_s3.c:308: Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: lost connection after CONNECT from mail.xgpuc.com[127.0.0.1] Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: disconnect from mail.xgpuc.com[127.0.0.1] commands=0/0

### ISSUE THREAD

**Issue by Xingz21** [iredmail/iRedMail#209]
你好，我想问下遇到了下面这个问题，怎么解决？
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: connect from mail.xgpuc.com[127.0.0.1]
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: SSL_accept error from mail.xgpuc.com[127.0.0.1]: -1
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: warning: TLS library problem: error:0A000126:SSL routines::unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: lost connection after CONNECT from mail.xgpuc.com[127.0.0.1]
Mar 15 09:57:00 mail postfix/smtps/smtpd[7282]: disconnect from mail.xgpuc.com[127.0.0.1] commands=0/0

**Comment by pablo-flinq** [comment]
update postfix to last version (3.7.4) solves this

**Comment by iredmail** [comment]
Please leave the issue tracker for bug report and use our forum for tech support: https://forum.iredmail.org/
