### ISSUE TITLE
Suggestion - add smtps to master.cf

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#21]
Hello
I saw postfix don`t listen on 465 port
Maybe add support for:
root@webmail:~# grep smtps /etc/services
submissions     465/tcp         ssmtp smtps urd # Submission over TLS [RFC8314]

add to master.cf:
smtps     inet  n       -      n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o content_filter=smtp-amavis:[127.0.0.1]:10026

Best Regards
TaKeN

**Comment by iredmail** [comment]
FYI: https://docs.iredmail.org/enable.smtps.html
