### ISSUE TITLE
unable to subscribe expunge folder

### ISSUE THREAD

**Issue by cheng3969** [iredmail/iRedMail#211]
Hi,
Ive set up dovecot lazy expunge plugin with below config, but subscribe to expunge folder button is greyed out in roundcube.
How can i show expunge folder?
Thank you.

Please check this issue:
[roundcube issue](https://github.com/roundcube/roundcubemail/issues/8981)

**Comment by Anzulo1984** [comment]
https://github.com/roundcube/roundcubemail/issues/8981

this is solved
