### ISSUE TITLE
Unable to save password modification error from Roundcube

### ISSUE THREAD

**Issue by zhoucd** [iredmail/iRedMail#212]
Unable to save password modification error from Roundcube，the error message is The new password cannot be saved

**Comment by iredmail** [comment]
In `/opt/www/roundcubemail/plugins/password/config.inc.php`, update `password_algorithm` to `ssha512`, also `password_algorithm_prefix` to `{SSHA512}`.

**Comment by zhoucd** [comment]
The problem has not been resolved，There is an error message in the log
![image](https://user-images.githubusercontent.com/7435219/234453857-13921517-6021-40ef-9830-c8bfb728f001.png)

**Comment by iredmail** [comment]
This is not related to the changes i mentioned. Did you change any other parameters?

**Comment by zhoucd** [comment]
This is my  config, My iRedMail version is 1.6.2，os is Ubuntu 22.04, DB selected pgsql，No changes to other configurations
![image](https://user-images.githubusercontent.com/7435219/234456154-00d7a977-0182-4913-9d90-9edbcbee0458.png)

**Comment by iredmail** [comment]
`password_algorithm_prefix` should be `{SSHA512}`. You missed `{}`.

**Comment by zhoucd** [comment]
Thanks，After adding {}, the problem was resolved！
