### ISSUE TITLE
用域名访问 一直301

### ISSUE THREAD

**Issue by HuiZzli** [iredmail/iRedMail#213]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  1.6.2
- Deployed with iRedMail Easy or the downloadable installer? downloadable
- Linux/BSD distribution name and version:  Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-71-generic x86_64)
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL 
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? 
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

部署完成，重启之后，用域名访问 一直301

**Comment by iredmail** [comment]
DNS 记录都正确吗？
参考：https://docs.iredmail.org/setup.dns.html
