### ISSUE TITLE
V-iRedMail-1.6.3    May 24 08:25:55 mail postfix/smtp[419850]: connect to aspmx.l.google.com

### ISSUE THREAD

**Issue by fenghualanglang** [iredmail/iRedMail#214]
Hello, currently you can send emails within the same domain, but you are unable to send emails to Gmail or 163.com. I suspect that there might be certain configuration issues causing the timeouts when sending emails to these domains.

nslookup alt2.aspmx.l.google.com
nslookup 163mx03.mxmail.netease.com. is ok 

May 24 09:42:34 mail postfix/anvil[572944]: statistics: max cache size 2 at May 24 09:37:47
May 24 09:42:44 mail postfix/smtp[584451]: connect to gmail-smtp-in.l.google.com[2607:f8b0:4023:c03::1b]:25: Connection timed out
May 24 09:42:45 mail postfix/smtp[584450]: connect to 163mx01.mxmail.netease.com[103.129.252.82]:25: Connection timed out
May 24 09:43:15 mail postfix/smtp[584451]: connect to alt1.gmail-smtp-in.l.google.com[64.233.171.27]:25: Connection timed out
May 24 09:43:15 mail postfix/smtp[584450]: connect to 163mx03.mxmail.netease.com[103.129.252.82]:25: Connection timed out
May 24 09:43:45 mail postfix/smtp[584451]: connect to alt1.gmail-smtp-in.l.google.com[2607:f8b0:4003:c15::1a]:25: Connection timed out
May 24 09:43:45 mail postfix/smtp[584450]: connect to 163mx00.mxmail.netease.com[220.181.12.180]:25: Connection timed out
May 24 09:43:45 mail postfix/smtp[584450]: 4QR5475Mt9z4xhH: to=<lihua0405@163.com>, relay=none, delay=2025, delays=1905/0.03/120/0, dsn=4.4.1, status=deferred (connect to 163mx00.mxmail.netease.com[220.181.12.180]:25: Connection timed out)

**Comment by iredmail** [comment]
Does your ISP block port 25?

**Comment by fenghualanglang** [comment]
However, there isn't any. I'm using a Vultr server, and I have opened port 25. To test it, I even disabled the firewall, but the connection still times out.


May 24 10:15:03 mail postfix/cleanup[641836]: 4QR6WC2m9jz4xqV: message-id=<120aea097b796ef08ccdd10392d73663@eth.edu.kg>
May 24 10:15:03 mail postfix/qmgr[505444]: 4QR6WC2m9jz4xqV: from=<zhangjunbo@****.kg>, size=1795, nrcpt=1 (queue active)
May 24 10:15:03 mail postfix/10025/smtpd[641887]: disconnect from mail.eth.edu.kg[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
May 24 10:15:03 mail amavis[303208]: (303208-05) Passed CLEAN {RelayedInternal}, ORIGINATING/MYNETS LOCAL [127.0.0.1]:41908 ESMTP/ESMTP <zhangjunbo@eth.edu.kg> -> <zhangjunbo0405@163.com>, (), Queue-ID: 4QR6WB5Xl5z4xny, Message-ID: <120aea097b796ef08ccdd10392d73663@****.kg>, mail_id: AscsR9mcGgpA, b: b1kCrCNwJ, Hits: -0.9, size: 573, queued_as: 4QR6WC2m9jz4xqV, Subject: "11111111231111111111111111", From: <zhangjunbo@****.kg>, User-Agent: Roundcube_Webmail, helo=localhost, Tests: [ALL_TRUSTED=-1,TRACKER_ID=0.1], autolearn=no autolearn_force=no, autolearnscore=0.1, dkim_new=dkim:****.kg, 545 ms
May 24 10:15:03 mail amavis[303208]: (303208-05) Passed CLEAN, <zhangjunbo@****.kg> -> <zhangjunbo0405@163.com>, Hits: -0.9, tag=2, tag2=6.2, kill=6.9, queued_as: 4QR6WC2m9jz4xqV, L/0/0/0
May 24 10:15:03 mail postfix/amavis/smtp[641841]: 4QR6WB5Xl5z4xny: to=<zhangjunbo0405@163.com>, relay=127.0.0.1[127.0.0.1]:10026, delay=0.65, delays=0.07/0.03/0.01/0.54, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 4QR6WC2m9jz4xqV)
May 24 10:15:03 mail postfix/qmgr[505444]: 4QR6WB5Xl5z4xny: removed


May 24 10:15:33 mail postfix/smtp[641889]: connect to 163mx02.mxmail.netease.com[103.129.252.82]:25: Connection timed out

**Comment by iredmail** [comment]
Vultr blocks port 25 by default.

**Comment by fenghualanglang** [comment]
Thank you, your answer has enlightened me and brought clarity.

**Comment by fenghualanglang** [comment]
[root@mail ~]# telnet mail.eth.edu.kg 25
Trying ::1...
Connected to mail.eth.edu.kg.
Escape character is '^]'.
220 mail.eth.edu.kg ESMTP Postfix



===========================================================
Hello, I'm sorry to hear that you're encountering errors after reconfiguring your setup. Please provide me with the specific error you're experiencing, and I'll be glad to help you troubleshoot and find a solution.
===========================================================


May 29 02:39:11 mail postfix/smtps/smtpd[389756]: warning: unknown[46.148.40.193]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:39:14 mail postfix/smtps/smtpd[389756]: lost connection after AUTH from unknown[46.148.40.193]
May 29 02:39:14 mail postfix/smtps/smtpd[389756]: disconnect from unknown[46.148.40.193] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:39:15 mail postfix/smtps/smtpd[389756]: connect from unknown[46.148.40.146]
May 29 02:39:17 mail postfix/smtps/smtpd[389756]: Anonymous TLS connection established from unknown[46.148.40.146]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:39:24 mail postfix/qmgr[1201]: 4QTzSm1mlXz4xd3: from=<zhangjunbo@eth.edu.kg>, size=1794, nrcpt=1 (queue active)
May 29 02:39:24 mail postfix/qmgr[1201]: 4QRhLw4JSlz4xqd: from=<zhangjunbo@eth.edu.kg>, size=1832, nrcpt=1 (queue active)
May 29 02:39:37 mail postfix/smtps/smtpd[395433]: connect from unknown[46.148.40.145]
May 29 02:39:39 mail postfix/smtps/smtpd[395433]: Anonymous TLS connection established from unknown[46.148.40.145]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:39:48 mail postfix/smtps/smtpd[395433]: warning: unknown[46.148.40.145]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:39:48 mail postfix/smtps/smtpd[395433]: lost connection after AUTH from unknown[46.148.40.145]
May 29 02:39:48 mail postfix/smtps/smtpd[395433]: disconnect from unknown[46.148.40.145] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:39:50 mail postfix/smtps/smtpd[389756]: lost connection after EHLO from unknown[46.148.40.146]
May 29 02:39:50 mail postfix/smtps/smtpd[389756]: disconnect from unknown[46.148.40.146] ehlo=1 commands=1
May 29 02:39:55 mail postfix/smtp[394925]: connect to reception.mail-tester.com[94.23.206.89]:25: Connection timed out
May 29 02:39:55 mail postfix/smtp[394925]: 4QRhLw4JSlz4xqd: to=<test-2tmeytfxd@srv1.mail-tester.com>, relay=none, delay=324003, delays=323972/0.05/30/0, dsn=4.4.1, status=deferred (connect to reception.mail-tester.com[94.23.206.89]:25: Connection timed out)
May 29 02:39:55 mail postfix/smtp[394914]: connect to 163mx03.mxmail.netease.com[103.129.252.82]:25: Connection timed out



May 29 02:40:25 mail postfix/smtp[394914]: connect to 163mx01.mxmail.netease.com[103.129.252.82]:25: Connection timed out
May 29 02:40:48 mail postfix/smtps/smtpd[395433]: connect from unknown[46.148.40.149]
May 29 02:40:49 mail postfix/smtps/smtpd[395433]: Anonymous TLS connection established from unknown[46.148.40.149]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:40:55 mail postfix/smtp[394914]: connect to 163mx02.mxmail.netease.com[103.129.252.82]:25: Connection timed out
May 29 02:41:00 mail postfix/smtps/smtpd[395433]: warning: unknown[46.148.40.149]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:41:02 mail postfix/smtps/smtpd[395433]: lost connection after AUTH from unknown[46.148.40.149]
May 29 02:41:02 mail postfix/smtps/smtpd[395433]: disconnect from unknown[46.148.40.149] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:41:03 mail postfix/smtps/smtpd[371661]: timeout after AUTH from unknown[46.148.40.77]
May 29 02:41:03 mail postfix/smtps/smtpd[371661]: disconnect from unknown[46.148.40.77] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:41:03 mail postfix/smtps/smtpd[389756]: connect from unknown[46.148.40.144]
May 29 02:41:05 mail postfix/smtps/smtpd[389756]: Anonymous TLS connection established from unknown[46.148.40.144]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:41:18 mail postfix/smtps/smtpd[389756]: warning: unknown[46.148.40.144]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:41:25 mail postfix/smtp[394914]: connect to 163mx00.mxmail.netease.com[220.181.12.180]:25: Connection timed out
May 29 02:41:25 mail postfix/smtp[394914]: 4QTzSm1mlXz4xd3: to=<zhangjunbo0405@163.com>, relay=none, delay=2013, delays=1893/0.05/121/0, dsn=4.4.1, status=deferred (connect to 163mx00.mxmail.netease.com[220.181.12.180]:25: Connection timed out)
May 29 02:41:30 mail postfix/smtps/smtpd[395433]: connect from unknown[46.148.40.142]
May 29 02:41:31 mail postfix/smtps/smtpd[395433]: Anonymous TLS connection established from unknown[46.148.40.142]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:41:31 mail postfix/smtps/smtpd[371661]: connect from unknown[46.148.40.192]
May 29 02:41:33 mail postfix/smtps/smtpd[371661]: Anonymous TLS connection established from unknown[46.148.40.192]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:41:40 mail postfix/smtps/smtpd[395433]: warning: unknown[46.148.40.142]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:41:42 mail postfix/smtps/smtpd[395433]: lost connection after AUTH from unknown[46.148.40.142]
May 29 02:41:42 mail postfix/smtps/smtpd[395433]: disconnect from unknown[46.148.40.142] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:41:45 mail postfix/smtps/smtpd[371661]: warning: unknown[46.148.40.192]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:41:48 mail postfix/smtps/smtpd[371661]: lost connection after AUTH from unknown[46.148.40.192]
May 29 02:41:48 mail postfix/smtps/smtpd[371661]: disconnect from unknown[46.148.40.192] ehlo=1 auth=0/1 rset=1 commands=2/3
May 29 02:42:09 mail postfix/smtps/smtpd[395433]: connect from unknown[46.148.40.143]
May 29 02:42:10 mail postfix/smtps/smtpd[395433]: Anonymous TLS connection established from unknown[46.148.40.143]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
May 29 02:42:19 mail postfix/smtps/smtpd[395433]: warning: unknown[46.148.40.143]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
May 29 02:42:32 mail postfix/anvil[321044]: statistics: max connection rate 1/60s for (465:46.148.40.153) at May 29 02:34:03
May 29 02:42:32 mail postfix/anvil[321044]: statistics: max connection count 1 for (465:46.148.40.153) at May 29 02:34:03
May 29 02:42:32 mail postfix/anvil[321044]: statistics: max cache size 5 at May 29 02:39:39

**Comment by iredmail** [comment]
Seems your ISP blocks port 25.
网络端口 25 被运营商封禁了。

**Comment by fenghualanglang** [comment]
Hello, my port 25 has already been opened by the ISP, and telnet mail.eth.edu.kg 25 is successful

telnet mail.eth.edu.kg 25
Connected to mail.eth.edu.kg.
Escape character is '^]'.
220 mail.eth.edu.kg ESMTP Postfix

**Comment by iredmail** [comment]
There're inbound and outbound on port 25.
Inbound is fine, but outbound seems blocked.
