### ISSUE TITLE
Provide options

### ISSUE THREAD

**Issue by peterpt** [iredmail/iRedMail#216]
I was trying to install latest version without any success , lost my patience .
Problem was that uwgsi was not opening the socket for nginx .
Could you guys please provide an option for installing on apache2 ?
this looks like when people was forced to move to systemd from sysinit initiation boot by debian , despite the fact that almost every 2 weeks a bug or a vulnerability is discovered .

Nginx is only good for simple stuff , not a mail server , i have used 0.6.8 for several years on apache without any issue , sadly i had an unrecoverable issue in the hdd and lost everything in mail server .

**Comment by Anzulo1984** [comment]
Neither did you provide any information on which distro you are trying to install, so no troubleshooting is possible
And what choices do you want?

Talking about nginx beeing only good for simple stuff tells me, that you have literally no idea what you are talking about:

https://w3techs.com/technologies/details/ws-nginx

Just a simple illustration about how much nginx is used

**Comment by peterpt** [comment]
On this is was trying to install on Devuan witch is debian based , i had to replace my os-releases from devuan to debian to do the trick , did not wanted to change the original os-version from devuan to debian version 10 or 11 .
Everything went right until script start to add systemd start ups witch does not exist in devuan , and then got that wusgi issue .
I had redmail installed for several years on apache config without any issue , and just because someone says that falling from a cliff is good it does not mean that it is right , i had at that time nginx wuning port 80 and apache on iredmail , nginx was more often down than apache , and there was no php running on nginx .
I believe that providing an option for users to use apache is good for everyone , right now i am with an issue on redirecting / to mail/ where i already commented all those lines in templates from roundcube and it is still doing it , on apache this probably wount happen because the config files are more simple to understand .

**Comment by Anzulo1984** [comment]
Apache was dropped long time ago and won't come back, and i don't know why you have to install it on an unsupported distro, you can straight up use debian and dont have any struggles

**Comment by peterpt** [comment]
i know , problem is that i am not a fan of systemd and debian is that .
https://www.cvedetails.com/vulnerability-list/vendor_id-15978/product_id-34874/Systemd-Project-Systemd.html

and since more people use it then more vulnerabilities will pop up .

Just keep configurations simple and easy to understand like before , now every web access roundcube , iredadmin , netdata and sogo run on port 443 , if someone wants to set iredmail to 8443 port will have to create new vhost for that . 
Iredmail should not be wide opened to the web , everything in email configuration is there . An alternative port like 8443 would be nice for it releasing it from a crash on port 443 from server . If port 443 falls down from any reason then all services will go down with it , not any 1 will be up .

Well , it looks i have to figure this out myself on the way i can . 

There is no more need to continue this because you already said "Apache was dropped long time ago and won't come back" .

I will close this issue now , thank you
