### ISSUE TITLE
Disable redirect from 80 to 443

### ISSUE THREAD

**Issue by peterpt** [iredmail/iRedMail#217]
Finally i was able to put this working here , however i want to disable the redirection from http to https and i can not find the config file that you guys created , i disable the redirection in templates but it is still redirecting to https:///somedomain/mail/

I even disable nginx and installed apache 2 and started it , and redirects anyway !!!
I have no idea where did you guys apply that configuration , i even cleaned my browser cache , deleted ssl certificate and it still continues redirecting !!
problem is that i need to create other vhosts in different ports not ssl like 8443 , and i can not do it because as soon as i enter the domain i get redirected automatically to port 443 .
How can i disabled redirection ?

Also it would be a good idea to take out that option in future from iredmail so admin can create different vhosts .

**Comment by iredmail** [comment]
It's /etc/nginx/sites-enabled/00-default.conf.

**Comment by peterpt** [comment]
actually that was already made before , that was not the issue , the issue in fact it is in the new web browsers today like firefox an chrome that automatically do that .
i had to got into about:config in firefox and set these values : 

network.stricttransportsecurity.preloadlist and set it to false
dom.security.https_first to false
dom.security.https_first_pbm to false

Also had to change in : /etc/nginx/templates/hsts.tmpl
the value : 
add_header Strict-Transport-Security  to "max-age=0"

to make it work , however i have no idea why it is still reedirecting on https the folder mail/ , despite the fact that i already comented in that redirect URI to mail/ in roundcube template .

in fact there is nothing now in roundcube templates with that directory to point to , but it is still doing it , this part i need some help .
