### ISSUE TITLE
Debian 12

### ISSUE THREAD

**Issue by Anzulo1984** [iredmail/iRedMail#218]
Debian 12 was released 2 days ago, support should be added asap

iredmail should work out of the box without any problems (at least if it is a clean install and not an dist-upgrade)

**Comment by Anzulo1984** [comment]
I'm already on it, made the install script working and setup a test system on a VM

So far: can confirm installation works, and noticed that debian 10 is still supported for install, even when support was officially dropped already

I'm gonna test further and prepare a pull request

**Comment by Anzulo1984** [comment]
Before i continue and create a patch:

do you want to drop debian 10 support in install script?

since changes from debian 11 -> 12 also include php7.4 -> php8.2 as default, which could cause problems with latest sogo which has problems with php < 8.1

since bookworm has latest sogo that supports/needs php8.2 without useing nightly, i would suggest dropping debian11 for fresh installs

**Comment by iredmail** [comment]
I have time today and will take over your PR and continue. Thanks for the contribution. :)

**Comment by Anzulo1984** [comment]
Did last commit, got pgsql to work

**Comment by iredmail** [comment]
I use `netcat-openbsd` instead of your `netcat-traditional`, because:

> This is the "classic" netcat, written by *Hobbit*. It lacks many features found in netcat-openbsd.

FYI https://packages.debian.org/bookworm/netcat-traditional

**Comment by Anzulo1984** [comment]
makes sense, thus makes no difference since it still works
but netcat alone did not install, i had to choose a release since netcat alone went into a virtual package

**Comment by iredmail** [comment]
Hi @Anzulo1984 

Debian 12 support is done. Please help test with latest development edition. :)

**Comment by Anzulo1984** [comment]
which one should i try? ldap/pg/mysql

**Comment by iredmail** [comment]
We need help to test all backends. :)

**Comment by Anzulo1984** [comment]
currently @ mysql

**Comment by cwchristerw** [comment]
@iredmail What is schedule for new release? I currently have very old iRedMail installation and I need to create new iRedMail installation and I have to use latest Debian version.
