### ISSUE TITLE
Error: OperationalError(1054, "Unknown column 'enablesogoactivesync' in 'field list'") in iRedAdmin Pro

### ISSUE THREAD

**Issue by vanken18** [iredmail/iRedMail#225]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.3
- Deployed with iRedMail Easy or the downloadable installer? downloadable
- Linux/BSD distribution name and version: Ubuntu 22.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL
- Web server (Apache or Nginx): Apache
- Manage mail accounts with iRedAdmin-Pro? Yes
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
Error: OperationalError(1054, "Unknown column 'enablesogoactivesync' in 'field list'")

Upon unchecking this 
![image](https://github.com/iredmail/iRedMail/assets/106047523/fd47a078-471d-4bfa-999c-235a80475a93)
and then saving the configuration, I encounters the error above.

**Comment by Anzulo1984** [comment]
Web server (Apache or Nginx): Apache

So you modified your iredmail instance

i guess you did an upgrade and didnt apply the database changes

**Comment by iredmail** [comment]
Hi @vanken18 

You missed some step while upgrading iRedMail from old release. Search "enablesogoactivesync" will give you some hint:
https://github.com/search?q=repo%3Airedmail%2Fdocs+enablesogoactivesync+language%3AHTML&type=code&l=HTML
