### ISSUE TITLE
Weird mail address in Spider Email Archiver

### ISSUE THREAD

**Issue by M-Stenzel** [iredmail/iRedMail#226]
Hi team,

this relates to the Spider Email Archiver, version 2.4.0.

In the bottom left corner the webmaster address (mouse pointer over the text) is written (in the screenshot it is too blurry):
a; d; m; i; n; @; m; a; i; l; .; x; y; -; s; p; a; c; e; .; d; e

So an extra "; " is added after each letter. This is an error.

This is my settings.json file (rather private info deleted!)

`{
        "admin_emails": ["admin@mail.xy-space.de"],
        "archiving_username": "archive",
        "archiving_domain": "",
        "archiving_with_host_ip": true,
        "license_key": "",
        "log_level": "info",
        "log_target": "file",
        "log_rotate_interval": "1w",
        "log_max_backups": 20,
        "log_syslog_server": "/dev/log",
        "retention_years": 3,
        "smtpd_bind_address": ":25",
        "smtpd_force_secure_conn": false,
        "smtpd_allowed_only": true,
        "smtpd_auth": true,
        "smtpd_user": "",
        "smtpd_password": "",
        "web_bind_address": ":8080",
        "web_home_path": "",
        "web_default_language": "en_US",
        "cert_domain": ""
}`

![Error](https://github.com/iredmail/iRedMail/assets/76916440/7b9dac62-224b-4f13-99ef-0e26aaf32c5b)

**Comment by iredmail** [comment]
- Re-packed v2.4.0 with this fix: https://spiderd.io/releases/spider-v2.4.0-linux-amd64.tar
- Docker image are rebuilding and may take few minutes to finish: https://hub.docker.com/r/iredmail/spider
