### ISSUE TITLE
Missing in doc - Alias to one account in same domain

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#23]
Hello,
I try find a way how to create alias for account in same domain.
Step do reproduce:
Create account user@domain.com
i want create alias admin@domain.com to forward email to user@domain.com and i can`t find in doc...

Can You help me and add this information to DOCs.

**Comment by iredmail** [comment]
Search "mail forwarding" on document index page: https://docs.iredmail.org :)

**Comment by takenek** [comment]
There is example how create virtual alias to forward mail to 2 account in other domain. i want create normal alias for this same domain.

**Comment by iredmail** [comment]
FYI: https://docs.iredmail.org/sql.create.mail.alias.html

You can search https://docs.iredmail.org/
