### ISSUE TITLE
A new website cannot be added on the same server.

### ISSUE THREAD

**Issue by PYU224** [iredmail/iRedMail#230]
I tried to add a new website at 'example.com' on a server with iRedmail installed at 'mail.example.com', but I am redirected to Roundcube and can't.
How can I add a website without redirects?

**Comment by iredmail** [comment]
How did you add this new website in Nginx? Do you specify a `root` directory for it?

**Comment by PYU224** [comment]
I have added the file as below.

/etc/nginx/sites-enabled/example.com
```
server {
        listen 80;
        listen [::]:80;

        server_name example.com www.example.com;

        root /var/www/example.com;
        index index.html index.php;

        location / {
                try_files $uri $uri/ =404;
        }
}

server {
        listen 443;
        listen [::]:443;

        root /var/www/example.com;
        index index.html index.php;

        server_name example.com www.example.com;

        location / {
                try_files $uri $uri/ =404;
        }
}
```

**Comment by iredmail** [comment]
> /etc/nginx/sites-enabled/example.com

File name must be ended with `.conf`, for example, `example.com.conf`. Otherwise it's not loaded by Nginx at all.

**Comment by spoonfuldust** [comment]
`/etc/nginx/sites-enabled/api.conf` - file location

```
server {
    listen 80;
    server_name www.api.example.com api.example.com;
    access_log /var/log/nginx/srv1.log;
    error_log /var/log/nginx/srv1_error.log;
    rewrite ^(.*) https://api.example.com$1 permanent;
    server_tokens off;

    location / {
           include proxy_params;
           proxy_pass http://127.0.0.1:8001;
       }
}
```
as far as I understand it should work, but it doesn't

**Comment by spoonfuldust** [comment]
on api.example.com/docs I should have api documentation, but have 404
on api.example.com/mail I shouldn't have anything, but have Roundcube, like on mail.example.com/mail

**Comment by iredmail** [comment]
You added web host api.example.com running on port 80, I guess you visited https:// which is port 443?
