### ISSUE TITLE
managing sieve filters from thunderbird using tb extension

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#231]
Managing sieve filters from thunderbird using extension plugin was working in some old version of iredmail as I remmember.

Why this was removed?
What is instead that?
How to enable that in newest release?

**Comment by iredmail** [comment]
You can update Dovecot config file to make managesieve listening on public network interface, also open port `4190` in firewall, then it's reachable.

**Comment by interduo** [comment]
Maybe installer should ask about it?

**Comment by iredmail** [comment]
No plan for this. Sorry.
