### ISSUE TITLE
warning: dnsblog_query: lookup error for DNS query - bug or too verbose error reporting?

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#232]
`2023-07-26T14:35:10.187741+00:00 poczta postfix/dnsblog[10492]: warning: dnsblog_query: lookup error for DNS query 97.139.105.184.b.barracudacentral.org: Host or domain name not found. Name service error for name=97.139.105.184.b.barracudacentral.org type=A: Host not found, try again
`

**Comment by Anzulo1984** [comment]
This is not a bug, it is caused by your DNS resolver.
barracuda has lookup limits, so if you use a highly used DNS resolver, it can block the query

OR

barracuda was unreachable at this very moment

**Comment by interduo** [comment]
On fresh install You need to:
- go to barracudacentral.org,
- register an account,
- configure IP addresses list,

I suggest to put this info in manual and installer.
