### ISSUE TITLE
Oud Of Office auto-reply doesn't respect transport settings

### ISSUE THREAD

**Issue by jwegge** [iredmail/iRedMail#234]
When using a filter created in round cube (such as out of office) on a setup where all outgoing malis is sent through an external server ("Relay outgoing email to" in web front-end), this is not done for the reply generated on the server itself.

Detail: we use Proxmox mail gateway for in- & outgoing email.
Iredmail is configured for all hosted domains to use the external mail gateway (in my case 10.10.10.14:26).
All outgoing email is scanned by the Proxmox mail gateway EXCEPT for the "out of office" messages, which get sent directly by iredmail to the destination mailserver.

Destination mailserver may or may not accept these messages as different pub ip & hostname as the expected mail gateway (dkim & spf gets mangled).

**Comment by Anzulo1984** [comment]
Yes, because it is an autoreply, it strips out sender and other stuff to avoid bounceback loops, and aswell doesn't send trough normal sasl authenticated domain settings

consider it as an advanced bounce message

**Comment by Anzulo1984** [comment]
you can manually add a virtual transport map for such things

**Comment by bcnx** [comment]
> you can manually add a virtual transport map for such things

Hi, I'm looking at the same problem as well and I just discovered that the autoreply mails are not using the local Postfix instance. So Postfix virtual transport or transport maps will not help. 
Is there any way to send those mails to a relay host as well?

Thanks,

BC
