### ISSUE TITLE
Iredmail 1.4.1 installation fail on Centos 9 stream

### ISSUE THREAD

**Issue by sureshnwe** [iredmail/iRedMail#238]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.1
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): LDAP
- Web server (Apache or Nginx):Ngnix
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

I try to install iredmail 1.4.1 on Centos 9 stream. fails with below error.

[root@mail1 iRedMail-1.6.4]# bash iRedMail.sh
[ INFO ] Checking configuration file: /opt/mailapp/iRedMail-1.6.4/config ... [FOUND]
< Question > Use it for mail server setting? [y|N]y
[ INFO ] Use config file: /opt/mailapp/iRedMail-1.6.4/config for mail server setting.
[ INFO ] Import installation process status from file: /opt/mailapp/iRedMail-1.6.4/runtime/install.status.
--2023-09-06 17:07:19--  https://keys.openpgp.org/vks/v1/by-fingerprint/74FFC6D72B925A34B5D356BDF8A27B36A6E2EAE9
Loaded CA certificate '/etc/pki/tls/certs/ca-bundle.crt'
Resolving keys.openpgp.org (keys.openpgp.org)... 37.218.245.50, 2a00:c6c0:0:154:1::1
Connecting to keys.openpgp.org (keys.openpgp.org)|37.218.245.50|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

[ INFO ] Add yum repo for SOGo: /etc/yum.repos.d/sogo.repo.
[ INFO ] Installing package(s): rsyslog firewalld python3 python3-pip python3-pip-wheel python3-requests uwsgi-logger-syslog uwsgi-plugin-python3 postfix cyrus-sasl cyrus-sasl-lib cyrus-sasl-plain postfix-pcre postfix-ldap openldap-servers openldap-clients mariadb-server perl-DBD-mysql python3-ldap php-cli php-common php-fpm php-gd php-xml php-mysqlnd php-ldap php-pgsql php-mbstring php-pecl-apcu php-intl php-json php-pecl-zip nginx dovecot dovecot-pigeonhole dovecot-mysql amavis spamassassin altermime perl-Mail-SPF lz4 clamav clamav-update clamav-server clamav-server-systemd mlmmj python3-ldap python3-PyMySQL sogo sogo-activesync libwbxml sogo-ealarms-notify sogo-tool sope49-gdl1-mysql sope49-ldap mysql-libs python3-sqlalchemy python3-setuptools python3-dns python3-six python3-ldap python3-PyMySQL python3-jinja2 python3-PyMySQL python3-dns python3-simplejson fail2ban curl libmnl libuuid lm_sensors nc zlib iproute python3-pyyaml unzip bzip2 acl patch tmpwatch crontabs dos2unix logwatch lz4
No repository match: rpmforge
No repository match: remi-safe
No repository match: ius
No repository match: remi
No repository match: remi-php74
No repository match: atrpms
SOGo Groupware                                  4.1 kB/s | 2.9 kB     00:00
Package rsyslog-8.2102.0-117.el9.x86_64 is already installed.
Package firewalld-1.2.5-1.el9.noarch is already installed.
Package python3-3.9.17-2.el9.x86_64 is already installed.
Package python3-pip-wheel-21.2.3-7.el9.noarch is already installed.
Package cyrus-sasl-lib-2.1.27-21.el9.x86_64 is already installed.
Package python3-setuptools-53.0.0-12.el9.noarch is already installed.
Package python3-six-1.15.0-9.el9.noarch is already installed.
Package curl-7.76.1-26.el9.x86_64 is already installed.
Package libmnl-1.0.4-15.el9.x86_64 is already installed.
Package libuuid-2.37.4-15.el9.x86_64 is already installed.
Package zlib-1.2.11-40.el9.x86_64 is already installed.
Package iproute-6.2.0-5.el9.x86_64 is already installed.
Package unzip-6.0-56.el9.x86_64 is already installed.
Package acl-2.3.1-3.el9.x86_64 is already installed.
Package crontabs-1.11-26.20190603git.el9.noarch is already installed.
Error:
 Problem: package openldap-servers-2.6.2-2.el9.x86_64 from epel requires openldap(x86-64) = 2.6.2, but none of the providers can be installed
  - cannot install both openldap-2.6.3-1.el9.x86_64 from baseos and openldap-2.6.2-2.el9.x86_64 from baseos
  - cannot install both openldap-2.6.3-1.el9.x86_64 from baseos and openldap-2.6.2-3.el9.x86_64 from baseos
  - package openldap-clients-2.6.3-1.el9.x86_64 from baseos requires openldap(x86-64) = 2.6.3-1.el9, but none of the providers can be installed
  - cannot install both openldap-2.6.2-2.el9.x86_64 from baseos and openldap-2.6.3-1.el9.x86_64 from @System
  - cannot install both openldap-2.6.2-3.el9.x86_64 from baseos and openldap-2.6.3-1.el9.x86_64 from @System
  - conflicting requests
  - cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/
[root@mail1 iRedMail-1.6.4]#

**Comment by iredmail** [comment]
Package `openldap` is installed after OS installation, please upgrade your system to latest version with `yum update` first, then install iRedMail.

You should have `openldap-2.6.2-3.el9.x86_64` and `openldap-compat-2.6.2-3.el9.x86_64` after `yum update`.
