### ISSUE TITLE
onlyoffice mail docker

### ISSUE THREAD

**Issue by Belgerix** [iredmail/iRedMail#24]
Please excuse me if this question is simple 
I am new to this
I am attempting to use the Onlyoffice mail docker run as host  with mysql 5.7.29 on ubuntu everything seems to link up untill   
,ERROR 1062 (23000) at line 4 in file: '/tmp/cluebringer_init_sql.1530222400': Duplicate entry 'SenderIP:71.XXX.XX.XX' for key 'Source'

**Comment by iredmail** [comment]
Sorry, You should contact onlyoffice support instead. :)
