### ISSUE TITLE
Missing indexes on database structure

### ISSUE THREAD

**Issue by Anzulo1984** [iredmail/iRedMail#240]
https://forum.iredmail.org/post87451.html

1 row in set (47.928 sec)

considering the insane amount of time on this query takes (but without any failures), my best guess is that it must be caused by missing or bad indexes on the related tables

**Comment by Anzulo1984** [comment]
i tested this on my backend:

SELECT COUNT(msgs.mail_id) AS total
FROM msgs
LEFT JOIN msgrcpt ON (msgs.mail_id = msgrcpt.mail_id)
LEFT JOIN maddr AS sender ON (msgs.sid = sender.id)
LEFT JOIN maddr AS recip ON (msgrcpt.rid = recip.id)
WHERE msgs.quar_type <> 'Q';

result:

total 2133,  0,031 Sec

**Comment by iredmail** [comment]
- 0.031 sec seems fine.
- each column used in query is indexed separately, although no composite index, but it should be still fast enough.
- How many records in each table: msgs, msgrcpt, quarantine?
- Please show us your indexes, and compare them with the ones created by iRedMail: https://github.com/iredmail/iRedMail/blob/master/samples/amavisd/amavisd.mysql

```
SHOW INDEX FROM msgs;
SHOW INDEX FROM msgrcpt;
SHOW INDEX FROM quarantine;
```
