### ISSUE TITLE
Lost package

### ISSUE THREAD

**Issue by hanmaier** [iredmail/iRedMail#242]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.6
- Linux/BSD distribution name and version: Ubuntu or Centos etc..
![image](https://github.com/iredmail/iRedMail/assets/83855766/242cb549-fd89-4aec-a9b9-544cb64b519b)
netdata-v1.43.0.gz.run
roundcubemail-1.6.4-complete.tar.gz
lost two file,  source website didnot add ?

**Comment by iredmail** [comment]
Fixed, thanks for the feedback. :)

**Comment by theking0912** [comment]
> Fixed. You're trying the development edition, it's not always stable and we don't recommend to use it in production, you won't get upgrade tutorial for development edition too.

thank you for your recommendation, I will try the stable version. thanks again！
