### ISSUE TITLE
大量退信邮件如何批量删除

### ISSUE THREAD

**Issue by Universe91** [iredmail/iRedMail#25]
之前有个账号被利用发送垃圾邮件，导致有上万封退信邮件，请问这些邮件如何删除，不能清空所有收件箱，里面有正常邮件

**Comment by iredmail** [comment]
只能使用 postqueue 命令配合 grep/awk 等命令过滤出你要删除的邮件的 queue id，然后用 postsuper 命令删除之。

**Comment by Universe91** [comment]
队列里的垃圾信息已经被我清了

**Comment by iredmail** [comment]
那你要解决的问题是？

**Comment by Universe91** [comment]
![image](https://user-images.githubusercontent.com/52906754/79110390-e3ec9100-7dac-11ea-8662-cc51c002d507.png)
收件箱里的还存在

**Comment by Universe91** [comment]
之前使用过postsuper -d ALL deferred命令

**Comment by iredmail** [comment]
已经投递到邮箱的邮件可以用 doveadm 的相关子命令来查找和删除：
https://wiki.dovecot.org/Tools/Doveadm
