### ISSUE TITLE
Oops... something went wrong!

### ISSUE THREAD

**Issue by y0zhyck** [iredmail/iRedMail#250]
![image](https://github.com/iredmail/iRedMail/assets/38162408/9645d514-708c-4d19-8f36-8dd7adbf1d3b)

My mail was working fine, for a second something broke (on the hosting side) now I can't use iredmail how can I fix this situation?

I am using Debain 12

**Comment by iredmail** [comment]
- Which web application is this?
- What's related error in log file?

**Comment by y0zhyck** [comment]
> * Which web application is this?
> * What's related error in log file?

It is no longer relevant, we have woken up... Good morning sleeping princesses, I moved to mail cow
