### ISSUE TITLE
Feature: allow to purge mail from trash after 30days from deleting and make trashbin read-only

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#251]
I would like to dramaticly reduce count of support ticket issues regarding of recovering deleted mails/mailbox is full issue.

Is it possible in iredAdmin-Pro:
- automaticly purge mail from trash after 30days from deleting,
- making trashbin read-only
?

I didn't find this in docs.

**Comment by iredmail** [comment]
> * automaticly purge mail from trash after 30days from deleting,

Better done in Dovecot.
FYI https://doc.dovecot.org/configuration_manual/namespace/#core_setting-namespace/mailbox/autoexpunge

**Comment by interduo** [comment]
How to make read-only trashbin?
