### ISSUE TITLE
cleanup_amavisd_db.py - TypeError: unhashable type: 'bytearray'

### ISSUE THREAD

**Issue by kman261** [iredmail/iRedMail#253]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  1.6.8
- Deployed with iRedMail Easy or the downloadable installer? downloadable
- Linux/BSD distribution name and version: Rocky Linux 9
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySql
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
I recently created a new mail server and migrated from an old Centos 7 server, originally 0.9.5-1, but continually updated to 1.6.8 using the docs.  Things seem to be fine, with a few exceptions I am still working on.  

I have been getting this error in my daily cron emails.  I checked all changes to amavisd back to iRedmail 0.9.5, and believe I performed all updates, but I am possibly missed something.

Traceback (most recent call last):
  File "/opt/www/iredadmin/tools/cleanup_amavisd_db.py", line 180, in <module>
    msgs_mail_ids.add(i.mail_id)
TypeError: unhashable type: 'bytearray'

also running manually returns:
python /opt/www/iRedAdmin-2.5/tools/cleanup_amavisd_db.py
* Backend: mysql
* SQL server: 127.0.0.1:3306
* Enable dirty read for querying without locking SQL tables.
* Delete quarantined mails which older than 7 days
* Delete incoming/outgoing emails which older than 7 days
*       [-] Deleting records: 1 - 25 (Tue Mar 12 08:18:28 2024)
* Delete unreferenced records from table `msgrcpt`.
* Delete unreferenced records from table `quarantine`.
Traceback (most recent call last):
  File "/opt/www/iRedAdmin-2.5/tools/cleanup_amavisd_db.py", line 180, in <module>
    msgs_mail_ids.add(i.mail_id)
TypeError: unhashable type: 'bytearray'

The new server has 45 rows in the quarantine table.

Thanks,
Dave

**Comment by iredmail** [comment]
I can not reproduce it locally.
Is it possible to give me direct ssh access with root privilege for quick troubleshooting? Contact me: support _at_ iredmail.org.

**Comment by kman261** [comment]
I sent an email to you yesterday.  Thanks

**Comment by iredmail** [comment]
fixed in https://github.com/iredmail/iRedAdmin/commit/46cee3d9658faa35c291931634d86da4c007ee8f
