### ISSUE TITLE
Max connection reached for 127.0.0.1:7790 when managing users from portal

### ISSUE THREAD

**Issue by bolinches** [iredmail/iRedMail#256]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.8
- Deployed with iRedMail Easy or the downloadable installer? installer
- Linux/BSD distribution name and version: FreeBSD 13.3
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL 
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro? Pro
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

When creating, editing or deleting users from iRedAdmin-Pro 5.5

I get "Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=7790): Max retries exceeded with url: /api/subscriber/user@mydomain.com/subscribed?query_all_lists=no&email_only=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x8788bb850>: Failed to establish a new connection: [Errno 61] Connection refused'))")) "

And does nto get deleted, edited or created

**Comment by iredmail** [comment]
mlmmjadmin service was not running, please restart it.

**Comment by bolinches** [comment]
Thanks. That was it.
