### ISSUE TITLE
Unable to install to Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by cwchristerw** [iredmail/iRedMail#257]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.8
- Deployed with iRedMail Easy or the downloadable installer? Installer
- Linux/BSD distribution name and version: Ubuntu 24.04 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? -
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue. -

```
[ INFO ] Installing package(s): python3-setuptools python3-pip python3-wheel python3-requests uwsgi uwsgi-plugin-python3 postfix postfix-pcre libsasl2-modules mariadb-client mariadb-server postfix-mysql libdbd-mysql-perl php-cli php-fpm php-json php-gd php-curl mcrypt php-intl php-xml php-mbstring php-zip php-mysql nginx-full dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-managesieved dovecot-sieve dovecot-mysql amavisd-new libcrypt-openssl-rsa-perl libmail-dkim-perl clamav-freshclam clamav-daemon spamassassin altermime arj nomarch cpio lzop cabextract p7zip-full rpm libmail-spf-perl unrar-free pax lrzip gpg-agent libclamunrar9 mlmmj python3-pymysql python3-sqlalchemy python3-dnspython python3-pymysql python3-jinja2 python3-netifaces python3-bcrypt python3-dnspython python3-simplejson python3-pymysql fail2ban geoip-bin geoip-database bzip2 acl patch cron tofrodos logwatch unzip bsdutils liblz4-tool rsyslog nftables
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libclamunrar9
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/
```

**Comment by cwchristerw** [comment]
https://packages.ubuntu.com/search?keywords=libclamunrar&searchon=names&suite=all&section=all

Instead of using libclamunrar9, use libclamunrar or libclamunrar11 package.

**Comment by iredmail** [comment]
- iRedMail-1.6.8 doesn't support Ubuntu 24.04 at all.
- Upcoming iRedMail-1.7.0 supports Ubuntu 24.04, we're still waiting for Fail2ban. https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/2055114

**Comment by iredmail** [comment]
Fail2ban is now working on Ubuntu 24.04, we're ready to tag new iRedMail version. :)
