### ISSUE TITLE
The SMTP port 25 is blocked by the cloud provider. (DigitalOcean)

### ISSUE THREAD

**Issue by elduglas** [iredmail/iRedMail#258]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.8
- Deployed with iRedMail Easy or the downloadable installer? Downloable Installer
- Linux/BSD distribution name and version: Ubuntu 22.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): Postgres 
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hello, I requested DigitalOcean to unblock the SMTP port and they said no. Is it possible to change it so it can work on another port? This is what they said:

![image](https://github.com/iredmail/iRedMail/assets/9750729/d4e4ae7f-0648-42fd-9a3a-de3255338147)

If it's not possible, what would you recommend doing?

Thanks so much!!!

**Comment by iredmail** [comment]
Port 25 is required. If impossible to open it, then switch to another VPS vendor which allows port 25.
Linode and Amazon EC2 seem ok: https://docs.iredmail.org/install.iredmail.on.rhel.html#system-requirements

**Comment by elduglas** [comment]
> Port 25 is required. If impossible to open it, then switch to another VPS vendor which allows port 25. Linode and Amazon EC2 seem ok: https://docs.iredmail.org/install.iredmail.on.rhel.html#system-requirements

Oki, thanks so much!!!
