### ISSUE TITLE
Missing iRedAPD tarball

### ISSUE THREAD

**Issue by denormalizer** [iredmail/iRedMail#26]
On a fresh Centos7 system, I tried to install iRedMail and I got an error about a missing iRedAPD tarball. Specifically, iRedAPD-3.6.tar.gz

How to reproduce:

    git clone https://github.com/iredmail/iRedMail.git
    cd iRedMail
    bash iRedMail.sh

Result:

    sha256sum: misc/iRedAPD-3.6.tar.gz: No such file or directory
    misc/iRedAPD-3.6.tar.gz: FAILED open or read

Looking at the dir at this location:

    https://dl.iredmail.org/yum/misc/

I can see that iRedAPD only goes up to: iRedAPD-3.5.tar.gz

**Comment by iredmail** [comment]
There’s critical issue in iRedAPD-3.6 found yesterday, had to remove it and repack before publicly announce this new release. 

Will tag iRedMail-1.2 tomorrow. :)

**Comment by denormalizer** [comment]
Ah OK. I don't know the internals of iRedMail (yet), but would it work if it dropped back to using iRedAPD-3.5 instead?

**Comment by iredmail** [comment]
Yes it works with iRedAPD-3.5. But better download the repacked 3.6 here:
https://github.com/iredmail/iRedAPD/archive/3.6.tar.gz

**Comment by denormalizer** [comment]
I tried to put it in ./pkgs/misc but new error:

    sha256sum: WARNING: 1 computed checksum did NOT match

I'll wait for the new release :)

**Comment by iredmail** [comment]
You can run “shasum -a 256 iRedAPD-3.6.tar.gz” to get the shasum, then update files “pkgs/pkgs*shasum” with this new shasum.

**Comment by iredmail** [comment]
iRedMail-1.2 has been tagged. Release notes and announcement will be published tomorrow (too late today). Enjoy. :)

**Comment by denormalizer** [comment]
All good now. Thanks
