### ISSUE TITLE
Installing iRedmail on FreeBSD 14

### ISSUE THREAD

**Issue by angelotheman** [iredmail/iRedMail#260]
I haven't been able to install the iRedMail server (1.7.1) to my FreeBSD system.

It always ends up giving me this error

```
===> Fetching all distfiles required by py311-pluggy0-0.13.1_1 for building
===>   py311-wcwidth-0.2.8 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by py311-wcwidth-0.2.8 for building
===>  lsof-4.99.3_2,8 requires kernel sources.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/sysutils/lsof
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/py-Jinja2
<< ERROR >> Failed in downloading package(s), please fix it manually and then relaunch iRedMail installer.
```

at the tail end of the message.
I haven't been able to fix

**Comment by iredmail** [comment]
> ===>  lsof-4.99.3_2,8 requires kernel sources.

Grab FreeBSD kernel source first, then install again.

**Comment by angelotheman** [comment]
I'm sorry, but how do I do that?

If a practical step is given, I would really love it. 

Thanks.

**Comment by angelotheman** [comment]
Hello,

I still got this error after figuring out how to grab the kernel source

```
=> Attempting to fetch https://files.pythonhosted.org/packages/source/w/wcwidth/wcwidth-0.2.8.tar.gz
wcwidth-0.2.8.tar.gz                                    60 kB  143 MBps    00s
===> Fetching all distfiles required by py311-wcwidth-0.2.8 for building
===>  lsof-4.99.3_2,8 requires kernel sources.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/sysutils/lsof
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/py-Jinja2
<< ERROR >> Failed in downloading package(s), please fix it manually and then relaunch iRedMail installer.
```

**Comment by githonk** [comment]
I had exactly the same issue and decided to reinstall and select the system source tree "src" during the selection of which system components to install. The install script worked after that.

**Comment by angelotheman** [comment]
I don't really understand. Could you assist me with the commands you used and in what directory

**Comment by iredmail** [comment]
Installing packages via ports tree didn't need FreeBSD source tree before, but not sure which package port requires `lsof` which requires source tree... I still didn't figure out which package port relies on `lsof` yet.
