### ISSUE TITLE
The IP you're using to send mail is not     authorized to 550-5.7.1 send email directly to our servers

### ISSUE THREAD

**Issue by osizadmin** [iredmail/iRedMail#264]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.7.0 PGSQL edition
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: Ubuntu 22.04.4 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL
- Web server (Apache or Nginx):Nginx
- Manage mail accounts with iRedAdmin-Pro? roundcube webmail
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Sep  2 14:20:09 redmail postfix/smtp[1093692]: 4Wy9rQ2dx2dz8vdt: to=<mail@gmail.com>, relay=aspmx.l.google.com[1.123.123.123]:25, delay=3.3, delays=0.13/0.08/1.6/1.5, dsn=5.7.1, status=bounced (host aspmx.l.google.com[71.123.123.123] said: 550-5.7.1 [1.123.123.123] The IP you're using to send mail is not authorized to 550-5.7.1 send email directly to our servers. Please use the SMTP relay at your 550-5.7.1 service provider instead. For more information, go to 550 5.7.1  https://support.google.com/mail/?p=NotAuthorizedError d2e1a72fcca58-715e57a0f50si1104d2710b3a.328 - gsmtp (in reply to end of DATA command))

Sep  2 14:20:09 redmail postfix/cleanup[1093679]: 4Wy9rTs58Rpz8vgs: message-id=<4Wy9rT58Rpz8vgs@redmail.domain.net>
Sep  2 14:20:09 redmail postfix/bounce[1093716]: 4Wy9rQ2dx2z8vdt: sender non-delivery notification: 4Wy9rT58Rpz8vgs
Sep  2 14:20:09 redmail postfix/qmgr[2337]: 4Wy9rT58Rpz8vgs: from=<>, size=4649, nrcpt=1 (queue active)
Sep  2 14:20:09 redmail postfix/qmgr[2337]: 4Wy9rQ2dx2z8vdt: removed
Sep  2 14:20:09 redmail postfix/pipe[1093717]: 4Wy9rT58Rpz8vgs: to=<user@admin.domain.net>, relay=dovecot, delay=0.17, delays=0.04/0.01/0/0.12, dsn=2.0.0, status=sent (delivered via dovecot service)
Sep  2 14:20:09 redmail postfix/qmgr[2337]: 4Wy9rT58Rpz8vgs: removed

In mail inbox:
 Undelivered Mail Returned to Sender 
 
 This is the mail system at host redmail.domain.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<[mail@domian.com](mailto:mail@domian.com)>: host aspmx.l.google.com[7.122.123.123]
    said: 2550-5.7.1 [102.242.2.1] The IP you're using to send mail is not
    authorized to 550-5.7.1 send email directly to our servers. Please use the
    SMTP relay at your 550-5.7.1 service provider instead. For more
    information, go to 550 5.7.1
    https://support.google.com/mail/?p=NotAuthorizedError
    d2e1a72fcca58-715e57a0f50si1s1042710b3a.328 - gsmtp (in reply to end of DATA
    command)
Reporting-MTA: dns; redmail.domain.net

**Comment by iredmail** [comment]
Did you ever click the link in bounce message to understand why it happened?

**Comment by osizadmin** [comment]
Yes, its showing below:

'The IP you're using to send email is not authorized...'
Troubleshoot delivery issues with Postmaster Tools
[Gmail Postmaster Tools](https://support.google.com/mail/answer/6227174) provides senders with metrics on parameters such as reputation, spam rate, feedback loop, etc. It can help you prevent your emails from being blocked or sent to spam by Gmail.

In order to prevent spam, Gmail refuses mail from IP addresses that are not authorized to send mail. The determination of whether or not an IP address is authorized to send mail is made by the ISP that provides you with the IP address. This list typically contains consumer IP ranges offered for dialup, DSL, or other broadband access.

What can I do to fix this?
Your ISP may provide SMTP relays which will accept mail from your IP, and these servers should be authorized to send mail. Some ISPs may provide a way to get an IP that is authorized, either by upgrading to business class service or static IP service. You should reach out to your ISP to see what options are available.

Another alternative is to send mail through your own domain’s servers, either by configuring them to allow relay from your IP address, or by using MSA (mail submission agent). Learn how to use Gmail to [send mail from a different address](https://support.google.com/mail/answer/22370).

Please note that we are unable to allowlist IP addresses or otherwise make exceptions.
