### ISSUE TITLE
TLS is required, but was not offered by host 127.0.0.1[127.0.0.1])

### ISSUE THREAD

**Issue by osizadmin** [iredmail/iRedMail#265]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

iRedMail version (check /etc/iredmail-release): 1.7.0 PGSQL edition
Deployed with iRedMail Easy or the downloadable installer?
Linux/BSD distribution name and version: Ubuntu 22.04.4 LTS
Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL
Web server (Apache or Nginx):Nginx
Manage mail accounts with iRedAdmin-Pro? roundcube webmail
[IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: connect from localhost[127.0.0.1]
Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: discarding EHLO keywords: CHUNKING
Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: discarding EHLO keywords: CHUNKING
Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: 4WzPS31N13z8slH: client=localhost[127.0.0.1], sasl_method=LOGIN, sasl_username=demo@admin.domain.com
Sep  4 14:06:43 redmail postfix/cleanup[1395638]: 4WzPS31N13z8slH: message-id=<624670b8a417d99c50d76ce0ace5343e@admin.domain.com>
Sep  4 14:06:43 redmail postfix/qmgr[1384135]: 4WzPS31N13z8slH: from=<demo@admin.domain.com>, size=798, nrcpt=1 (queue active)
Sep  4 14:06:43 redmail roundcube: <99ak7098> User demo@admin.domain.com [192.168.1.1]; Message <624670b8a417d99c50d76ce0ace5343e@admin.domain.com> for mail@domain.com;; 250: 2.0.0 Ok: queued as 4WzPS31N13z8slH
Sep  4 14:06:43 redmail postfix/submission/smtpd[1395622]: disconnect from localhost[127.0.0.1] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Sep  4 14:06:43 redmail postfix/amavis/smtp[1395643]: 4WzPS31N13z8slH: to=<mail@domain.com;>, relay=127.0.0.1[127.0.0.1]:10026, delay=0.09, delays=0.09/0/0/0, dsn=4.7.4, status=deferred (TLS is required, but was not offered by host 127.0.0.1[127.0.0.1])

Please let me know to resolve this issue.

**Comment by iredmail** [comment]
Did you modify any Postfix config after initial iRedMail installation?
