### ISSUE TITLE
Docker: /iredadmin does not work -> 404 Not Found

### ISSUE THREAD

**Issue by TitanFighter** [iredmail/iRedMail#27]
Any ideas?

Version: the latest (which was updated 33 mins ago).

**Comment by iredmail** [comment]
It’s /iredadmin, not /iredmail.

**Comment by iredmail** [comment]
- Do you have env variable “USE_IREDADMIN=NO” somewhere?

- does supervisord launch iredadmin?

**Comment by TitanFighter** [comment]
> Do you have env variable “USE_IREDADMIN=NO” somewhere?

No

> does supervisord launch iredadmin?

Yes

**Comment by iredmail** [comment]
Do you have any file with “iredadmin” in file name under /etc/nginx/sites-conf.d/default-ssl/?

**Comment by TitanFighter** [comment]
> Do you have any file with “iredadmin” in file name under /etc/nginx/sites-conf.d/default-ssl/?

Yes. `90-iredadmin.conf`

**Comment by TitanFighter** [comment]
`include /opt/iredmail/custom/nginx/webapps/iredadmin?.conf`

I do not have /opt/iredmail/custom/**nginx**/ folder

**Comment by iredmail** [comment]
With 90-iredadmin.conf, /iredadmin should work as expected. 

Try to turn on debug mode in Nginx and check which (nginx) location rule Is used.

**Comment by iredmail** [comment]
> `include /opt/iredmail/custom/nginx/webapps/iredadmin?.conf`
> 
> I do not have /opt/iredmail/custom/**nginx**/ folder

Nginx ignores it if doesn’t exist.

**Comment by TitanFighter** [comment]
`nginx -s reload` fixed this issue and I can not reproduce it anymore - I removed container in order to rebuild it and /iredadmin still works. I will try with a fresh server to be sure that it 100% works and if this issue comes back - I will inform you.
