### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by eiffy-zuo** [iredmail/iRedMail#270]
* - Roundcube webmail: https://mail.waypay.asia/mail/
* - SOGo groupware: https://mail.waypay.asia/SOGo/
* - netdata (monitor): https://mail.waypay.asia/netdata/
* - Web admin panel (iRedAdmin): https://mail.waypay.asia/iredadmin/

When I open the https://mail.waypay.asia/iredadmin/ , it prompts 502 Bad Gateway
 My other pages can be opened normally

**Comment by iredmail** [comment]
- Which linux distribution and release are you running?
- Is `iredadmin` service running?
