### ISSUE TITLE
My mail server domain name can be resolved, but I cannot receive or send mails

### ISSUE THREAD

**Issue by eiffy-zuo** [iredmail/iRedMail#271]
My mail server domain name can be resolved, but I cannot receive or send mails. Gmail reports an error message saying that it cannot find the domain name.
This is my resolution record. Can someone help me take a look?
![1ba07a796defcbcba37c3aeb448693d](https://github.com/user-attachments/assets/20a62b19-096e-4b71-8217-654b77366c14)
![39f3fba39976f61161fdaa15a30469d](https://github.com/user-attachments/assets/652117f1-cb6e-4e5a-bfa0-83c0a3693fa2)

**Comment by iredmail** [comment]
没看出来吗？域名写错了，`.aisa` 结尾，不是 `.asia`。

**Comment by eiffy-zuo** [comment]
[image: image.png]Yes, sorry for my carelessness. I redeployed, but now I
have a new problem. My server can receive mail but cannot send it.
