### ISSUE TITLE
BUG: py311-cheroot needed for iredadmin.py

### ISSUE THREAD

**Issue by bozhinov** [iredmail/iRedMail#273]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.7.1
- Deployed with iRedMail Easy or the downloadable installer? No
- Linux/BSD distribution name and version: 14.2
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

iredamin.py said it module was missing so I installed it from pkg - py311-cheroot

**Comment by iredmail** [comment]
iRedAdmin is designed to be launched by uwsgi or other wsgi server, not ran directly with command like "python3 iredadmin.py", hence we didn't install cheroot as dependency. 

Don't run iredadmin by "python3 iredadmin.py" in production server.

**Comment by bozhinov** [comment]
I get internal server error so I did some digging
but that's on me. my jail has no rc.conf so I had to start services manually and I probably messed the order

**Comment by iredmail** [comment]
Do you mean iRedMail installer doesn't update rc.conf to start iredadmin automatically? Or iredadmin failed to start?

**Comment by bozhinov** [comment]
failed to start but I ve created a separate issue for it.
lets leave this one be cause I m ashamed of it
