### ISSUE TITLE
BUG: Freshclam does not work without ca_root_nss

### ISSUE THREAD

**Issue by bozhinov** [iredmail/iRedMail#274]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.7.1
- Deployed with iRedMail Easy or the downloadable installer? No
- Linux/BSD distribution name and version:  FreeBSD 14.2
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

ClamAV needs freshclam first and that one fails because "certificate is not OK"
Once I installed ca_root_nss it was OK

**Comment by bozhinov** [comment]
I see this has been considered in the core script

**Comment by iredmail** [comment]
ca_root_nss is installed by iRedMail installer.
What's the full and original error message reported by freshclam?
