### ISSUE TITLE
iRedMail needs COMPAT_FREEBSD11 on 14.2

### ISSUE THREAD

**Issue by bozhinov** [iredmail/iRedMail#275]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.7.1
- Deployed with iRedMail Easy or the downloadable installer? No
- Linux/BSD distribution name and version: FreeBSD 14.2
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Ran into that dependency during installation of one of the ports
had to recompile the kernel
but that's on me for removing it in the first place as it comes enabled by default.

**Comment by iredmail** [comment]
Then it's not an iRedMail issue. :)

**Comment by bozhinov** [comment]
I was thinking maybe add it to the prerequisites
