### ISSUE TITLE
Internal Server Error after fresh install on FreeBSD 14.2

### ISSUE THREAD

**Issue by bozhinov** [iredmail/iRedMail#276]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.7.1
- Deployed with iRedMail Easy or the downloadable installer? No
- Linux/BSD distribution name and version: FreeBSD 14.2
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Fresh installed thick jail 14.2 and nothing but iRedMailAdmin as a feature enabled

I get Internal Server error while trying to access it
I suspect this is the problem

/var/log/message:
Dec 21 07:47:45 mail newsyslog[71401]: logfile first created
Dec 21 07:47:45 mail syslogd: kernel boot file is /boot/kernel/kernel
Dec 21 07:47:48 mail iredapd Error while creating SQL connection: RuntimeError("OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.")
Dec 21 07:47:48 mail syslogd: last message repeated 1 times
Dec 21 07:47:48 mail iredapd Error while loading plugin 'reject_sender_login_mismatch': RuntimeError("OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.")
Dec 21 07:47:48 mail iredapd Error while loading plugin 'greylisting': RuntimeError("OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.")
Dec 21 07:48:18 mail php-fpm[5980]: [NOTICE] configuration file /usr/local/etc/php-fpm.conf test is successful
Dec 21 07:48:18 mail php-fpm[5980]: 
Dec 21 07:48:18 mail php-fpm[6458]: [NOTICE] fpm is running, pid 6458
Dec 21 07:48:18 mail php-fpm[6458]: [NOTICE] ready to handle connections

**Comment by iredmail** [comment]
Have to update `/etc/make.conf` and set `ssl=openssl34` (or other openssl version you prefer), then rebuild all packages which relies on openssl. Next iRedMail release will use `ssl=openssl34` to fix this issue.

**Comment by iredmail** [comment]
Have to rebuild security/openssl (or security/openssl3X) with option `LEGACY` enabled.

Make sure option `LEGACY` is enabled:
```
cd /usr/ports/security/openssl/
make config
```
Or, modify it in `/var/db/ports/security_openssl/options` directly:
```
OPTIONS_FILE_SET+=LEGACY
```

Then rebuild and reinstall it.
