### ISSUE TITLE
My email server can receive but not send emails

### ISSUE THREAD

**Issue by eiffy-zuo** [iredmail/iRedMail#277]
My email server can receive but not send emails
![be2bde1ef9bc19d4fc5d2b2417eaa37](https://github.com/user-attachments/assets/17d06886-f3ba-4616-b4e9-90060e1e05ed)

**Comment by eiffy-zuo** [comment]
![1](https://github.com/user-attachments/assets/9918a2a2-5553-4f1c-b500-4fda5f38f908)
![2](https://github.com/user-attachments/assets/371a8c06-2981-4246-bd5f-81b12fc953dc)
![3](https://github.com/user-attachments/assets/dff38fe6-2675-4d0f-9238-5c857ad7d731)
I tried several mailboxes and they all said the connection timed out.

**Comment by iredmail** [comment]
Seems your ISP block port 25. Please contact your isp to figure it out.
