### ISSUE TITLE
hang up all system

### ISSUE THREAD

**Issue by tonychagas** [iredmail/iRedMail#28]
update the centeos in las days, the email server does not works. seeu actualizations above:
[tony.txt](https://github.com/iredmail/iRedMail/files/4562589/tony.txt)

**Comment by iredmail** [comment]
- are you updating packages or OS?
- what does “not work” mean?

**Comment by tonychagas** [comment]
in the file "tony.txt" is the list of packages that "yum update" intends to update ... If I update, the email server stops sending email, receiving, etc.

Testing with "postfis check" everything is ok, but I can't receive any email.

The list of packages is postfix, however, I think it could not be updated because there is an exclusion rule in the repository directory

**Comment by iredmail** [comment]
Any related error in Postfix/Dovecot log files?

**Comment by tonychagas** [comment]
after update , including postfix upate:

2:postfix-2.10.1-9.el7.x86_64

log text:

May  3 16:23:48 mail postfix/postfix-script[3542]: starting the Postfix mail system
May  3 16:23:48 mail postfix/master[3544]: daemon started -- version 2.10.1, configuration /etc/postfix
May  3 16:25:57 mail postfix/postscreen[3704]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
May  3 16:25:58 mail postfix/master[3544]: warning: process /usr/libexec/postfix/postscreen pid 3704 exit status 1
May  3 16:25:58 mail postfix/master[3544]: warning: /usr/libexec/postfix/postscreen: bad command startup -- throttling
May  3 16:26:58 mail postfix/postscreen[3735]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
May  3 16:26:59 mail postfix/master[3544]: warning: process /usr/libexec/postfix/postscreen pid 3735 exit status 1
May  3 16:26:59 mail postfix/master[3544]: warning: /usr/libexec/postfix/postscreen: bad command startup -- throttling
May  3 16:27:59 mail postfix/postscreen[3796]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
May  3 16:28:00 mail postfix/master[3544]: warning: process /usr/libexec/postfix/postscreen pid 3796 exit status 1
May  3 16:28:00 mail postfix/master[3544]: warning: /usr/libexec/postfix/postscreen: bad command startup -- throttling
May  3 16:29:00 mail postfix/postscreen[3858]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
May  3 16:29:01 mail postfix/master[3544]: warning: process /usr/libexec/postfix/postscreen pid 3858 exit status 1
May  3 16:29:01 mail postfix/master[3544]: warning: /usr/libexec/postfix/postscreen: bad command startup -- throttling
May  3 16:29:51 mail clamd[2555]: SelfCheck: Database status OK.
May  3 16:30:01 mail postfix/postscreen[3901]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
May  3 16:30:02 mail postfix/master[3544]: warning: process /usr/libexec/postfix/postscreen pid 3901 exit status 1
May  3 16:30:02 mail postfix/master[3544]: warning: /usr/libexec/postfix/postscreen: bad command startup -- throttling

**Comment by iredmail** [comment]
> May 3 16:25:57 mail postfix/postscreen[3704]: fatal: bad numerical configuration: smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES

File `/etc/postfix/main.cf` contains an invalid line:

```
smtpd_client_connection_count_limit = 25readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
```

Please split it to 2 lines and restart postfix service:

```
smtpd_client_connection_count_limit = 25
readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
```

Note: iRedMail doesn't set `smtpd_client_connection_count_limit` in main.cf. So i don't consider this as an iRedMail bug.

**Comment by tonychagas** [comment]
iredmail install this in master.cf like this:

smtpd_client_connection_count_limit = 0
