### ISSUE TITLE
Customizing postfix config

### ISSUE THREAD

**Issue by mattmattox** [iredmail/iRedMail#31]
I'm trying to customizing /etc/postfix/main.cf to add a relay host to support Spamhero.
I have created a sidecar container to setup the sasl password and update the config but `postfix reload` does pickup the config. And `supervisorctl restart postfix` causes postfix to crash.

Also, it would be helpful if https://www.github.com/iredmail/dockerized was open to the public so people can fork it. Then create a patch and PR.

**Comment by iredmail** [comment]
> I'm trying to customizing /etc/postfix/main.cf to add a relay host to support Spamhero.
> I have created a sidecar container to setup the sasl password and update the config but `postfix reload` does pickup the config. And `supervisorctl restart postfix` causes postfix to crash.

Dockerized iRedMail follows the best practice of iRedMail Easy:
https://docs.iredmail.org/iredmail-easy.best.practice.html

> Also, it would be helpful if https://www.github.com/iredmail/dockerized was open to the public so people can fork it. Then create a patch and PR.

You get it now:
https://github.com/iredmail/dockerized
