### ISSUE TITLE
Please rename /etc/iredmail-release for OpenBSD

### ISSUE THREAD

**Issue by FollowMeDown** [iredmail/iRedMail#35]
I use OpenBSD 6.7!

If I start **neofetch** I can see information from /etc/iredmail-release and not from the system. Please rename your /etc/iredmail-release file for right **neofetch** output.

Wrong output :
```
bastion$ neofetch
             ,        ,            deface@bastion.my.box 
            /(        )`           ------------------------ 
            \ \___   / |           OS: 1.3 OPENLDAP edition. # Get professional support from iRedMail Team: http://www.iredmail.org/support.html amd64 
            /- _  `-/  '           Host: HP
           (/\/ \ \   /\           Kernel: 6.7 
           / /   | `    \          Uptime: 41 mins 
           O O   ) /    |          Packages: 380 (pkg_info) 
           `-^--'`<     '          Shell: ksh v5.2.14 99/07/13.2 
          (_.)  _  )   /           Resolution: 1920x1080 
           `.___/`    /            WM: i3 
             `-----' /             Terminal: xterm 
<----.     __ / __   \             CPU: Intel i7-6500T (4) @ 2.794GHz 
<----|====O)))==) \) /====|        GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
<----'    `--' `.__,' \            Memory: 1922MiB / 8042MiB 
             |        |
              \       /       /\                           
         ______( (_  / \______/                            
       ,'  ,-----'   |
       `--{__________)
```

**Comment by iredmail** [comment]
Great, you just caught a `neofetch` bug: It should correctly recognize the `/etc/<X>-release` file for system info.

Seems neofetch reads info from `/etc/*-release`, but `/etc/iredmail-release` happens to be sorted before `/etc/os-release`. haha.

Contact your neofetch developers to fix it please. :)

**Comment by iredmail** [comment]
I just help locate the source line:
https://github.com/dylanaraps/neofetch/blob/c8e08cd76e59aa759bda815f61a149955b61466a/neofetch#L1050

It's completely wrong to expect `/etc/*-release` stores OS related info.
