### ISSUE TITLE
Can't install using existing MySql

### ISSUE THREAD

**Issue by MESWEB** [iredmail/iRedMail#36]
I can't install v1.0.
Debian 10 with apache2 and existing MySql 
Command:
`USE_EXISTING_MYSQL='YES'     MYSQL_SERVER_ADDRESS='localhost'     MYSQL_SERVER_PORT='3306'     MYSQL_ROOT_USER='root'     MYSQL_ROOT_PASSWD=''     MYSQL_GRANT_HOST='localhost'     bash iRedMail.sh`

**Comment by iredmail** [comment]
- Please use the latest iRedMail release, iRedMail-1.2.1.
- No support for NEW installation with old iRedMail releases.

**Comment by MESWEB** [comment]
OK. I tried with newest version 1.2.1 without success. How I can select MySQL where is no option during installation?

**Comment by iredmail** [comment]
Select `MariaDB` for MySQL.
