### ISSUE TITLE
Ubuntu 16.04: latest version not supported and old version throws error to upgrade to new

### ISSUE THREAD

**Issue by Wrufesh** [iredmail/iRedMail#38]
Hello,
I was trying to install iRedMail on Ubuntu 16.04.
With latest version, I get an error like it is not supported to Ubuntu 16.04.
It supports Ubuntu 18.04.

I found that some people had installed v0.9.7 on Ubuntu 16.04 bak in 2018.
I tried to install it getting the source from github.
Now I get the error like:
```
[ INFO ] Checking new version of iRedMail ...

<< ERROR >> Your iRedMail version (0.9.7) is out of date, please
<< ERROR >> download the latest version and try again:
<< ERROR >> http://www.iredmail.org/download.html

```

Is there any workaround?

**Comment by iredmail** [comment]
Ubuntu 16.04 is too old for a NEW mail server, please use 18.04 instead with the latest iRedMail-1.2.1.

Or, wait for some more days for new iRedMail release with Ubuntu 20.04 support.

**Comment by Wrufesh** [comment]
Shouldn't I be able to install the old version(v0.9.7)?
I only have Ubuntu 16.04.

**Comment by iredmail** [comment]
> Shouldn't I be able to install the old version(v0.9.7)?

We don’t support new installation with old iRedMail release. And don’t try it please. 


> I only have Ubuntu 16.04.

Maybe you should contact your VPS vendor or some other kind of vendor to offer new Ubuntu release, 16.04 is 4+ years old, 18.04 is 2+ years old.
