### ISSUE TITLE
forget password form for roundcube user

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#39]
Mail users want to have "Forget password form".
I found https://github.com/jerryrelmore/roundcube-forgot_password. 

Could You implement it in iredmail?

**Comment by interduo** [comment]
It doesn't work well.
Today I almost write my own. 

@iredmail would You like to do code review and get it to iredmail package?

**Comment by iredmail** [comment]
hi @interduo 

We have no plan to integrate this plugin shortly.
Feel free to share your plugin (github repo URL) in our forum: https://forum.iredmail.org/
