### ISSUE TITLE
internal server error after logout iredadmin

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#4]
Hello
I just install fresh iRedMail 1.0 stable on Debian 10.
After login to: https://example.com/iredadmin
and press logout i get on screen:
"internal server error"

In logs i get:
X.X.X.X - - [21/Dec/2019:19:38:40 +0100] "POST /iredadmin/login HTTP/1.1" 500 32 "https://example.com/iredadmin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

Best Regards
TaKeN

**Comment by iredmail** [comment]
Seems a bug of iRedAdmin open source edition. Another user reported this in forum days ago, I will try to reproduce and fix it later. 

Thanks for the feedback.
