### ISSUE TITLE
misc/netdata-v1.23.0.gz.run: No such file or directory

### ISSUE THREAD

**Issue by Sebka97** [iredmail/iRedMail#41]
It seems like the netdata link is broken

Reading package lists... Done
[ INFO ] Fetching source tarballs ...
[ INFO ] + 1 of 6: https://dl.iredmail.org/yum/misc/iRedAdmin-1.0.tar.bz2
[ INFO ] + 2 of 6: https://dl.iredmail.org/yum/misc/mlmmjadmin-3.0.tar.gz
[ INFO ] + 3 of 6: https://dl.iredmail.org/yum/misc/iRedAPD-4.0.tar.gz
[ INFO ] + 4 of 6: https://dl.iredmail.org/yum/misc/netdata-v1.23.0.gz.run
[ INFO ] + 5 of 6: https://dl.iredmail.org/yum/misc/roundc … ete.tar.gz
[ INFO ] + 6 of 6: https://dl.iredmail.org/yum/misc/webpy-0.51.tar.gz
[ INFO ] Validate downloaded source tarballs ...
misc/iRedAdmin-1.0.tar.bz2: OK
misc/mlmmjadmin-3.0.tar.gz: OK
misc/iRedAPD-4.0.tar.gz: OK
sha256sum: misc/netdata-v1.23.0.gz.run: No such file or directory
misc/netdata-v1.23.0.gz.run: FAILED open or read
misc/roundcubemail-1.4.6-complete.tar.gz: OK
misc/webpy-0.51.tar.gz: OK
sha256sum: WARNING: 1 listed file could not be read
        [ FAILED ]
<< ERROR >> Package verification failed. Script exit ...

**Comment by iredmail** [comment]
Fixed. Thanks for the feedback.

btw, netdata-v1.23.0.gz.run is also available from netdata github repo:
https://github.com/netdata/netdata/releases
