### ISSUE TITLE
Error installation "sha256sum: WARNING: 1 listed file could not be read"

### ISSUE THREAD

**Issue by mckenziearts** [iredmail/iRedMail#43]
Unable to find to `misc/iRedAPD-4.1.tar.gz` archive

On this release the iRedAPD is 4.0 but during installation iRedMail tries to download version 4.1.

<img width="838" alt="1" src="https://user-images.githubusercontent.com/14105989/86083119-480c2080-ba91-11ea-936d-06a44662c759.png">

But the version 4.1 don't exist here

<img width="475" alt="Untitled" src="https://user-images.githubusercontent.com/14105989/86083206-80136380-ba91-11ea-8540-56125b54d12f.png">

Error Screen

<img width="718" alt="2" src="https://user-images.githubusercontent.com/14105989/86083253-9de0c880-ba91-11ea-9e3e-b04607e74b54.png">

**Comment by iredmail** [comment]
Fixed. Sorry about this trouble.
