### ISSUE TITLE
can`t login webmail

### ISSUE THREAD

**Issue by thisleo** [iredmail/iRedMail#45]
Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 43: Unknown setting: ssl_min_protocol

**Comment by iredmail** [comment]
Which linux distribution and release are you running?

**Comment by thisleo** [comment]
> Which linux distribution and release are you running?

CentOS Linux release 7.8.2003
Dovecot Version: 2.2.36.4

**Comment by iredmail** [comment]
CentoS 7 should not have `ssl_min_protocol` parameter, Did you add this parameter manually, or it's created by iRedMail installer (which is not expected)?

**Comment by thisleo** [comment]
> CentoS 7 should not have `ssl_min_protocol` parameter, Did you add this parameter manually, or it's created by iRedMail installer (which is not expected)?

it's created by iRedMail installer, i did not edit it

**Comment by iredmail** [comment]
Confirmed it's a bug and confirmed moment ago:
https://github.com/iredmail/iRedMail/commit/4b19b99b15857d5901fd4238420d7d4c0cf76061

If this is a server not in production yet, it's recommended to re-install OS then re-install iRedMail-1.3 (repacked already).
