### ISSUE TITLE
1 listed file could not be read

### ISSUE THREAD

**Issue by chaemoong** [iredmail/iRedMail#46]
[ INFO ] Fetching source tarballs ...
[ INFO ] + 1 of 6: https://dl.iredmail.org/yum/misc/iRedAdmin-1.0.tar.bz2
[ INFO ] + 2 of 6: https://dl.iredmail.org/yum/misc/mlmmjadmin-3.0.tar.gz
[ INFO ] + 3 of 6: https://dl.iredmail.org/yum/misc/iRedAPD-4.1.tar.gz
[ INFO ] + 4 of 6: https://dl.iredmail.org/yum/misc/netdata-v1.23.1.gz.run
[ INFO ] + 5 of 6: https://dl.iredmail.org/yum/misc/roundcubemail-1.4.7-complete.tar.gz
[ INFO ] + 6 of 6: https://dl.iredmail.org/yum/misc/webpy-0.51.tar.gz
[ INFO ] Validate downloaded source tarballs ...
misc/iRedAdmin-1.0.tar.bz2: OK
misc/mlmmjadmin-3.0.tar.gz: OK
misc/iRedAPD-4.1.tar.gz: OK
misc/netdata-v1.23.1.gz.run: OK
sha256sum: misc/roundcubemail-1.4.7-complete.tar.gz: No such file or directory
misc/roundcubemail-1.4.7-complete.tar.gz: FAILED open or read
misc/webpy-0.51.tar.gz: OK
sha256sum: WARNING: 1 listed file could not be read
        [ FAILED ]
<< ERROR >> Package verification failed. Script exit ...
https://dl.iredmail.org/yum/misc/roundcubemail-1.4.7-complete.tar.gz == 404 Not Found

**Comment by iredmail** [comment]
Fixed. Thanks for the feedback.
Didn't expect someone to test the development edition so soon. :)
