### ISSUE TITLE
API issue creating mailbox

### ISSUE THREAD

**Issue by hellvetika** [iredmail/iRedMail#48]
Hi !

We bought iRedMail Pro and I have an issue when creating user mailboxes and when the password does no contains a special character. I got this result from API:

`string(39) "{"_success": false, "_msg": "PW_EMPTY"}"`

(User password who contains a special character are ok).

I disabled server wide password requirements, because we are crating user from another database where password are already checked as strong.

Is this a bug or do I have to set some parameters to ignore password strenght when set by API ?

Thank you for your help !

**Comment by iredmail** [comment]
> We bought iRedMail Pro

Thanks for the purchase. :)

> I got this result from API:
> 
> `string(39) "{"_success": false, "_msg": "PW_EMPTY"}"`

- Is the `string(39)` printed by your own script?
- If the request was rejected due to missing special char, i expect the error message to be `PW_NO_SPECIAL_CHAR`, not `PW_EMPTY` (which means the password is empty).

Could you please show me some info:

- The API endpoint which triggered this error. e.g. `https://<server>/iredadmin/api/...` (just the `/api/...` part is ok too)
- The sample code used to send http post to trigger the error.

> I disabled server wide password requirements, because we are crating user from another database where password are already checked as strong.

Did you get above error AFTER disabled server wide password requirements? Or the requirements are still enabled?

**Comment by hellvetika** [comment]
Wow, very quick answer :)

**Endpoint: /api/user/<user@mydomain>**

I use php-curl to query the API, this is my PHP function:

```
function createMailAccount($user){
	$posts = [
		'name'		=> $user['nom'].''.$user['prenom'],
		'password' 		=> <our existing user plain password>,
		'quota'	=> $user['mail_quota'],
		'aliases'	=> $user['completmail'].'@mydomain.ch',
	];

	//echo json_encode($posts);

	$ch = curl_init('https://mx.mydomain.ch/iredadmin/api/user/'.$user['username'].'@mydomain.ch');

	$headr = array();
	$headr[] = 'Content-type: application/json';

	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($posts));
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_HTTPHEADER,$headr);
	curl_setopt($ch, CURLOPT_COOKIEFILE, '/path/to/the/cookie.txt');

	// execute!
	$response = curl_exec($ch);

	// close the connection, release resources used
	curl_close($ch);

	var_dump($response);
}
```

> Did you get above error AFTER disabled server wide password requirements? Or the requirements are still enabled?
I tested twice, but they are actually disabled

**Comment by iredmail** [comment]
Which version of iRedAdmin-Pro are you running?

**Comment by hellvetika** [comment]
> Which version of iRedAdmin-Pro are you running?


The latest: SQL-4.4

**Comment by iredmail** [comment]
Seems i can not reproduce your issue. Here's my shell script used for testing, with default password requirements enabled.

```
#!/usr/bin/env bash

url='http://rc8:8080/api'

admin='postmaster@a.io'
password='my-password'

domain='a.io'

#
# Login
#
curl -X POST -c cookie.txt -d "username=${admin}&password=${password}" ${url}/login
curl -X POST -b cookie.txt --data "name=testname&password=12Password&quota=1024" "${url}/user/3@$domain"
rm -f cookie.txt
```

I got this:

```
{"_success": true}    # Login
{"_success": false, "_msg": "PW_NO_SPECIAL_CHAR"}    # Create new user
```

**Comment by hellvetika** [comment]
Ok ! I'll keep on testing because I'm obliged to use PHP but I'll keep you informed if I find a solution. :)

**Comment by iredmail** [comment]
ok. feel free to reopen this issue or create a new one if you have same / new issue.
