### ISSUE TITLE
/root/iRedMail-1.3.1/tools/create_mail_user_SQL.sh doesnt use "Default quota of new user"

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#49]
"Default quota of new user" is not used in ./iRedMail-1.3.1/tools/create_mail_user_SQL.sh set in iredadminpro panel

**Comment by iredmail** [comment]
`create_mail_user_SQL.sh` runs SQL commands directly, it doesn't check the "default quota of new user" or "max quota". Please use iRedAdmin-Pro instead, it also offers RESTful API interface if you need to create mail accounts on command line or in script.
FYI: https://docs.iredmail.org/iredadmin-pro.restful.api.html

**Comment by interduo** [comment]
And also if You got another "storagebasedir" than /var/vmail ... it's not used in query.

Maybe in DB there should be set DEFAULT in DB SCHEME as variable from installer?
If You use the SQL generated - You cannot do anything after login to roundcube.

**Comment by iredmail** [comment]
> And also if You got another "storagebasedir" than /var/vmail ... it's not used in query.

What do you mean "another storagebasedir"?

**Comment by interduo** [comment]
default is /var/vmail,
i use /vmail <--- this is another/not default

**Comment by iredmail** [comment]
- If you use script `create_mail_user_SQL.sh` to create new user, you should update `create_mail_user_SQL.sh` to use correct storagebasedir.
- During iRedMail installation, iRedAdmin(-Pro) was configured to use the storage base directory you input during the installation wizard, so it's not a problem. If you want to change the directory, please update iRedAdmin(-Pro) config file.
