### ISSUE TITLE
Windows WSL Error - Debian Bullseye 

### ISSUE THREAD

**Issue by knoxcard2** [iredmail/iRedMail#5]
```
lsb_release -a
```

```
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye
```
```
root@LAPTOP-21F611179:/usr/src/iredmail# bash iRedMail.sh
```
```
********* ERROR *********
Release version of the operating system on this server is unsupported by
iRedMail, please access below link to get the latest iRedMail and a list
of supported Linux/BSD distributions and release versions.

http://www.iredmail.org/download.html

*************************
```

**Comment by iredmail** [comment]
What’s “Windows WSL”?
For Debian OS, only Debian 9 and 10 are tested, not “bullseye”.

**Comment by knoxcard2** [comment]
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
WSL allows you to run Linux on Windows, it works surprisingly well!

But darn, I can't downgrade my linux from bullseye.
Guess I will try to run a windows based mail server and have my nodeJS linux environment communicate via port 25.  Argghhh, what a mess.

**Comment by knoxcard2** [comment]
Can I add an override to basically run the same routines of "Buster" for "Bullseye"?
Bet it would work!

Just don't know what files to edit.

**Comment by iredmail** [comment]
> Can I add an override to basically run the same routines of "Buster" for "Bullseye"?
> Bet it would work!

Don’t try this. We didn’t test Debian testing at all, you won’t get a working iRedMail server on Debian testing. 

Please try one of supported Linux/BSD distribution and release:
https://www.iredmail.org/download.html
