### ISSUE TITLE
back to page after submit

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#51]
**form:** 
iredadmin.domain.pl/users/domain.pl 
(List of user domain)

**do:**
after submitting disabling account on 3 page it takes back to first page

**should be done:**
afer submitting disabling account on any page it should take back to this page

**Comment by iredmail** [comment]
I will try to reproduce and fix it shortly. Thanks for the feedback.

**Comment by iredmail** [comment]
Confirmed it's a bug of iRedAdmin-Pro and has been fixed moment ago, the fix will be available in next release.
Thank you very much for the feedback. :)
