### ISSUE TITLE
spammassassin - needs to be upgraded

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#52]
Everyday I've got mail with:
```
Cron <root@poczta>   [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean

/etc/cron.daily/spamassassin:
config: warning: description exists for non-existent rule USER_IN_WELCOMELIST_TO

channel: lint check of update failed, channel failed
sa-update failed for unknown reasons
```

Debian 10, almost fresh install

**Comment by iredmail** [comment]
- Package `php-common` installs cron job `/etc/cron.d/php`, it runs everyday and generates some output which is sent as daily email to root user.
- SpamAssassin upstream mirror site may have some issue, it's safe to ignore and please keep trying (it will update automatically).

**Comment by interduo** [comment]
`https://www.mail-archive.com/users@spamassassin.apache.org/msg106313.html`
