### ISSUE TITLE
/usr/lib/php/sessionclean: 51: /usr/lib/php/sessionclean: sort: Permission denied

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#53]
Everyday I get those email:

```
Cron <root@poczta>   [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean

/usr/lib/php/sessionclean: 51: /usr/lib/php/sessionclean: sort: Permission denied
```
Debian Buster almost fresh install

**Comment by iredmail** [comment]
File `/usr/lib/php/sessionclean` should have permission 0755 with default installation, please check and fix it on your server.

**Comment by interduo** [comment]
This is other problem than permissions:
```
# ls -la /usr/lib/php/sessionclean
-rwxr-xr-x 1 root root 2922 gru 17  2018 /usr/lib/php/sessionclean
```

Look that this is a problem in this script - look whats after sort

**Comment by iredmail** [comment]
I think you just found a bug of the script (offered by package `php-common`). It's better report to Debian mailing list or its bug tracker. :)
