### ISSUE TITLE
please consider to add http2 support in nginx/apache as default option

### ISSUE THREAD

**Issue by changchichung** [iredmail/iRedMail#55]
I have no idea how to update apache configurations

but in nginx , just edit /etc/nginx/sites-enabled/00-default-ssl.conf
and add http2 at the end of line 6.

like this

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl;
    server_name _;
```
and your web service will have http2 support .

![](https://i.imgur.com/zE3dTHX.png)

**Comment by iredmail** [comment]
Implemented locally and will be available in next release. Close issue first. :)
