### ISSUE TITLE
More description fields for accounts

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#57]
There is only one field called user/employeeid in account list.

Please add "alternative account" and "description" fields in iredadmin. That costs none, efficienty is high. Especialy when exporting accounts for externat systems.

**Comment by iredmail** [comment]
- What's "alternative account"?
- About "description", do you mean some "comment" text?
- What kind of info do you want to store in "alternative account" and "description"?
- Export to which external systems? Do you need it now? How does it affect the export?

**Comment by interduo** [comment]
Alternative account - - an account used for sending request to when user lost his password, Alternative account is an email address. (I write a form whitch I will put on github in few days)

Desctiption - type text - simply text comment (sometimes there are two workers with the same name and surename, description would help to distinguish),

I don't need it now.
I just want to check everyday if some account (doesn't) need to be disabled/enabled/deleted/autoresponder_configured depending on some circumstances.

**Comment by iredmail** [comment]
No plan for these 2 features shortly, sorry.
