### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by CraftedCat** [iredmail/iRedMail#59]
AUTO_USE_EXISTING_CONFIG_FILE=y \
    AUTO_INSTALL_WITHOUT_CONFIRM=y \
    AUTO_CLEANUP_REMOVE_SENDMAIL=y \
    AUTO_CLEANUP_REMOVE_MOD_PYTHON=y \
    AUTO_CLEANUP_REPLACE_FIREWALL_RULES=y \
    AUTO_CLEANUP_RESTART_IPTABLES=y \
    AUTO_CLEANUP_REPLACE_MYSQL_CONFIG=y \
    AUTO_CLEANUP_RESTART_POSTFIX=n \
    bash iRedMail.sh

Not working with last version, promt in....
< Question > Restart firewall now (with ssh ports: 22)? [y|N]

**Comment by iredmail** [comment]
Replace your `AUTO_CLEANUP_RESTART_IPTABLES` by `AUTO_CLEANUP_RESTART_FIREWALL`.
It's described on our website: https://docs.iredmail.org/unattended.iredmail.installation.html
