### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by CraftedCat** [iredmail/iRedMail#60]
[ INFO ] Configure SOGo Groupware (Webmail, Calendar, Address Book, ActiveSync).
[ INFO ] Configure Fail2ban (authentication failure monitor).
**ERROR 1133 (28000) at line 5: Can't find any matching row in the user table**
[ INFO ] Configure netdata (system and application monitor).

**Comment by iredmail** [comment]
Which iRedMail release are you running?

**Comment by CraftedCat** [comment]
last, Ubuntu 18.04

and recieve mail afterfresh install ERROR 1045 (28000): Access denied for user 'fail2ban'@'localhost' (using password: NO)

**Comment by iredmail** [comment]
What does "last" mean? 1.3.1 stable release, or the latest development edition?

**Comment by CraftedCat** [comment]
1.3.1

**Comment by iredmail** [comment]
Any related log in file `runtime/install.log` under iRedMail-1.3.1 directory?

**Comment by iredmail** [comment]
Closed due to no further update.
