### ISSUE TITLE
Include rcmcarddav in default install

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#62]
What do You think about?
`https://github.com/blind-coder/rcmcarddav`

Now iredmail have not option to synchronize contacts for roundcube and thunderbird.

**Comment by iredmail** [comment]
No plan for this. Sorry. 
A better option might be z-push + sabredav.

**Comment by interduo** [comment]
You are right sabredav is better. 
What plugin to roundcube do You recommend for using with sabredav?
