### ISSUE TITLE
Creating vhost configs per mail domain

### ISSUE THREAD

**Issue by modir** [iredmail/iRedMail#64]
In order to have autodiscover working we either use the domain autodiscover.maildomain.com or work with SRV records. In the first case there is the problem that there is no SSL certificate for each autodiscover.maildomain.com domain. If iredmail would create a vhost config for each mail domain then it would get very easy to create for each domain a SSL certificate with Let's Encrypt.

So my issue is about two things:

1. Create a vhost for each (mail) domain
1. Automate the creation of certificates for each domain

**Comment by iredmail** [comment]
The solution is simpler:

- Create only one virtual host to handle "autodiscover.*" (in Nginx config file: `server_name  autodiscover.*;`), use for example `/opt/www/well_known/` as the shared directory to handle `http(s)://autodiscover.<domain>/.well-known/` requests.
- While running `certbot`, specify `-w /opt/www/well_known/` to specify the web document root.

**Comment by modir** [comment]
And the SSL certificate is then handed out for "autodiscover.*"? And how do you handle "autoconfig.*"?

**Comment by iredmail** [comment]
Instead of creating one cert for each autodiscover domain name, you can use one cert with all supported autodiscover domain.

**Comment by modir** [comment]
OK. In this case I rewrite my request.
I would like to have in iRedAdmin a button which is calling certbot with these parameters:
`certbot certonly --webroot --dry-run -w /var/www/html -d autodiscover.mydomain.com` where the -d parameter is populated with all domains configured in iredadmin.

**Comment by iredmail** [comment]
hmm, iRedAdmin(-Pro) is a web application running as `iredadmin` user, it doesn't have required privileges to run such command. What we need is a separate daemon process which serves HTTP RESTful API and listens on request like this: iRedAdmin(-Pro) sends the request to the API, then the daemon process runs `certbot` (or other commands on demand) to finish the job.

Currently what you request for is not gonna happen shortly.
