### ISSUE TITLE
Crontab backups - errors on db: sogo, sa_bayes when sogo not installed

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#66]
I choose not install sogo and I get errors on everyday backups.

```
2020-07-26 01:01:05.289 UTC [48579] postgres@sogo FATAL:  database "sogo" does not exist
2020-07-26 01:01:06.893 UTC [48629] postgres@sa_bayes FATAL:  database "sa_bayes" does not exist
```

**Comment by iredmail** [comment]
I can not reproduce this issue with `/var/vmail/backup/backup_pgsql.sh` script shipped in latest iRedMail-1.3.1.

- Which version of iRedMail are you running? Did you upgrade it from an old version?
- Which linux distribution and release are you running?

**Comment by interduo** [comment]
iRedAdmin-Pro-SQL-4.4. No.
Debian 10.

**Comment by interduo** [comment]
I just go to postgres logs and see that...

**Comment by iredmail** [comment]
- Safe to ignore and no plan to fix it.
- A possible way to fix it is: we set the backup databases dynamically during iRedMail installation, this way it knows all existing databases. But the disadvantage is: if you upgrade this backup script by downloading from GitHub, you have to edit it and list all database names. but again, no plan to  "fix" it this way.

**Comment by interduo** [comment]
Huuh, It's few minutes of coding. Clean logs is always appreciated.

**Comment by iredmail** [comment]
No plan to fix it this way. But PR (Pull Request) is always welcome. :)

**Comment by interduo** [comment]
If whole project was OpenSource....
I would push some PRs...

**Comment by iredmail** [comment]
iRedMail is full open source.

**Comment by iredmail** [comment]
> If whole project was OpenSource....
> I would push some PRs...

Maybe i should use your pattern: `If you're paid customer, i will reply your questions.` :)

**Comment by interduo** [comment]
Haha what is paid customer? We've buyed license allready...

**Comment by iredmail** [comment]
Pay for requested features / changes in iRedMail part. I'm tired of "If whole project was OpenSource...."

- iRedMail is full open source to all users.
- iRedAdmin-Pro is full open source to only paid customers, no free download without a license.
