### ISSUE TITLE
what

### ISSUE THREAD

**Issue by dem-ionz** [iredmail/iRedMail#67]
installed fresh copy from git repo. fresh install of 18.04 nothing done but apt update apt upgrade, nothing installed...

run the iRedMail.sh
install.. everything goes... choose nginx, MariaDB, default packages for iredmail... go.. works fine...

login to iredadmin works fine.. 

go to add account... works.. type the details.. user.. password... display name.. size of mailbox... add... internal server error... logs offer no clues.. what's going on?

**Comment by iredmail** [comment]
Please use the latest stable release 1.3.1: https://www.iredmail.org/download.html 

Development edition is currently broken due to the transition of moving to Python 3.
