### ISSUE TITLE
Bad PL translation in UI

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#69]
![Zrzut ekranu z 2020-08-03 14-15-26](https://user-images.githubusercontent.com/17087236/89181715-8c10aa80-d594-11ea-8788-dd969a466831.png)

There is:
"Konto jest wyłączone" (Account is turned off)

There should be:
"Konto administratora domeny" (Account is domain admin)

**Comment by iredmail** [comment]
Dear @interduo 

Sorry about this trouble. But we don't know Polish, so we have to rely on the translators.
Would you like to help fix it and probably update/fix other translation items?

FYI: https://docs.iredmail.org/translate.iredadmin.html

**Comment by interduo** [comment]
I would do this if whole project was OpenSource.

I checked:
https://github.com/iredmail/iredadmin-pro-translation/blob/master/pl_PL/LC_MESSAGES/iredadmin.po

There are more translation mistakes :( and not all strings are translated...

**Comment by interduo** [comment]
No plan for this. Sorry.
Are You interested in commercial support for that?

**Comment by iredmail** [comment]
Sure it’s ok. 

What’s your proposal? You can also mail us if you don’t want to write here: https://www.iredmail.org/support.html

**Comment by interduo** [comment]
I don't want money, I've got a proposal:
I will do the whole Polish translation correctly If You introduce roundcube <-> thunderbird addressbook synchronization in iRedMail. This is case whitch probbably You did in past. Could be sabredav + some plugin to roundcube - like You said earlier in another issue.

Deal?

**Comment by iredmail** [comment]
> I will do the whole Polish translation correctly If You introduce roundcube <-> thunderbird addressbook synchronization in iRedMail.

No plan for this. sorry.
