### ISSUE TITLE
Link to github from website and admin center

### ISSUE THREAD

**Issue by modir** [iredmail/iRedMail#70]
It would be nice if in the admin center ( /iredadmin ) and on the official website would be the links to the github pages.

**Comment by iredmail** [comment]
Download page on website has links of all iRed* repositories: https://www.iredmail.org/download.html
Quote:

> Source code: iRedMail, iRedAPD, iRedAdmin, mlmmjadmin.

About the admin center, do you mean iRedAdmin-Pro or the iRedAdmin open source edition?

**Comment by modir** [comment]
> About the admin center, do you mean iRedAdmin-Pro or the iRedAdmin open source edition?

Both

**Comment by iredmail** [comment]
I don't think it's necessary to add repository links in admin panel. Could you share your thoughts?

**Comment by modir** [comment]
At the moment you already have the following links:

> © 2013 iRedMail Project | News & Announments | Support

From my point of view the "bug tracker" link is missing. Hence the link to github. (It is about opening issues and not about the code.)

Sidenote: Your copyright should be 2020 (or 2019) and "Announments" has a typo.

**Comment by iredmail** [comment]
- The "Support" link is for "bug tracker" or tech support.
- Fixed the copyright year and typo moment ago. https://github.com/iredmail/iRedAdmin/commit/d137866cb9a2f680cb0282f2f86f2c525c0bdc99
- No plan to add links of github repos.

Thanks for the feedback. 👍
