### ISSUE TITLE
Collect logs in e.g. ELK stack

### ISSUE THREAD

**Issue by modir** [iredmail/iRedMail#72]
It would be great if there is a nice user interface for the logs. Especially larger environments would benefit from e.g ELK stack. The logs from all services/daemons could then get collected at one place and better searched through.

**Comment by iredmail** [comment]
Short answer: no plan for this right now.

- ELK is a bonus but not a must-have app stack, and better run them on another server and not on mail server itself.
- If you already have ELK or Graylog running, you can update rsyslog config file to forward all logs to ELK/Graylog.

**Comment by modir** [comment]
In this case it would at least be nice if iredmail provides its own web interface for searching through the logs.

**Comment by iredmail** [comment]
- iRedAdmin(-Pro) is an application running as system user `iredadmin`, it doesn't have privilege to read log files under `/var/log/`.
- I personally don't think it's a good idea to display full + original log lines in admin panel. it may leak some sensitive info, especially from `/var/log/syslog` or `/var/log/messages`.

I think the question should be: which information do you need from the log files?

**Comment by modir** [comment]
> iRedAdmin(-Pro) is an application running as system user iredadmin, it doesn't have privilege to read log files under /var/log/.

This is the reason why I think iRedMail would benefit from moving to a solution where the logs are collected and stored in a database (like e.g. ElasticSearch).

> I think the question should be: which information do you need from the log files?

I need one central place where each software related to email (postfix, dovecot, spam filter, etc.) sends its logs to. So that I only have one place to troubleshoot.

**Comment by iredmail** [comment]
You can update rsyslog config file to send them to your existing ELK stack.

**Comment by modir** [comment]
I do not have an ELK stack. What I want is that iRedMail provides a more modern solution regarding logging.

**Comment by iredmail** [comment]
I understand your point. It's nice to have ELK stack in your network, but it shouldn't be shipped by iRedMail.
