### ISSUE TITLE
ERROR 1071

### ISSUE THREAD

**Issue by giolong** [iredmail/iRedMail#73]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

thank you so much 

please help me, when i install Iredmail i meet some error below

ERROR 1071 (42000) at line 105 in file: '/root/iRedMail/samples/amavisd/amavisd.mysql': Specified key was too long; max key length is 767 bytes 

Thank so much

**Comment by iredmail** [comment]
Fill the basic info of your iRedMail server please.

**Comment by giolong** [comment]
thank you so much for your reply 
my server info as below

iRedMail version (check /etc/iredmail-release): iRedMail 1.3.1 
Deployed with iRedMail Easy or the downloadable installer? : downloadable installer?
Linux/BSD distribution name and version:  CentOS 7
Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL and LDAP same
Web server (Apache or Nginx): NGINX only in script ? 
Manage mail accounts with iRedAdmin-Pro? : none
[IMPORTANT] Related original log or error message is required if you're experiencing an issue.

thank you

**Comment by iredmail** [comment]
Do you have mysql/mariadb service running before iRedMail installation?

**Comment by giolong** [comment]
thank you for your reply 
|Do you have mysql/mariadb service running before iRedMail installation?

No, i actually install in new CentOS7

**Comment by iredmail** [comment]
> iRedMail version (check /etc/iredmail-release): iRedMail 1.3.1

Did you download the iRedMail-1.3.1 from our website (https://www.iredmail.org/download.html )? Or downloaded the latest master branch of this GitHub repo?

**Comment by giolong** [comment]
thank you for your reply 
actually i follow below instruction 
https://www.linuxbabe.com/mail-server/centos-7-iredmail-email-server
so i clone from your github repo with command 
git clone https://github.com/iredmail/iRedMail.git

**Comment by iredmail** [comment]
Please always follow our OFFICIAL tutorials:
https://docs.iredmail.org/#install
