### ISSUE TITLE
Download all attachements - roundcube plugin

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedMail#75]
Please add a plugin to roundcube to default iredmail installation:
http://www.tehinterweb.co.uk/roundcube/#pizipdownload

This will allow to download all attachements as a zip whitch is really appreciate function when there are many attachments.

**Comment by iredmail** [comment]
We won't add third-party Roundcube plugins in iRedMail installer, but you're free to add them after iRedMail installation.

**Comment by interduo** [comment]
Its not third part. It is installed allready but not turned on in config.

**Comment by interduo** [comment]
Maybe in installer should be dialog to turn on plugins in rc?

**Comment by interduo** [comment]
Correct name of plugins zipdownload. It requires php-zip package.

**Comment by interduo** [comment]
Thanks for enabling it. 
Why other plugins are downloaded and not enabled by default?
