### ISSUE TITLE
Install-issue

### ISSUE THREAD

**Issue by ControlByDestiny** [iredmail/iRedMail#78]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):  1.3.1
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version:  Ubuntu 20.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? yes
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.
![image](https://user-images.githubusercontent.com/28295419/90498756-4ac6f000-e17b-11ea-9616-c783bb06367f.png)
安装提示定位不到包

**Comment by iredmail** [comment]
是从官网下载的 iRedMail-1.3.1 稳定版，还是从 github 直接 clone 的版本？
请重新从官网下载再试下：https://www.iredmail.org/download.html

**Comment by ControlByDestiny** [comment]
官网下载的稳定版本，想用dockerized，不稳定的没敢尝试

**Comment by iredmail** [comment]
我刚才从官网下载了版本并检查了文件 `functions/packages.sh`，Ubuntu 20.04 没有使用 python-pymysql 这个包。
麻烦贴一下 `/etc/os-release` 文件的内容。

**Comment by ControlByDestiny** [comment]
我记错系统的版本号了，不是20.04，是18.04。(。・＿・。)ﾉI’m sorry~
![image](https://user-images.githubusercontent.com/28295419/90500724-da6d9e00-e17d-11ea-8698-379e2bfb119c.png)

**Comment by iredmail** [comment]
你的系统使用的 apt 源有问题。参考我的：

```
# cat /etc/os-release 
...
VERSION="18.04.5 LTS (Bionic Beaver)"
...

# apt-cache policy python-pymysql
python-pymysql:
  Installed: 0.8.0-1
  Candidate: 0.8.0-1
  Version table:
 *** 0.8.0-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ControlByDestiny** [comment]
好的，我试试
