### ISSUE TITLE
iRedAdmin 1.1 (beta) error

### ISSUE THREAD

**Issue by bartoruiz** [iredmail/iRedMail#79]
==== REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER ====
- iRedMail version (check /etc/iredmail-release): 1.3.1 MARIADB edition.
- Deployed with iRedMail Easy or the downloadable installer? Latest Downloadable installer (https://github.com/iredmail/iRedMail/archive/master.zip)
- Linux/BSD distribution name and version: Ubuntu 20.04 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MariaDB
- Web server (Apache or Nginx): Nginx

Install finishes without any issues, except:
iRedAdmin-beta.tar.bz2 does not seem to work properly.  Changing postmaster's password ends in a "internal server error" result, creating an user too.

**Comment by iredmail** [comment]
- Please download iRedMail-1.3.1 from our website: https://www.iredmail.org/download.html 
- Do not try github development edition.
