### ISSUE TITLE
Dockerize Iredmail as an option for deployment

### ISSUE THREAD

**Issue by jawabuu** [iredmail/iRedMail#8]
Hey @iredmail ,
I would like to inquire if there is an interest in dockerizing iredmail as an option for deployment.
I have seen this discussion
https://forum.iredmail.org/topic13826-iredmail-and-docker-architecture-proposal.html
where some members of the community seemed  reluctant.
A proposal that has since stalled here
https://github.com/kawaii/iredmail-docker
I have also come across this
https://www.github.com/lejmr/iredmail-docker
which seems to work okay but all the components are bundled into the docker image.
My proposal - if you are fine with it - is to work on a docker deployment for iredmail which would;
1. Maintain the current structure of the project
2. Be entirely option so it can co-exist with the current codebase.
3. Split the components into individual services to allow for better customization.

The advantages of this approach would be
1. It would be consistent with current deployments of Iredmail so migration to/from docker-iredmail would be seamless
2. Deployment would always be up to date and follow versioning of core iredmail
3. _Optional_ and Non-Intrusive

Let me know what you think

**Comment by iredmail** [comment]
Dear @jawabuu,

I sent you a link to visit the work-in-progress docker edition. Feel free to check all existing files in the repo, feedback/suggestions/corrections are always welcome. :)

**Comment by jawabuu** [comment]
This is excellent.
I'll get on it right away. Hoping to have something for you soon!!

**Comment by TitanFighter** [comment]
Hi @iredmail 
Do you have any ETA or could you at least share the current stage (alpha, beta, release candidate)?

Also if you can invite me I can test with docker compose and Lets encrypt and write instruction.

**Comment by iredmail** [comment]
hi @TitanFighter 

Sent the invitation to private github repo: https://github.com/iredmail/dockerized
Postfix, dovecot, amavisd, clamav, spamassassin, iRedAPD, mlmmj, mlmmjadmin, Roundcube are all working. Please help test.

**Comment by iredmail** [comment]
Dear all,

Beta image is now available on Docker Hub: https://hub.docker.com/r/iredmail/mariadb
