### ISSUE TITLE
Fail2Ban not creating firewall rules due to nftables not started

### ISSUE THREAD

**Issue by eelmasllari** [iredmail/iRedMail#80]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.1
- Deployed with iRedMail Easy or the downloadable installer?: Installer
- Linux/BSD distribution name and version: Debian 10
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MariaDB
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro?: No

Fail2Ban was banning IPs, but not creating the necessary firewall rules. Errors similar to the following were in /var/log/syslog (N.B. nothing was listed in /var/log/fail2ban.log)

    Aug 27 09:46:34 mx fail2ban.actions        [28411]: NOTICE  [dovecot] Ban 1.1.1.1
    Aug 27 09:46:34 mx fail2ban.utils          [28411]: Level 39 7fdbb07d24b8 -- exec: nft add set inet filter f2b-dovecot \{ type ipv4_addr\; \}
    nft insert rule inet filter input tcp dport \{ 80,443,25,587,465,110,995,143,993,4190 \} ip saddr @f2b-dovecot reject
    Aug 27 09:46:34 mx fail2ban.utils          [28411]: ERROR   7fdbb07d24b8 -- stderr: 'add set inet filter f2b-dovecot { type ipv4_addr; }'
    Aug 27 09:46:34 mx fail2ban.utils          [28411]: ERROR   7fdbb07d24b8 -- stderr: 'insert rule inet filter input tcp dport { 80,443,25,587,465,110,995, 143,993,4190 } ip saddr @f2b-dovecot reject'

Cause: The nftables service was not enabled by default in Debian, therefore the configuration that iRedMail creates in /etc/nftables.conf was never loaded. As a result, no table "inet filter" exists, only the default "ip filter", which results in the errors above.

Solution: start nftables service and set it to start by default (systemctl enable nftables), then restarted fail2ban.

Suggestion for solving problem in the future: the installer should make sure the nftables service is set to start by default.

**Comment by iredmail** [comment]
According to [source code](https://github.com/iredmail/iRedMail/blob/1.3.1/functions/cleanup.sh#L135), service `nftables` should be enabled by iRedMail installer.

Did you see any error related to the command (mentioned in above source code line) in file `iRedMail-1.3.1/runtime/install.log` on your server?

**Comment by iredmail** [comment]
Closed due to no further update.
