### ISSUE TITLE
iRedMail redirects my website address automatically from `example.com` to `example.com/mail`

### ISSUE THREAD

**Issue by hooshbartar** [iredmail/iRedMail#81]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.1 PGSQL edition.
- Deployed with iRedMail Easy or the downloadable installer? yes
- Linux/BSD distribution name and version:  CentOS 8
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  PGSQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? I don't know
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Hi there!
I have installed iredmail using the installation script following this tutorial: https://www.linuxbabe.com/mail-server/centos-8-iredmail-email-serverm , but after it's installation my website doesn't work and it redirects my web site address to /mail address(ie: redirects `example.com` to `example.com/mail` automatically).  I don't want this redirection and want to correct it but don't know how?

**Comment by iredmail** [comment]
- Check /etc/nginx/sites-enabled/00-default-ssl.conf.
- iRedMail requires a fresh / clean OS. Please always read official documents so that you won't miss important notes / warnings: https://docs.iredmail.org/#install

**Comment by hooshbartar** [comment]
> * Check /etc/nginx/sites-enabled/00-default-ssl.conf.
> * iRedMail requires a fresh / clean OS. Please always read official documents so that you won't miss important notes / warnings: https://docs.iredmail.org/#install

This is the content of that file:

```

#
# Note: This file must be loaded before other virtual host config files,
#
# HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    include /etc/nginx/templates/misc.tmpl;
    include /etc/nginx/templates/ssl.tmpl;
    include /etc/nginx/templates/iredadmin.tmpl;
    include /etc/nginx/templates/roundcube.tmpl;
    include /etc/nginx/templates/sogo.tmpl;
    include /etc/nginx/templates/netdata.tmpl;
    include /etc/nginx/templates/php-catchall.tmpl;
    include /etc/nginx/templates/stub_status.tmpl;
}
~
~
"/etc/nginx/sites-enabled/00-default-ssl.conf" 21L, 597C

```
I should mention my domain address hasn't SSL certification, maybe the problem is because of that? But how can I fix it?

**Comment by iredmail** [comment]
- Check the path of `root` directive to your website directory, then restart / reload nginx service.
- Check file `/var/www/html/index.html`.

**Comment by hooshbartar** [comment]
> * Check the path of `root` directive to your website directory, then restart / reload nginx service.
> * Check file `/var/www/html/index.html`.

Thanks!
I have also another question. in `domain/mail` address my username and password doesn't work!(It was working yesterday)m but in `domain/iredmailadmin` it works! Why?!

**Comment by iredmail** [comment]
- Is Dovecot service running?
- Please check log files `/var/log/dovecot/*.log` to figure it out.

**Comment by hooshbartar** [comment]
> * Check the path of `root` directive to your website directory, then restart / reload nginx service.
> * Check file `/var/www/html/index.html`.

I edited the mentioned file's content from:

`<html><head><meta HTTP-EQUIV="REFRESH" content="0; url=/mail."></head></html>
`

To 

`<html><head><meta HTTP-EQUIV="REFRESH" content="0; url=/"></head></html>
`

But still it redirects requests to `/` to `/mail`.

**Comment by iredmail** [comment]
Remove this `/var/www/html/index.html`, so that i will use your own `index.php` file.

**Comment by hooshbartar** [comment]
> /var/www/html/index.html

I removed that file but still it redirects to `/mail`
