### ISSUE TITLE
sogo 4 not avaialble (403 error)

### ISSUE THREAD

**Issue by kruisdraad** [iredmail/iRedMail#83]
manually set to 5 and then it works.

**Comment by kruisdraad** [comment]
its means you cannot download it , it gives a 403 error

**Comment by kruisdraad** [comment]
changing SOGO_VERSION in the conf from 4 to 5 solves it

**Comment by iredmail** [comment]
Please be clear.

- How did you download SOGo 4? Which URL?

**Comment by iredmail** [comment]
OK, i got it. SOGo team removed SOGo 4 nightly build from their server:
http://packages.inverse.ca/SOGo/nightly/4/

Not sure whether it's a temporary removal, or a permanent one. Let's wait for some time.

**Comment by iredmail** [comment]
Reported to SOGo bug tracker:
https://sogo.nu/bugs/view.php?id=5157

**Comment by iredmail** [comment]
- Confirmed: SOGo team removed v3 + v4 nightly build repositories permanently. https://sogo.nu/bugs/view.php?id=5157
- I re-packaged iRedMail-1.3.1 and switch SOGo to v5.
