### ISSUE TITLE
after install iredmail on ubuntu 20.04 admin dashbord not working

### ISSUE THREAD

**Issue by acidzz** [iredmail/iRedMail#86]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release):1.3.1 
- Deployed with iRedMail Easy or the downloadable installer? installer
- Linux/BSD distribution name and version: ubuntu 20.4
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): LDAP
- Web server (Apache or Nginx):Nginx 
- Manage mail accounts with iRedAdmin-Pro? no
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Resolve this issue: this install don't have depend pip install pymysql
after install work great

**Comment by iredmail** [comment]
iRedMail installer will try to install pip2 on Ubuntu 20.04:
https://github.com/iredmail/iRedMail/blob/1.3.1/functions/packages.sh#L724

Did you notice any related error on console?

**Comment by iredmail** [comment]
Closed due to no further update.
