### ISSUE TITLE
Feature Request: Add Mailman

### ISSUE THREAD

**Issue by Franky1** [iredmail/iRedMail#88]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 
- Deployed with iRedMail Easy or the downloadable installer?
- Linux/BSD distribution name and version: 
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): 
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro?
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

**FEATURE REQUEST**

Since **mlmmj** doesn't seem to be updated anymore (last update is from 2017) and the setup of mlmmj under iRedMail is quite cumbersome, I would like to suggest to support the mailing list manager **Mailman**.

**Comment by iredmail** [comment]
Dear @Franky1, we have no plan to replace mlmmj with mailman yet. sorry.
