### ISSUE TITLE
centos 8 中数据库为postgresql 13 会安装异常

### ISSUE THREAD

**Issue by crazyfd** [iredmail/iRedMail#89]
OS: CentOS Linux release 8.2.2004
使用最新版的安装程序，数据库为postgresql ，数据库安装源的数据库是默认安装了PGSQL版本13，结果会报错
 + < DEBUG > Initialize PostgreSQL databases.
/root/iRedMail-1.3.1/functions/postgresql.sh: line 37: postgresql-setup: command not found
 + < DEBUG > Service control: stop postgresql.
Failed to stop postgresql.service: Unit postgresql.service not loaded.
 + < DEBUG > Service control: start postgresql.
Failed to start postgresql.service: Unit postgresql.service not found.
 + < DEBUG > Import iRedAPD database template.
cp: target '/var/lib/pgsql/data/tmp/' is not a directory
psql: error: could not connect to server: could not connect to server: No such file or directory

**Comment by iredmail** [comment]
确认 pgsql 软件包下载正常么？

**Comment by crazyfd** [comment]
> 确认 pgsql 软件包下载正常么？

[root@local ~]# yum install  postgresql
Last metadata expiration check: 1:18:16 ago on Mon 12 Oct 2020 08:24:08 AM CEST.
Package postgresql13-13.0-1PGDG.rhel8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

我看了下系统默认数据库安装的目录位置在/var/lib/pgsql/13，软件目录是在/usr/pgsql-13
和你脚本的路径有些不一样

**Comment by iredmail** [comment]
> postgresql13-13.0-1PGDG.rhel8.x86_64

你这不是 CentOS 官方 yum 仓库里的包。我们只支持 CentOS 官方和 EPEL 仓库的软件包。
