### ISSUE TITLE
#1709 - Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by Blisk** [iredmail/iRedMail#90]
I use centos 7.8
when I try to create this table in phpmyadmin I get error
https://raw.githubusercontent.com/iredmail/iRedMail/1.3/samples/fail2ban/sql/fail2ban.mysql

#1709 - Index column size too large. The maximum column size is 767 bytes.

**Comment by iredmail** [comment]
Replace `VARCHAR(255)` by VARCHAR(100)` for column `ports` should fix it:
```
`ports` VARCHAR(100) NOT NULL DEFAULT '',
```

**Comment by iredmail** [comment]
@Blisk Does it work for you?

**Comment by Blisk** [comment]
I didn't try that because what I did is I put into sql table ROW_FORMAT=DYNAMIC
and that worked

**Comment by iredmail** [comment]
Try to shorten the length of `ports` and try again.

btw, which MySQL/MariaDB version are you running?

**Comment by iredmail** [comment]
Closed due to no further update.

**Comment by Blisk** [comment]
Still doesn't work
I tried this
-- Used to store banned/unbanned clients
CREATE TABLE IF NOT EXISTS banned (
id BIGINT(20) UNSIGNED AUTO_INCREMENT,
-- Banned client IP address
ip VARCHAR(46) NOT NULL DEFAULT '',
-- A list of banned network ports, separated by comma
ports VARCHAR(50) NOT NULL DEFAULT '',
-- protocol: tcp, udp, ...
protocol VARCHAR(10) NOT NULL DEFAULT 'tcp',
-- Fail2ban jail name
jail VARCHAR(50) NOT NULL DEFAULT '',
-- The server hostname which the ban/unban happens
hostname VARCHAR(255) NOT NULL DEFAULT '',
country VARCHAR(255) NOT NULL DEFAULT '',
-- reverse DNS name of banned IP address.
rdns VARCHAR(255) NOT NULL DEFAULT '',
-- number of times the failure occurred in the log file.
-- we use Fail2ban action tag ipjailfailures here.
failures INT(2) NOT NULL DEFAULT 0,
-- matched log lines.
-- we use Fail2ban action tag ipjailmatches here.
loglines TEXT,
-- When the ban happens
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- if remove=1, ip will be removed by cron job.
remove TINYINT(1) DEFAULT 0,
PRIMARY KEY (id),
UNIQUE INDEX (ip, ports, protocol),
INDEX (hostname),
INDEX (rdns),
INDEX (jail),
INDEX (country),
INDEX (timestamp),
INDEX (remove)
) ENGINE=InnoDB;


and get error 
#1709 - Index column size too large. The maximum column size is 767 bytes. 


5.5.65-MariaDB - MariaDB Server

**Comment by iredmail** [comment]
Interesting, this SQL structure works fine on my local testing machine, CentOS 7.8.2003.

What's the settings in your `/etc/my.cnf`?
[code]
[client]
default-character-set = utf8mb4

[mysqld]
character-set-server    = utf8mb4
collation-server        = utf8mb4_unicode_ci
...
[/code]

**Comment by Blisk** [comment]
[client]
default-character-set = utf8mb4

[mysqld]
#bind-address            = 127.0.0.1
port                    = 3306
character-set-server    = utf8mb4
collation-server        = utf8mb4_unicode_ci
#datadir                 = /var/lib/mysql
#socket                  = /var/lib/mysql/mysql.sock
#user                    = mysql

#innodb_large_prefix=true
#innodb_file_format=barracuda
#innodb_file_per_table=1

innodb_large_prefix=TRUE
innodb_file_per_table=TRUE
innodb_large_prefix=on
innodb_file_format=Barracuda

#general_log = 1
#general_log_file = /var/log/mysql.log

#slow_query_log
#slow_query_log_file = /var/log/mysql_slow.log

skip-external-locking
#skip-bdb
#skip-networking

# Disable query cache
query-cache-type    = 0
query-cache-size    = 0

thread_cache_size   = 8
open_files_limit    = 65535
max_connections     = 1024
#max_connect_errors = 150

**Comment by iredmail** [comment]
Almost same my.cnf, i have no idea why it doesn't work on your server. :(

**Comment by Blisk** [comment]
I am soure I am not the only one.
And there is alot of people with this problem when I google it

#1709 - Index column size too large. The maximum column size is 767 bytes.
