### ISSUE TITLE
iRedAdmin不能在Python3环境下运行

### ISSUE THREAD

**Issue by ymilv** [iredmail/iRedMail#92]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.1
- Deployed with iRedMail Easy or the downloadable installer?download
- Linux/BSD distribution name and version: Ubuntu Server 20.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL
- Web server (Apache or Nginx):Nginx
- Manage mail accounts with iRedAdmin-Pro?No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

因为Ubuntu 20.04移除了Python2的支持，所以安装后iRedAdmin无法启动，访问显示502错误。
强行安装Python2.7后，直接运行iredadmin.py可以在8080端口工作。但uwsgi启动iredadmin的ini文件无法运行，提示uwsgi缺少"python.so"和"syslog.so"插件，但uwsgi的这两个插件只支持python3，uwsgi-plugin-python和uwsgi-plugin-syslog在20.04下无法安装。
--btw：iredadmin的文件中有几处在python3中有语法错误，这个很容易修改，但最终还是卡在了uwsgi上。
iRedMail非常好，谢谢你的工作，希望尽快全面转到python3。

**Comment by iredmail** [comment]
新版本 iRedMail-1.3.2 即将发布，所有 python 组件都迁移到 python 3 了。请耐心等待。
也可以从 github 直接 clone 最新的开发版本，完美支持 py3。
