### ISSUE TITLE
Feature request: use classic debian upgrade model

### ISSUE THREAD

**Issue by drajar** [iredmail/iRedMail#96]
Hi

Congrats for great work! 

For debian, classic upgrade method is:
apt update
apt upgrade. 

It will be great if iredmail and all components can be upgrade this classic way. 

Best regards, 
Dragoș

**Comment by iredmail** [comment]
iredapd, mlmmjadmin, Roundcube, netdata and iRedAdmin(-Pro) are upgraded manually with source tarballs, others are done with “apt”.
