### ISSUE TITLE
Email Sent To Gmail Doesn't Look Like It Supports S/MIME Encryption. Does iRedMail support S/MIME?

### ISSUE THREAD

**Issue by vthg2themax** [iredmail/iRedMail#97]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.2
- Deployed with iRedMail Easy or the downloadable installer? Yes.
- Linux/BSD distribution name and version: Ubuntu 20.04LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): PGSQL
- Web server (Apache or Nginx): Nginx.
- Manage mail accounts with iRedAdmin-Pro? No.
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

**Comment by iredmail** [comment]
- S/MIME is a client side feature, not a mail server side.
- SOGo groupware supports it, you can give it a try.
