### ISSUE TITLE
Implicit TLS ("SMTPS") is not deprecated

### ISSUE THREAD

**Issue by josch700** [iredmail/iRedMail#98]
Hi,

iRedMail should enable Submission over Implicit TLS ("SMTPS") via Port 465 per default, as described in RFC8314 and iredmail/docs#8 .
It is more secure than connecting to Port 587 (plaintext) and then initiating TLS via a command, and should be considered superior (see also the RFC).
Therefore, the Postfix configs and firewall rules need to be changed to reflect this.

**Comment by iredmail** [comment]
Closed as `won't fix`. Sorry.
